/**
 * v357–v372 deepened SA counselling batch (6 lines × 5 langs) — STG/EML PHC Batches E–F.
 * E: HIV/TB follow-on + quinine. F: supportive misc (vitamins, derm, psych adjuncts).
 * Original Materia educational scripts only — no invented doses, ECG intervals, IU amounts,
 * contact times, or depot intervals.
 * Types kept local to avoid circular import with counselling.ts.
 */

export type ExtLang = "en" | "zu" | "af" | "st" | "xh";

export interface ExtScript {
  lang: ExtLang;
  lines: string[];
  sourceNote: string;
  publishState: "published" | "draft";
}

const EN_NOTE = "Materia original counselling — founder-reviewed educational layer";
const ZU_NOTE = "Materia original isiZulu counselling — founder-reviewed educational layer";
const AF_NOTE = "Materia original Afrikaans counselling — founder-reviewed educational layer";
const ST_NOTE = "Materia original Sesotho counselling — founder-reviewed educational layer";
const XH_NOTE = "Materia original isiXhosa counselling — founder-reviewed educational layer";

function five(
  en: string[],
  zu: string[],
  af: string[],
  st: string[],
  xh: string[],
): Partial<Record<ExtLang, ExtScript>> {
  return {
    en: { lang: "en", publishState: "published", sourceNote: EN_NOTE, lines: en },
    zu: { lang: "zu", publishState: "published", sourceNote: ZU_NOTE, lines: zu },
    af: { lang: "af", publishState: "published", sourceNote: AF_NOTE, lines: af },
    st: { lang: "st", publishState: "published", sourceNote: ST_NOTE, lines: st },
    xh: { lang: "xh", publishState: "published", sourceNote: XH_NOTE, lines: xh },
  };
}

export const COUNSELLING_V357_TO_V372: Record<string, Partial<Record<ExtLang, ExtScript>>> = {
  "mol-emtricitabine": five(
    [
      "Emtricitabine (FTC) is an NRTI used in HIV regimens and selected PrEP combinations — take every day as your ART or PrEP plan directs.",
      "Materia does not invent a dose, fixed-dose pairing, or renal cut-off — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about kidney disease, hepatitis B status, pregnancy plans, and ALL other medicines before starting or stopping.",
      "Do not stop suddenly if you have hepatitis B without a clinician plan — flares can occur; ask what monitoring applies to you.",
      "Ask how this tablet fits with your other ART medicines and what to do if you miss a dose — do not invent a double-up rule.",
      "If severe rash, yellow eyes, unusual muscle pain, or breathing difficulty develops — seek care urgently.",
    ],
    [
      "I-emtricitabine (FTC) i-NRTI esetshenziswa ezinhlelweni ze-HIV nasezinhlanganisweni ezikhethiwe ze-PrEP — thatha nsuku zonke njengoba uhlelo lwakho lwe-ART noma i-PrEP lushiwo.",
      "I-Materia ayiqambi umthamo, ukubhanqa kwe-fixed-dose, noma umkhawulo wezinso — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesifo sezinso, isimo se-hepatitis B, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala noma ukuyeka.",
      "Ungayeki ngokuzumayo uma une-hepatitis B ngaphandle kohlelo lukadokotela — ukuqubuka kungenzeka; buza ukuqapha okusebenza kuwe.",
      "Buza ukuthi leli philisi lihlangana kanjani namanye amaphilisi e-ART nokuthi wenzani uma uphuthelwa — ungacabangi umthetho wokuphinda kabili.",
      "Uma ukuqubuka okukhulu, amehlo aphuzi, ubuhlungu bemisipha obungajwayelekile, noma ubunzima bokuphefumula kuvela — funa usizo ngokushesha.",
    ],
    [
      "Emtrisitabien (FTC) is 'n NRTI in MIV-regimens en geselekteerde PrEP-kombinasies — neem elke dag soos jou ART- of PrEP-plan aandui.",
      "Materia versin nie 'n dosis, vaste-dosis paring, of nierafsnyding nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van niersiekte, hepatitis B-status, swangerskapplanne, en ALLE ander medisyne voor jy begin of stop.",
      "Moenie skielik stop as jy hepatitis B het sonder 'n klinikusplan nie — opvlams kan voorkom; vra watter monitering op jou van toepassing is.",
      "Vra hoe hierdie tablet by jou ander ART-medisyne pas en wat om te doen as jy 'n dosis mis — moenie 'n verdubbelingsreël versin nie.",
      "As ernstige uitslag, geel oë, ongewone spierpyn, of asemnood ontwikkel — soek dringend sorg.",
    ],
    [
      "Emtricitabine (FTC) ke NRTI e sebelisoang litokisetso tsa HIV le metsoako e khethiloeng ea PrEP — e nke letsatsi le letsatsi joalo ka ha moralo oa hau oa ART kapa PrEP o laela.",
      "Materia ha e iqape tekanyo, ho kopanya ha fixed-dose, kapa moeli oa liphio — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka lefu la liphio, boemo ba hepatitis B, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala kapa u emisa.",
      "U se ke ua emisa ka tšohanyetso haeba u na le hepatitis B ntle le moralo oa ngaka — ho phatloha ho ka hlaha; botsa tlhokomelo e sebetsang ho uena.",
      "Botsoa hore na pilisi ena e kenella joang le meriana e meng ea ART le hore na u etsang haeba u fosa tekanyo — u se ke ua iqapa molao oa ho pheta habeli.",
      "Haeba lekhopho le matla, mahlo a mosehla, bohloko ba mesifa bo sa tloaelehang, kapa ho hema thata ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-emtricitabine (FTC) yi-NRTI esetyenziswa kwiinkqubo ze-HIV kunye neendibaniselwano ezikhethiweyo ze-PrEP — thatha yonke imihla njengoko isicwangciso sakho se-ART okanye i-PrEP sisho.",
      "I-Materia ayiyiqiqi idosi, ukudibanisa kwe-fixed-dose, okanye umda wezintso — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngesifo sezintso, imeko ye-hepatitis B, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala okanye ukuyeka.",
      "Ungayeki ngequbuliso ukuba une-hepatitis B ngaphandle kwesicwangciso sogqirha — ukuqhuma kungenzeka; buza ukujonga okusebenza kuwe.",
      "Buza ukuba eli pilisi lihlangana njani namanye amayeza e-ART nokuba wenza ntoni ukuba uphuthelwa — ungacingi umthetho wokuphinda kabini.",
      "Ukuba irhashalala enzima, amehlo atyheli, intlungu yemisipha engaqhelekanga, okanye ubunzima bokuphefumla kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-abacavir": five(
    [
      "Abacavir (ABC) is an NRTI used in selected HIV regimens — hypersensitivity can be severe; never rechallenge after a labelled hypersensitivity reaction.",
      "Materia does not invent a dose or HLA screening algorithm — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about prior abacavir reactions, liver disease, pregnancy plans, and ALL other medicines before starting.",
      "Stop and seek urgent care if fever, rash, nausea, muscle pain, or breathing difficulty cluster after starting — do not restart without specialist advice.",
      "Ask how this medicine fits your ART combination and what blood tests are planned for monitoring.",
      "Carry awareness of hypersensitivity warning signs — ask your clinic for the patient alert card if one is provided.",
    ],
    [
      "I-abacavir (ABC) i-NRTI esetshenziswa ezinhlelweni ezikhethiwe ze-HIV — ukungazwani kungaba kubi kakhulu; ungaphindi uyizame ngemva kokungazwani okulebula.",
      "I-Materia ayiqambi umthamo noma i-algorithm yokuhlola i-HLA — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngokungazwani kwangaphambilini ne-abacavir, isifo sesibindi, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Yeka futhi funa usizo oluphuthumayo uma umkhuhlane, ukuqubuka, isicanucanu, ubuhlungu bemisipha, noma ubunzima bokuphefumula kuhlangana ngemva kokuqala — ungaphindi uqale ngaphandle kweseluleko sochwepheshe.",
      "Buza ukuthi lo muthi uhlangana kanjani nenhlanganisela yakho ye-ART nokuthi yiziphi izivivinyo zegazi ezicwangisiwe.",
      "Thwala ukwazi izimpawu zokuxwayisa zokungazwani — buza ikliniki yakho ngekhadi lokuxwayisa uma linikezwa.",
    ],
    [
      "Abakawir (ABC) is 'n NRTI in geselekteerde MIV-regimens — hipersensitiwiteit kan ernstig wees; heruitdaging nooit na 'n geëtiketteerde hipersensitiwiteitsreaksie nie.",
      "Materia versin nie 'n dosis of HLA-toetsalgoritme nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van vorige abakawir-reaksies, lewersiekte, swangerskapplanne, en ALLE ander medisyne voor jy begin.",
      "Stop en soek dringende sorg as koors, uitslag, naarheid, spierpyn, of asemnood saamgroep na begin — moenie herbegin sonder spesialisadvies nie.",
      "Vra hoe hierdie medisyne by jou ART-kombinasie pas en watter bloedtoetse vir monitering beplan is.",
      "Dra bewustheid van hipersensitiwiteit waarskuwingstekens — vra jou kliniek vir die pasiëntwaarskaart as een verskaf word.",
    ],
    [
      "Abacavir (ABC) ke NRTI e sebelisoang litokisetso tse khethiloeng tsa HIV — hypersensitivity e ka ba matla; u se ke ua e leka hape ka mor'a karabelo ea hypersensitivity e nang le ileibole.",
      "Materia ha e iqape tekanyo kapa algorithm ea tlhahlobo ea HLA — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka likarabelo tsa pejana tsa abacavir, lefu la sebete, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "Emissa 'me u batle thuso ea potlako haeba feberu, lekhopho, ho nyekeloa ke pelo, bohloko ba mesifa, kapa ho hema thata ho kopana ka mor'a ho qala — u se ke ua qala hape ntle le keletso ea setsebi.",
      "Botsoa hore na meriana ena e kenella joang motsoako oa hau oa ART le hore na ke liteko life tsa mali tse reriloeng bakeng sa tlhokomelo.",
      "Jara temoho ea matšoao a temoso a hypersensitivity — botsa kliniki ea hau ka karete ea temoso ea mokuli haeba e fanoa.",
    ],
    [
      "I-abacavir (ABC) yi-NRTI esetyenziswa kwiinkqubo ezikhethiweyo ze-HIV — i-hypersensitivity inokuba nzima kakhulu; ungaphindi uyizame emva kwempendulo ye-hypersensitivity enelebula.",
      "I-Materia ayiyiqiqi idosi okanye i-algorithm yokuvavanya i-HLA — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngeempendulo zangaphambili ze-abacavir, isifo sesibindi, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Yeka kwaye funa uncedo olungxamisekileyo ukuba umkhuhlane, irhashalala, isicanucanu, intlungu yemisipha, okanye ubunzima bokuphefumla kudibana emva kokuqala — ungaphindi uqale ngaphandle kweengcebiso zegcisa.",
      "Buza ukuba eli yeza lihlangana njani nendibaniselwano yakho ye-ART nokuba zeziphi iimvavanyo zegazi ezicwangcisiweyo.",
      "Thwala ulwazi lweempawu zesilumkiso se-hypersensitivity — buza iklinikhi yakho ngekhadi lesilumkiso lesigulana ukuba linikezelwa.",
    ],
  ),

  "mol-zidovudine": five(
    [
      "Zidovudine (AZT) is an NRTI used in selected HIV and perinatal pathways — anaemia and white-cell effects can occur.",
      "Materia does not invent a dose or PMTCT schedule — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about anaemia history, liver disease, pregnancy stage, and ALL other medicines before starting.",
      "Ask which blood counts are monitored and what fatigue or unusual bruising should trigger an earlier review.",
      "Take exactly as your ART or perinatal plan directs — do not invent a missed-dose double-up rule.",
      "If severe tiredness, pale gums, fever with sore throat, or unusual bruising develops — seek care urgently.",
    ],
    [
      "I-zidovudine (AZT) i-NRTI esetshenziswa ezindleleni ezikhethiwe ze-HIV nezokubeletha — i-anaemia nemiphumela yamaseli amhlophe kungenzeka.",
      "I-Materia ayiqambi umthamo noma uhlelo lwe-PMTCT — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngomlando we-anaemia, isifo sesibindi, isigaba sokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Buza ukuthi yimaphi ukubalwa kwegazi okuqashiwe nokuthi ukukhathala noma ukulimala okungajwayelekile kufanele kuqale ukubuyekezwa kusenesikhathi.",
      "Thatha njengoba uhlelo lwakho lwe-ART noma lokubeletha lushiwo — ungacabangi umthetho wokuphinda kabili uma uphuthelwa.",
      "Uma ukukhathala okukhulu, izinhliziyo ezimpunga, umkhuhlane nomphimbo obuhlungu, noma ukulimala okungajwayelekile kuvela — funa usizo ngokushesha.",
    ],
    [
      "Sidovudien (AZT) is 'n NRTI in geselekteerde MIV- en perinatale paaie — anemie en wit-sel effekte kan voorkom.",
      "Materia versin nie 'n dosis of PMTCT-skedule nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van anemiegeskiedenis, lewersiekte, swangerskapstadium, en ALLE ander medisyne voor jy begin.",
      "Vra watter bloedtellings gemonitor word en watter moegheid of ongewone kneusings 'n vroeër hersiening moet sneller.",
      "Neem presies soos jou ART- of perinatale plan aandui — moenie 'n verdubbelingsreël vir 'n gemiste dosis versin nie.",
      "As ernstige moegheid, bleek tandvleis, koors met seer keel, of ongewone kneusings ontwikkel — soek dringend sorg.",
    ],
    [
      "Zidovudine (AZT) ke NRTI e sebelisoang litseleng tse khethiloeng tsa HIV le tsa perinatal — anaemia le litlamorao tsa lisele tse sootho li ka hlaha.",
      "Materia ha e iqape tekanyo kapa kemiso ea PMTCT — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka nalane ea anaemia, lefu la sebete, mohato oa bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "Botsoa hore na ke lipalo life tsa mali tse hlokomeloang le hore na mokhathala kapa ho otlaha ho sa tloaelehang ho lokela ho qala tlhahlobo pele.",
      "E nke hantle joalo ka ha moralo oa hau oa ART kapa oa perinatal o laela — u se ke ua iqapa molao oa ho pheta habeli haeba u fositse.",
      "Haeba mokhathala o matla, marenana a sootho, feberu le 'metso o bohloko, kapa ho otlaha ho sa tloaelehang ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-zidovudine (AZT) yi-NRTI esetyenziswa kwiindlela ezikhethiweyo ze-HIV kunye nezokubeleka — i-anaemia kunye neziphumo zeeseli ezimhlophe zingenzeka.",
      "I-Materia ayiyiqiqi idosi okanye ishedyuli ye-PMTCT — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngembali ye-anaemia, isifo sesibindi, inqanaba lokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Buza ukuba zeziphi iibalwa zegazi ezijongwayo nokuba kukudinwa okanye ukulimala okungaqhelekanga okufanele kuqalise ukujongwa kwangethuba.",
      "Thatha kanye njengoko isicwangciso sakho se-ART okanye sokubeleka sisho — ungacingi umthetho wokuphinda kabini ukuba uphuthelwe.",
      "Ukuba ukudinwa okukhulu, iintsini ezimdaka, umkhuhlane nomqala obuhlungu, okanye ukulimala okungaqhelekanga kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-lopinavir": five(
    [
      "Lopinavir is an HIV protease inhibitor usually taken with ritonavir boosting — interaction burden with other medicines is high.",
      "Materia does not invent a dose, booster ratio, or interaction list — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about liver disease, lipid problems, pregnancy plans, and ALL other medicines or herbal products before starting.",
      "Some formulations have food guidance — follow the labelled product; do not invent a meal rule.",
      "Ask how diarrhoea, nausea, or taste changes should be managed and when to return if they persist.",
      "If severe tummy pain, yellow eyes, rash with fever, or unexplained weakness develops — seek care urgently.",
    ],
    [
      "I-lopinavir i-HIV protease inhibitor ngokuvamile ethathwa ne-ritonavir yokukhulisa — umthwalo wokuxhumana namanye amaphilisi uphezulu.",
      "I-Materia ayiqambi umthamo, isilinganiso se-booster, noma uhlu lokuxhumana — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesifo sesibindi, izinkinga zama-lipid, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi noma imikhiqizo yamakhambi ngaphambi kokuqala.",
      "Ezinye izinhlobo zinemihlahlandlela yokudla — landela umkhiqizo onelebula; ungacabangi umthetho wokudla.",
      "Buza ukuthi uhudo, isicanucanu, noma ukushintsha kokunambitha kufanele kuphathwe kanjani nokuthi ubuyela nini uma kuqhubeka.",
      "Uma ubuhlungu besisu obukhulu, amehlo aphuzi, ukuqubuka nomkhuhlane, noma ubuthakathaka obungachazeki kuvela — funa usizo ngokushesha.",
    ],
    [
      "Lopinavir is 'n MIV-protease-inhibeerder gewoonlik met ritonavir-versterking geneem — interaksielading met ander medisyne is hoog.",
      "Materia versin nie 'n dosis, versterkerverhouding, of interaksielys nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van lewersiekte, lipiedprobleme, swangerskapplanne, en ALLE ander medisyne of kruieprodukte voor jy begin.",
      "Som formulerings het kosleiding — volg die geëtiketteerde produk; moenie 'n maaltydreël versin nie.",
      "Vra hoe diarree, naarheid, of smaakveranderinge bestuur moet word en wanneer om terug te kom as dit aanhou.",
      "As ernstige maagpyn, geel oë, uitslag met koors, of onverklaarde swakheid ontwikkel — soek dringend sorg.",
    ],
    [
      "Lopinavir ke HIV protease inhibitor e atisang ho nkuoa le ritonavir ea ho matlafatsa — mojaro oa ho sebelisana le meriana e meng o phahame.",
      "Materia ha e iqape tekanyo, karolelano ea booster, kapa lethathamo la ho sebelisana — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka lefu la sebete, mathata a lipid, merero ea bokhachane, le MERIANA EOHLE e meng kapa lihlahisoa tsa litlama pele u qala.",
      "Mefuta e meng e na le tataiso ea lijo — latela sehlahisoa se nang le ileibole; u se ke ua iqapa molao oa lijo.",
      "Botsoa hore na letshollo, ho nyekeloa ke pelo, kapa liphetoho tsa tatso li lokela ho laoloa joang le hore na u khutle neng haeba li tsoela pele.",
      "Haeba bohloko bo boholo ba mpa, mahlo a mosehla, lekhopho le feberu, kapa bofokoli bo sa hlaloseng bo hlaha — batla thuso ka potlako.",
    ],
    [
      "I-lopinavir yi-HIV protease inhibitor rhoqo ethathwa ne-ritonavir yokukhulisa — umthwalo wokudibana namanye amayeza uphezulu.",
      "I-Materia ayiyiqiqi idosi, umlinganiselo we-booster, okanye uluhlu lokudibana — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngesifo sesibindi, iingxaki ze-lipid, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza okanye iimveliso zamayeza ngaphambi kokuqala.",
      "Ezinye iintlobo zinesikhokelo sokutya — landela imveliso enelebula; ungacingi umthetho wokutya.",
      "Buza ukuba urhudo, isicanucanu, okanye utshintsho lokungcamla kufuneka kulawulwe njani nokuba ubuyela nini ukuba kuyaqhubeka.",
      "Ukuba intlungu enkulu yesisu, amehlo atyheli, irhashalala nomkhuhlane, okanye ubuthathaka obungachazekiyo buvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-darunavir": five(
    [
      "Darunavir is an HIV protease inhibitor used in selected boosted regimens — take with the booster your clinician pairs.",
      "Materia does not invent a dose or booster pairing — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about sulfa allergy, liver disease, pregnancy plans, and ALL other medicines before starting.",
      "Food guidance often matters for darunavir products — follow the labelled product; do not invent a meal rule.",
      "Ask what lipid and liver monitoring is planned and how this medicine interacts with your other ART.",
      "If severe rash, yellow eyes, dark urine, or breathing difficulty develops — seek care urgently.",
    ],
    [
      "I-darunavir i-HIV protease inhibitor esetshenziswa ezinhlelweni ezikhethiwe ezikhulisiwe — thatha ne-booster udokotela ayibhangqa nawe.",
      "I-Materia ayiqambi umthamo noma ukubhanqa kwe-booster — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela nge-allergy ye-sulfa, isifo sesibindi, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Imihlahlandlela yokudla ivamise ukubaluleka emikhiqizweni ye-darunavir — landela umkhiqizo onelebula; ungacabangi umthetho wokudla.",
      "Buza ukuthi yikuphi ukuqapha kwama-lipid nesibindi okucwangisiwe nokuthi lo muthi uxhumana kanjani ne-ART yakho.",
      "Uma ukuqubuka okukhulu, amehlo aphuzi, umchamo omnyama, noma ubunzima bokuphefumula kuvela — funa usizo ngokushesha.",
    ],
    [
      "Darunavir is 'n MIV-protease-inhibeerder in geselekteerde versterkte regimens — neem met die versterker wat jou klinikus paar.",
      "Materia versin nie 'n dosis of versterkerparing nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van sulfa-allergie, lewersiekte, swangerskapplanne, en ALLE ander medisyne voor jy begin.",
      "Kosleiding is dikwels belangrik vir darunavir-produkte — volg die geëtiketteerde produk; moenie 'n maaltydreël versin nie.",
      "Vra watter lipied- en lewermonitering beplan is en hoe hierdie medisyne met jou ander ART wissel.",
      "As ernstige uitslag, geel oë, donker urine, of asemnood ontwikkel — soek dringend sorg.",
    ],
    [
      "Darunavir ke HIV protease inhibitor e sebelisoang litokisetso tse khethiloeng tse matlafalitsoeng — e nke le booster eo ngaka ea hau e e kopanyang.",
      "Materia ha e iqape tekanyo kapa ho kopanya ha booster — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka allergy ea sulfa, lefu la sebete, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "Tataiso ea lijo hangata e bohlokoa bakeng sa lihlahisoa tsa darunavir — latela sehlahisoa se nang le ileibole; u se ke ua iqapa molao oa lijo.",
      "Botsoa hore na ke tlhokomelo efe ea lipid le sebete e reriloeng le hore na meriana ena e sebelisana joang le ART ea hau e meng.",
      "Haeba lekhopho le matla, mahlo a mosehla, moroto o lefifi, kapa ho hema thata ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-darunavir yi-HIV protease inhibitor esetyenziswa kwiinkqubo ezikhethiweyo ezikhulisiweyo — thatha ne-booster ugqirha ayidibanisa nawe.",
      "I-Materia ayiyiqiqi idosi okanye ukudibanisa kwe-booster — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha nge-allergy ye-sulfa, isifo sesibindi, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Isikhokelo sokutya rhoqo sibalulekile kwiimveliso ze-darunavir — landela imveliso enelebula; ungacingi umthetho wokutya.",
      "Buza ukuba kukuphi ukujonga kwe-lipid kunye nesibindi okucwangcisiweyo nokuba eli yeza lidibana njani ne-ART yakho.",
      "Ukuba irhashalala enzima, amehlo atyheli, umchamo omnyama, okanye ubunzima bokuphefumla kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-bedaquiline": five(
    [
      "Bedaquiline is used in selected drug-resistant TB regimens under programme oversight — QT and drug-interaction counselling are clinician-led.",
      "Materia does not invent a dose or ECG monitoring interval — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the TB team about heart rhythm problems, liver disease, pregnancy plans, and ALL other medicines before starting.",
      "Do not skip doses or stop early without the programme team — resistance risk is high with incomplete courses.",
      "Ask which other TB medicines are paired with bedaquiline and what side effects to report early.",
      "If palpitations, fainting, yellow eyes, or severe nausea develops — seek care urgently.",
    ],
    [
      "I-bedaquiline isetshenziswa ezinhlelweni ezikhethiwe ze-TB ephikisa imithi ngaphansi kokuqapha kohlelo — ukwelulekwa nge-QT nokuxhumana kwemithi kuqhutshwa odokotela.",
      "I-Materia ayiqambi umthamo noma isikhathi sokuqapha i-ECG — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba le-TB ngezinkinga zesigqi senhliziyo, isifo sesibindi, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Ungaphuthelwa imithamo noma uyeke kusenesikhathi ngaphandle kwethimba lohlelo — ubungozi bokuphikisa buphezulu ngezinkambo ezingaphelele.",
      "Buza ukuthi yimiphi eminye imithi ye-TB ehlanganiswe ne-bedaquiline nokuthi yiziphi izimpawu eziseceleni okufanele uzibike kusenesikhathi.",
      "Uma ukushaya kwenhliziyo, ukuquleka, amehlo aphuzi, noma isicanucanu esikhulu kuvela — funa usizo ngokushesha.",
    ],
    [
      "Bedakwilien word in geselekteerde middelweerstandige TB-regimens onder programtoesig gebruik — QT- en middelinteraksie berading is klinikus-gelei.",
      "Materia versin nie 'n dosis of EKG-moniteringsinterval nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die TB-span van hartritmeprobleme, lewersiekte, swangerskapplanne, en ALLE ander medisyne voor jy begin.",
      "Moenie dosisse oorslaan of vroeg stop sonder die programspan nie — weerstandsrisiko is hoog met onvolledige kursusse.",
      "Vra watter ander TB-medisyne met bedakwilien gepaar word en watter newe-effekte vroeg te rapporteer.",
      "As hartklop, floute, geel oë, of ernstige naarheid ontwikkel — soek dringend sorg.",
    ],
    [
      "Bedaquiline e sebelisoa litokisetso tse khethiloeng tsa TB e hanyetsang meriana tlas'a tlhokomelo ea lenaneo — keletso ea QT le ho sebelisana ha meriana e etelloa pele ke lingaka.",
      "Materia ha e iqape tekanyo kapa nako ea tlhokomelo ea ECG — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha sa TB ka mathata a morethetho oa pelo, lefu la sebete, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "U se ke ua fosa litekanyo kapa u emise pele ntle le sehlopha sa lenaneo — kotsi ea ho hanyetsa e phahame ka lithuto tse sa fellang.",
      "Botsoa hore na ke meriana efe e meng ea TB e kopantsoeng le bedaquiline le hore na ke litlamorao life tse lokelang ho tlalehoa kapele.",
      "Haeba ho otla ha pelo, ho akheha, mahlo a mosehla, kapa ho nyekeloa ke pelo ho matla ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-bedaquiline isetyenziswa kwiinkqubo ezikhethiweyo ze-TB ephikisa amayeza phantsi kokujonga inkqubo — iingcebiso ze-QT kunye nokudibana kwamayeza zikhokelwa ngoogqirha.",
      "I-Materia ayiyiqiqi idosi okanye ixesha lokujonga i-ECG — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela le-TB ngeengxaki zesingqisho sentliziyo, isifo sesibindi, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Ungaphuthelwa iidosi okanye uyeke kwangethuba ngaphandle kweqela lenkqubo — umngcipheko wokuphikisa uphezulu ngeekhosi ezingaphelelanga.",
      "Buza ukuba ngawaphi amanye amayeza e-TB adityaniswe ne-bedaquiline nokuba zeziphi iziphumo ecaleni ekufuneka uzixele kwangethuba.",
      "Ukuba ukubetha kwentliziyo, ukuquleka, amehlo atyheli, okanye isicanucanu esikhulu kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-quinine": five(
    [
      "Quinine is a cinchona-alkaloid antimalarial used in selected malaria pathways — severe malaria is a medical emergency.",
      "Materia does not invent a dose or infusion rate — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about heart rhythm problems, hearing issues, pregnancy, G6PD status if known, and ALL other medicines.",
      "Cinchonism symptoms (tinnitus, headache, nausea, vision changes) can occur — report them early to the care team.",
      "Ask what follow-up oral antimalarial plan comes after the acute phase and when blood tests are repeated.",
      "If hearing loss, severe vision change, irregular heartbeat, or collapse develops — seek emergency care immediately.",
    ],
    [
      "I-quinine i-antimalarial ye-cinchona-alkaloid esetshenziswa ezindleleni ezikhethiwe ze-malaria — i-malaria enzima yisimo esiphuthumayo sesokwelapha.",
      "I-Materia ayiqambi umthamo noma isilinganiso sokufaka emithanjeni — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngezinkinga zesigqi senhliziyo, izinkinga zokuzwa, ukukhulelwa, isimo se-G6PD uma saziwa, nawo WONKE amanye amaphilisi.",
      "Izimpawu ze-cinchonism (umsindo ezindlebeni, ikhanda, isicanucanu, ukushintsha kokubona) zingenzeka — zibike kusenesikhathi ethimbeni.",
      "Buza ukuthi yiluphi uhlelo lwe-antimalarial yomlomo olulandela isigaba esibucayi nokuthi izivivinyo zegazi ziphindwa nini.",
      "Uma ukulahlekelwa ukuzwa, ukushintsha kokubona okukhulu, ukushaya kwenhliziyo okungajwayelekile, noma ukuwa kuvela — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Kwinien is 'n cinchona-alkaloïed antimalaria middel in geselekteerde malaria-paaie — ernstige malaria is 'n mediese noodgeval.",
      "Materia versin nie 'n dosis of infusietempo nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van hartritmeprobleme, gehoorprobleme, swangerskap, G6PD-status indien bekend, en ALLE ander medisyne.",
      "Cinchonisme simptome (tinnitus, hoofpyn, naarheid, visiieveranderinge) kan voorkom — rapporteer dit vroeg aan die sorgspan.",
      "Vra watter opvolg mondelinge antimalaria-plan na die akute fase kom en wanneer bloedtoetse herhaal word.",
      "As gehoorverlies, ernstige visiieverandering, onreëlmatige hartklop, of ineenstorting ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Quinine ke antimalaria ea cinchona-alkaloid e sebelisoang litseleng tse khethiloeng tsa malaria — malaria e matla ke tšohanyetso ea bongaka.",
      "Materia ha e iqape tekanyo kapa sekhahla sa infusion — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka mathata a morethetho oa pelo, mathata a kutlo, bokhachane, boemo ba G6PD haeba bo tsejoa, le MERIANA EOHLE e meng.",
      "Matšoao a cinchonism (tinnitus, hlooho, ho nyekeloa ke pelo, liphetoho tsa pono) a ka hlaha — a tlalehe kapele ho sehlopha sa tlhokomelo.",
      "Botsoa hore na ke moralo ofe oa antimalaria oa molomo o latelang mohato o bohale le hore na liteko tsa mali li pheta neng.",
      "Haeba tahlehelo ea kutlo, phetoho e matla ea pono, ho otla ha pelo ho sa tloaelehang, kapa ho oa ho hlaha — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-quinine yi-antimalarial ye-cinchona-alkaloid esetyenziswa kwiindlela ezikhethiweyo ze-malaria — i-malaria enzima yimeko engxamisekileyo yezonyango.",
      "I-Materia ayiyiqiqi idosi okanye isantya sokugalela — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngeengxaki zesingqisho sentliziyo, iingxaki zokuva, ukukhulelwa, imeko ye-G6PD ukuba iyaziwa, kunye NAWO ONKE amanye amayeza.",
      "Iimpawu ze-cinchonism (umsindo ezindlebeni, intloko, isicanucanu, utshintsho lokubona) zingenzeka — zixele kwangethuba kwiqela lokhathalelo.",
      "Buza ukuba sesiphi isicwangciso se-antimalarial yomlomo esiza emva kwesigaba esibucala nokuba iimvavanyo zegazi ziphindwa nini.",
      "Ukuba ukulahlekelwa kukuva, utshintsho lokubona olukhulu, ukubetha kwentliziyo okungaqhelekanga, okanye ukuwa kuvela — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-retinol": five(
    [
      "Retinol (vitamin A) is used in selected deficiency and public-health supplementation pathways — excess is harmful in pregnancy.",
      "Materia does not invent an IU dose or age-band schedule — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about pregnancy or plans to conceive, liver disease, and ALL other vitamin A-containing products before taking more.",
      "Do not combine multiple high-dose vitamin A products unless a clinician has reviewed the total exposure.",
      "Ask whether this dose is for measles-pathway support, deficiency treatment, or routine supplementation in your setting.",
      "If severe headache, vomiting, peeling skin, or vision changes develop after high-dose use — seek care urgently.",
    ],
    [
      "I-retinol (ivitamini A) isetshenziswa ezindleleni ezikhethiwe zokuntuleka nokwengeza kwezempilo yomphakathi — ukweqisa kuyingozi ekukhulelweni.",
      "I-Materia ayiqambi umthamo we-IU noma uhlelo lwebhende yobudala — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngokukhulelwa noma izinhlelo zokukhulelwa, isifo sesibindi, nawo WONKE eminye imikhiqizo ene-vitamin A ngaphambi kokuthatha okuningi.",
      "Ungahlanganisi imikhiqizo eminingi ye-vitamin A yomthamo ophezulu ngaphandle kokuthi udokotela ubuyekeze ukuchayeka okuphelele.",
      "Buza ukuthi lo mthamo ungowe-measles-pathway, ukwelapha ukuntuleka, noma ukwengeza okujwayelekile endaweni yakho.",
      "Uma ikhanda elibi, ukuhlanza, isikhumba esihluba, noma ukushintsha kokubona kuvela ngemva komthamo ophezulu — funa usizo ngokushesha.",
    ],
    [
      "Retinol (vitamien A) word in geselekteerde tekort- en openbare-gesondheid aanvullingspaaie gebruik — oormaat is skadelik in swangerskap.",
      "Materia versin nie 'n IU-dosis of ouderdomsgroep-skedule nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van swangerskap of planne om swanger te word, lewersiekte, en ALLE ander vitamien A-bevattende produkte voor jy meer neem.",
      "Moenie verskeie hoë-dosis vitamien A-produkte kombineer nie tensy 'n klinikus die totale blootstelling nagegaan het.",
      "Vra of hierdie dosis vir masels-pad ondersteuning, tekortbehandeling, of roetine aanvulling in jou omgewing is.",
      "As ernstige hoofpyn, braking, skilferende vel, of visiieveranderinge na hoë-dosis gebruik ontwikkel — soek dringend sorg.",
    ],
    [
      "Retinol (vitamin A) e sebelisoa litseleng tse khethiloeng tsa khaello le tlatsetso ea bophelo bo botle ba sechaba — ho feteletsa ho kotsi bokhachaneng.",
      "Materia ha e iqape tekanyo ea IU kapa kemiso ea sehlopha sa lilemo — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka bokhachane kapa merero ea ho ima, lefu la sebete, le LIHLAHISOA TSOHLE tse ling tse nang le vitamin A pele u nka tse ling.",
      "U se ke ua kopanya lihlahisoa tse ngata tsa vitamin A tsa tekanyo e phahameng ntle le haeba ngaka e hlahlobile ho pepeseha ho felletseng.",
      "Botsoa hore na tekanyo ena ke ea tšehetso ea measles-pathway, kalafo ea khaello, kapa tlatsetso e tloaelehileng sebakeng sa hau.",
      "Haeba hlooho e bohloko haholo, ho hlatsa, letlalo le hlobotsoeng, kapa liphetoho tsa pono li hlaha ka mor'a tšebeliso ea tekanyo e phahameng — batla thuso ka potlako.",
    ],
    [
      "I-retinol (ivitamini A) isetyenziswa kwiindlela ezikhethiweyo zokunqongophala kunye nongezelelo lwempilo yoluntu — ukugqithisa kuyingozi ekukhulelweni.",
      "I-Materia ayiyiqiqi idosi ye-IU okanye ishedyuli yeqela leminyaka — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngokukhulelwa okanye izicwangciso zokukhulelwa, isifo sesibindi, kunye NAZO ZONKE ezinye iimveliso ezine-vitamin A ngaphambi kokuthatha okungakumbi.",
      "Ungadibanisi iimveliso ezininzi ze-vitamin A zedosi ephezulu ngaphandle kokuba ugqirha uye wahlola ukutyhileka okupheleleyo.",
      "Buza ukuba le dosi yeyenkxaso ye-measles-pathway, unyango lokunqongophala, okanye ungezelelo oluqhelekileyo kwindawo yakho.",
      "Ukuba intloko ebuhlungu kakhulu, ukugabha, ulusu oluhlubayo, okanye utshintsho lokubona kuvela emva kokusebenzisa idosi ephezulu — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-sennosides": five(
    [
      "Sennosides are stimulant laxatives used in selected constipation pathways — short courses are usual unless a clinician directs otherwise.",
      "Materia does not invent a dose or overnight timing rule — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about bowel obstruction symptoms, pregnancy, inflammatory bowel disease, and ALL other medicines before use.",
      "Drink enough fluid unless restricted for another medical reason — ask what fluid advice applies to you.",
      "Ask about fibre, toilet timing, and when to return if there is no bowel movement or pain worsens.",
      "If severe tummy pain, vomiting, blood in stool, or dizziness develops — seek care urgently.",
    ],
    [
      "Ama-sennosides ama-laxative ashukumisayo asetshenziswa ezindleleni ezikhethiwe zokuqina kwamathumbu — izinkambo ezimfushane zijwayelekile ngaphandle kokuthi udokotela asho okunye.",
      "I-Materia ayiqambi umthamo noma umthetho wesikhathi sobusuku — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngezimpawu zokuvinjwa kwamathumbu, ukukhulelwa, isifo samathumbu esivuvukayo, nawo WONKE amanye amaphilisi ngaphambi kokusebenzisa.",
      "Phuza uketshezi olwanele ngaphandle kokuthi kunqandelwe ngesinye isizathu sezokwelapha — buza iseluleko soketshezi esisebenza kuwe.",
      "Buza nge-fibre, isikhathi sendlu yangasese, nokuthi ubuyela nini uma kungabi nokuya ngasese noma ubuhlungu baba kubi.",
      "Uma ubuhlungu besisu obukhulu, ukuhlanza, igazi endleni, noma isiyezi kuvela — funa usizo ngokushesha.",
    ],
    [
      "Sennosiede is stimulerende lakseermiddels in geselekteerde hardlywigheidspaaie — kort kursusse is gewoonlik tensy 'n klinikus anders aandui.",
      "Materia versin nie 'n dosis of oornag tydreël nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van dermobstruksie simptome, swangerskap, inflammatoriese dermsiekte, en ALLE ander medisyne voor gebruik.",
      "Drink genoeg vloeistof tensy beperk vir 'n ander mediese rede — vra watter vloeistofadvies op jou van toepassing is.",
      "Vra oor vesel, toilet-tydsberaming, en wanneer om terug te kom as daar geen stoelgang is of pyn versleg.",
      "As ernstige maagpyn, braking, bloed in stoelgang, of duiseligheid ontwikkel — soek dringend sorg.",
    ],
    [
      "Li-sennosides ke li-laxative tse susumetsang tse sebelisoang litseleng tse khethiloeng tsa ho thatafala ha mala — lithuto tse khutšoanyane li tloaelehile ntle le haeba ngaka e laela ho hong.",
      "Materia ha e iqape tekanyo kapa molao oa nako ea bosiu — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka matšoao a thibelo ea mala, bokhachane, lefu la mala le ruruhang, le MERIANA EOHLE e meng pele u sebelisa.",
      "Noa mokelikeli o lekaneng ntle le haeba o thibetsoe ka lebaka le leng la bongaka — botsa keletso ea mokelikeli e sebetsang ho uena.",
      "Botsoa ka fiber, nako ea ntloana, le hore na u khutle neng haeba ho se tšebetso ea mala kapa bohloko bo mpefala.",
      "Haeba bohloko bo boholo ba mpa, ho hlatsa, mali bolusaneng, kapa ho tsekela ho hlaha — batla thuso ka potlako.",
    ],
    [
      "Ii-sennosides zii-laxative ezishukumisayo ezisetyenziswa kwiindlela ezikhethiweyo zokuqina kwamathumbu — iikhosi ezimfutshane ziqhelekile ngaphandle kokuba ugqirha athethe okunye.",
      "I-Materia ayiyiqiqi idosi okanye umthetho wexesha lasebusuku — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngeempawu zokuthintelwa kwamathumbu, ukukhulelwa, isifo samathumbu esidumbayo, kunye NAWO ONKE amanye amayeza ngaphambi kokusebenzisa.",
      "Sela ulwelo olwaneleyo ngaphandle kokuba kunqandelwe ngesinye isizathu sezonyango — buza icebiso lolwelo olusebenza kuwe.",
      "Buza nge-fibre, ixesha lendlu yangasese, nokuba ubuyela nini ukuba akukho mnyango wamathumbu okanye intlungu iba mbi.",
      "Ukuba intlungu enkulu yesisu, ukugabha, igazi emgqhameni, okanye isiyezi kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-orphenadrine": five(
    [
      "Orphenadrine is an anticholinergic used in selected extrapyramidal and muscle-spasm contexts — sedation and dry mouth are common teaching points.",
      "Materia does not invent a dose — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about glaucoma, prostate problems, heart disease, epilepsy, and ALL other medicines before starting.",
      "Avoid alcohol and other sedatives unless a clinician has reviewed the combination — driving caution applies.",
      "Ask how long this adjunct is intended and what movement symptoms should trigger an earlier review.",
      "If confusion, inability to pass urine, severe constipation, or fast heartbeat develops — seek care urgently.",
    ],
    [
      "I-orphenadrine i-anticholinergic esetshenziswa ezimeni ezikhethiwe ze-extrapyramidal nezokubamba kwemisipha — ukulalisa nomlomo owomile yizinto ezivamile zokufundisa.",
      "I-Materia ayiqambi umthamo — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela nge-glaucoma, izinkinga ze-prostate, isifo senhliziyo, i-epilepsy, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Gwema utshwala namanye ama-sedative ngaphandle kokuthi udokotela ubuyekeze inhlanganisela — ukuqapha ukushayela kuyasebenza.",
      "Buza ukuthi lesi sithasiselo sicatshangelwe isikhathi esingakanani nokuthi yiziphi izimpawu zokunyakaza ezifanele ziqale ukubuyekezwa kusenesikhathi.",
      "Uma ukudideka, ukungakwazi ukuchama, ukuqina kwamathumbu okukhulu, noma ukushaya kwenhliziyo okusheshayo kuvela — funa usizo ngokushesha.",
    ],
    [
      "Orfenadien is 'n anticholinergiese middel in geselekteerde ekstrapiramidale en spierspasma kontekste — sedasie en droë mond is algemene onderrigpunte.",
      "Materia versin nie 'n dosis nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van gloukoom, prostaatprobleme, hartsiektes, epilepsie, en ALLE ander medisyne voor jy begin.",
      "Vermy alkohol en ander sedatiewe middels tensy 'n klinikus die kombinasie nagegaan het — bestuursversigtigheid geld.",
      "Vra hoe lank hierdie adjunk bedoel is en watter bewegingsimptome 'n vroeër hersiening moet sneller.",
      "As verwarring, onvermoë om te urineer, ernstige hardlywigheid, of vinnige hartklop ontwikkel — soek dringend sorg.",
    ],
    [
      "Orphenadrine ke anticholinergic e sebelisoang maemong a khethiloeng a extrapyramidal le a ho hlaba ha mesifa — ho otlolla le molomo o omileng ke lintlha tse tloaelehileng tsa thuto.",
      "Materia ha e iqape tekanyo — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka glaucoma, mathata a prostate, lefu la pelo, epilepsy, le MERIANA EOHLE e meng pele u qala.",
      "Qoba joala le li-sedative tse ling ntle le haeba ngaka e hlahlobile motsoako — tlhokomelo ea ho khanna ea sebetsa.",
      "Botsoa hore na tlatsetso ena e reretsoe nako e kae le hore na ke matšoao afe a motsamao a lokelang ho qala tlhahlobo pele.",
      "Haeba ho ferekana, ho sitoa ho ntša moroto, ho thatafala ha mala ho matla, kapa ho otla ha pelo ho potlakileng ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-orphenadrine yi-anticholinergic esetyenziswa kwiimeko ezikhethiweyo ze-extrapyramidal kunye nokubamba kwemisipha — ukulalisa nomlomo owomileyo zizinto eziqhelekileyo zokufundisa.",
      "I-Materia ayiyiqiqi idosi — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha nge-glaucoma, iingxaki ze-prostate, isifo sentliziyo, i-epilepsy, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Phepha utywala kunye nezinye ii-sedative ngaphandle kokuba ugqirha uye wahlola indibaniselwano — ukulumkela ukuqhuba kuyasebenza.",
      "Buza ukuba esi songezelelo sicingelwe ixesha elingakanani nokuba zeziphi iimpawu zokushukuma ekufuneka ziqalise ukujongwa kwangethuba.",
      "Ukuba ukudideka, ukungakwazi ukuchama, ukuqina kwamathumbu okukhulu, okanye ukubetha kwentliziyo okukhawulezayo kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-biperiden": five(
    [
      "Biperiden is an anticholinergic used in selected drug-induced extrapyramidal pathways — acute dystonia needs urgent clinical care.",
      "Materia does not invent a dose or dystonia protocol — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about glaucoma, prostate problems, myasthenia, and ALL other medicines before starting.",
      "Sedation and blurred vision can occur — take care with driving until you know how you respond.",
      "Ask whether this is for short-term dystonia rescue or longer adjunct use with your antipsychotic plan.",
      "If inability to move the neck or eyes, confusion, or inability to pass urine develops — seek care urgently.",
    ],
    [
      "I-biperiden i-anticholinergic esetshenziswa ezindleleni ezikhethiwe ze-extrapyramidal ezibangelwa imithi — i-dystonia ebucayi idinga ukunakekelwa okuphuthumayo.",
      "I-Materia ayiqambi umthamo noma umgomo we-dystonia — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela nge-glaucoma, izinkinga ze-prostate, i-myasthenia, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Ukulalisa nokubona okufiphele kungenzeka — qaphela ukushayela uze wazi ukuthi uphendula kanjani.",
      "Buza ukuthi lokhu kungokusiza i-dystonia yesikhashana noma ukusebenzisa isithasiselo isikhathi eside nohlelo lwakho lwe-antipsychotic.",
      "Uma ukungakwazi ukunyakazisa intamo noma amehlo, ukudideka, noma ukungakwazi ukuchama kuvela — funa usizo ngokushesha.",
    ],
    [
      "Biperiden is 'n anticholinergiese middel in geselekteerde middel-geïnduseerde ekstrapiramidale paaie — akute distonie benodig dringende kliniese sorg.",
      "Materia versin nie 'n dosis of distonieprotokol nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van gloukoom, prostaatprobleme, miastenie, en ALLE ander medisyne voor jy begin.",
      "Sedasie en dowwe sig kan voorkom — wees versigtig met bestuur totdat jy weet hoe jy reageer.",
      "Vra of dit vir korttermyn distonie-redding of langer adjunkgebruik met jou antipsigotiese plan is.",
      "As onvermoë om die nek of oë te beweeg, verwarring, of onvermoë om te urineer ontwikkel — soek dringend sorg.",
    ],
    [
      "Biperiden ke anticholinergic e sebelisoang litseleng tse khethiloeng tsa extrapyramidal tse bakoang ke meriana — dystonia e bohale e hloka tlhokomelo ea potlako.",
      "Materia ha e iqape tekanyo kapa protokole ea dystonia — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka glaucoma, mathata a prostate, myasthenia, le MERIANA EOHLE e meng pele u qala.",
      "Ho otlolla le pono e fifaleng li ka hlaha — hlokomela ho khanna ho fihlela u tseba hore na u arabela joang.",
      "Botsoa hore na sena ke sa pholoso ea dystonia ea nako e khuts'oane kapa tšebeliso ea tlatsetso e telele le moralo oa hau oa antipsychotic.",
      "Haeba ho sitoa ho sisinya molala kapa mahlo, ho ferekana, kapa ho sitoa ho ntša moroto ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-biperiden yi-anticholinergic esetyenziswa kwiindlela ezikhethiweyo ze-extrapyramidal ezibangelwa ngamayeza — i-dystonia ebucala ifuna ukhathalelo olungxamisekileyo.",
      "I-Materia ayiyiqiqi idosi okanye umgaqo we-dystonia — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha nge-glaucoma, iingxaki ze-prostate, i-myasthenia, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Ukulalisa nokubona okufiphele kungenzeka — lumkela ukuqhuba de wazi ukuba uphendula njani.",
      "Buza ukuba oku kukunceda i-dystonia yexeshana okanye ukusebenzisa isongezelelo ixesha elide kunye nesicwangciso sakho se-antipsychotic.",
      "Ukuba ukungakwazi ukushukuma intamo okanye amehlo, ukudideka, okanye ukungakwazi ukuchama kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-zuclopenthixol": five(
    [
      "Zuclopenthixol is a typical antipsychotic available in oral and depot forms — formulation choice is clinician-led.",
      "Materia does not invent a dose or depot interval — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about heart disease, movement disorders, pregnancy plans, and ALL other medicines before starting.",
      "Sedation, stiffness, and restlessness can occur — report early so the team can adjust the plan safely.",
      "Ask whether this is oral daily treatment or a depot injection pathway and when the next review is due.",
      "If high fever with stiffness, fainting, severe restlessness, or suicidal thoughts develop — seek emergency care immediately.",
    ],
    [
      "I-zuclopenthixol i-antipsychotic ejwayelekile etholakala ngomlomo nange-depot — ukukhetha uhlobo kuqhutshwa udokotela.",
      "I-Materia ayiqambi umthamo noma isikhathi se-depot — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesifo senhliziyo, izinkinga zokunyakaza, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Ukulalisa, ukuqina, nokungaphumuli kungenzeka — bika kusenesikhathi ukuze ithimba lilungise uhlelo ngokuphephile.",
      "Buza ukuthi lokhu kungukwelashwa kwansuku zonke ngomlomo noma indlela yomjovo we-depot nokuthi ukubuyekezwa okulandelayo kufanele nini.",
      "Uma umkhuhlane ophezulu nokuqina, ukuquleka, ukungaphumuli okukhulu, noma imicabango yokuzibulala kuvela — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Suklopentiksol is 'n tipiese antipsigotikum beskikbaar in orale en depot vorms — formuleringskeuse is klinikus-gelei.",
      "Materia versin nie 'n dosis of depot-interval nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van hartsiektes, bewegingsversteurings, swangerskapplanne, en ALLE ander medisyne voor jy begin.",
      "Sedasie, styfheid, en rusteloosheid kan voorkom — rapporteer vroeg sodat die span die plan veilig kan aanpas.",
      "Vra of dit daaglikse orale behandeling of 'n depot-inspuiting pad is en wanneer die volgende hersiening verskuldig is.",
      "As hoë koors met styfheid, floute, ernstige rusteloosheid, of selfmoordgedagtes ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Zuclopenthixol ke antipsychotic e tloaelehileng e fumanehang ka molomo le mefuta ea depot — khetho ea sebopeho e etelloa pele ke ngaka.",
      "Materia ha e iqape tekanyo kapa nako ea depot — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka lefu la pelo, mathata a motsamao, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "Ho otlolla, ho thatafala, le ho hloka phomolo ho ka hlaha — tlaleha kapele hore sehlopha se lokise moralo ka polokeho.",
      "Botsoa hore na sena ke kalafo ea letsatsi le letsatsi ea molomo kapa tsela ea ente ea depot le hore na tlhahlobo e latelang e lokela neng.",
      "Haeba feberu e phahameng le ho thatafala, ho akheha, ho hloka phomolo ho matla, kapa mehopolo ea ho ipolaea e hlaha — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-zuclopenthixol yi-antipsychotic eqhelekileyo efumaneka ngomlomo nangeendlela ze-depot — ukukhetha uhlobo kukhokelwa ngugqirha.",
      "I-Materia ayiyiqiqi idosi okanye ixesha le-depot — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngesifo sentliziyo, iingxaki zokushukuma, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Ukulalisa, ukuqina, nokungaphumli kungenzeka — xela kwangethuba ukuze iqela lilungise isicwangciso ngokukhuselekileyo.",
      "Buza ukuba oku kunyango lwemihla ngemihla lomlomo okanye indlela yenaliti ye-depot nokuba ukujonga okulandelayo kufanele nini.",
      "Ukuba umkhuhlane ophezulu nokuqina, ukuquleka, ukungaphumli okukhulu, okanye iingcinga zokuzibulala zivela — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-selenium-sulfide": five(
    [
      "Selenium sulfide is a topical antiseborrheic used for selected scalp and tinea versicolor pathways — follow wash-off timing on the label.",
      "Materia does not invent a concentration or contact time — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about broken skin, pregnancy, and any prior irritation to selenium products before use.",
      "Keep out of eyes and mouth — rinse thoroughly if accidental contact occurs.",
      "Ask how often to apply for your condition and when to review if flaking or itch persists.",
      "If severe burning, swelling, or widespread rash develops — stop and seek care urgently.",
    ],
    [
      "I-selenium sulfide i-antiseborrheic yesikhumba esetshenziswa ezindleleni ezikhethiwe zekhanda ne-tinea versicolor — landela isikhathi sokugeza esulebula.",
      "I-Materia ayiqambi ukugxilisa noma isikhathi sokuthintana — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesikhumba esaphukile, ukukhulelwa, nanoma yikuphi ukucasuka kwangaphambilini kwemikhiqizo ye-selenium ngaphambi kokusebenzisa.",
      "Gcina kude namehlo nomlomo — geza kahle uma uthintana ngephutha.",
      "Buza ukuthi kufanele usebenzise kangaki ngesimo sakho nokuthi ubuyekezwa nini uma ukuhluba noma ukuluma kuqhubeka.",
      "Uma ukushisa okukhulu, ukuvuvuka, noma ukuqubuka okusabalele kuvela — yeka futhi funa usizo ngokushesha.",
    ],
    [
      "Seleniumsulfied is 'n topiese antiseborreïese middel vir geselekteerde kopvel- en tinea versicolor paaie — volg afspoeltyd op die etiket.",
      "Materia versin nie 'n konsentrasie of kontakttyd nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van gebroke vel, swangerskap, en enige vorige irritasie vir seleniumprodukte voor gebruik.",
      "Hou uit oë en mond — spoel deeglik as toevallige kontak voorkom.",
      "Vra hoe gereeld om vir jou toestand aan te wend en wanneer om te hersien as skilfers of jeuk aanhou.",
      "As ernstige brand, swelling, of wydverspreide uitslag ontwikkel — stop en soek dringend sorg.",
    ],
    [
      "Selenium sulfide ke antiseborrheic ea letlalo e sebelisoang litseleng tse khethiloeng tsa hlooho le tinea versicolor — latela nako ea ho hlatsoa e holim'a ileibole.",
      "Materia ha e iqape concentration kapa nako ea ho kopana — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka letlalo le robehileng, bokhachane, le ho teka hafe kapa hafe ha pejana ha lihlahisoa tsa selenium pele u sebelisa.",
      "Boloka hole le mahlo le molomo — hlatsoa hantle haeba ho kopana ka phoso ho etsahala.",
      "Botsoa hore na u lokela ho sebelisa hangata hakae bakeng sa boemo ba hau le hore na u hlahlobe neng haeba ho hlobola kapa ho hlohlona ho tsoela pele.",
      "Haeba ho chesa ho matla, ho ruruha, kapa lekhopho le hasaneng le hlaha — emisa 'me u batle thuso ka potlako.",
    ],
    [
      "I-selenium sulfide yi-antiseborrheic yolusu esetyenziswa kwiindlela ezikhethiweyo zentloko kunye ne-tinea versicolor — landela ixesha lokuhlambela kwilebhile.",
      "I-Materia ayiyiqiqi ukugxininisa okanye ixesha lokuthintana — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngolusu olwaphukileyo, ukukhulelwa, kunye nayiphi na ukucaphuka kwangaphambili kwiimveliso ze-selenium ngaphambi kokusebenzisa.",
      "Gcina kude namehlo nomlomo — hlamba kakuhle ukuba uthintana ngempazamo.",
      "Buza ukuba kufuneka usebenzise rhoqo kangakanani kwimeko yakho nokuba ujonga nini ukuba ukuhluba okanye ukurhawuzelela kuyaqhubeka.",
      "Ukuba ukutshisa okukhulu, ukudumba, okanye irhashalala esasazekileyo kuvela — yeka kwaye funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-benzyl-benzoate": five(
    [
      "Benzyl benzoate is a topical scabicide used in selected scabies pathways — whole-household treatment is often discussed clinically.",
      "Materia does not invent a dilution or application schedule — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about broken skin, pregnancy, breastfeeding, and prior irritation before use.",
      "Keep away from eyes and mucous membranes — rinse if accidental contact occurs.",
      "Ask whether contacts need treatment and how to wash bedding and clothing for your pathway.",
      "If severe burning, swelling, or breathing difficulty develops — stop and seek care urgently.",
    ],
    [
      "I-benzyl benzoate i-scabicide yesikhumba esetshenziswa ezindleleni ezikhethiwe ze-scabies — ukwelashwa komndeni wonke kuvame ukuxoxwa ngokwezokwelapha.",
      "I-Materia ayiqambi ukuhlanseka noma uhlelo lokufaka — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesikhumba esaphukile, ukukhulelwa, ukuncelisa, nokucasuka kwangaphambilini ngaphambi kokusebenzisa.",
      "Gcina kude namehlo nezindawo ezimucosal — geza uma uthintana ngephutha.",
      "Buza ukuthi abaseduze badinga yini ukwelashwa nokuthi kugezwa kanjani izingubo zokulala nezingubo zendlela yakho.",
      "Uma ukushisa okukhulu, ukuvuvuka, noma ubunzima bokuphefumula kuvela — yeka futhi funa usizo ngokushesha.",
    ],
    [
      "Bensielbensoaat is 'n topiese skabicide in geselekteerde skurftepaaie — hele-huishouding behandeling word dikwels klinies bespreek.",
      "Materia versin nie 'n verdunning of aanwendingsskudule nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van gebroke vel, swangerskap, borsvoeding, en vorige irritasie voor gebruik.",
      "Hou weg van oë en slymvliese — spoel as toevallige kontak voorkom.",
      "Vra of kontakte behandeling nodig het en hoe om beddegoed en klere vir jou pad te was.",
      "As ernstige brand, swelling, of asemnood ontwikkel — stop en soek dringend sorg.",
    ],
    [
      "Benzyl benzoate ke scabicide ea letlalo e sebelisoang litseleng tse khethiloeng tsa scabies — kalafo ea lelapa lohle hangata e buisanoa ka bongaka.",
      "Materia ha e iqape dilution kapa kemiso ea ho kenya — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka letlalo le robehileng, bokhachane, ho anyesa, le ho teka ha pejana pele u sebelisa.",
      "Boloka hole le mahlo le limembrane tsa mucus — hlatsoa haeba ho kopana ka phoso ho etsahala.",
      "Botsoa hore na ba haufi ba hloka kalafo le hore na u hlatsoa joang liraba le liaparo bakeng sa tsela ea hau.",
      "Haeba ho chesa ho matla, ho ruruha, kapa ho hema thata ho hlaha — emisa 'me u batle thuso ka potlako.",
    ],
    [
      "I-benzyl benzoate yi-scabicide yolusu esetyenziswa kwiindlela ezikhethiweyo ze-scabies — unyango lwendlu yonke rhoqo luxoxwa ngokwezonyango.",
      "I-Materia ayiyiqiqi ukuhlanjululwa okanye ishedyuli yokufaka — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngolusu olwaphukileyo, ukukhulelwa, ukuncancisa, kunye nokucaphuka kwangaphambili ngaphambi kokusebenzisa.",
      "Gcina kude namehlo kunye ne-mucous membranes — hlamba ukuba uthintana ngempazamo.",
      "Buza ukuba abasondelayo bafuna unyango na nokuba kuhlamba njani iingubo zokulala neengubo zendlela yakho.",
      "Ukuba ukutshisa okukhulu, ukudumba, okanye ubunzima bokuphefumla kuvela — yeka kwaye funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-povidone-iodine": five(
    [
      "Povidone-iodine is an iodophor antiseptic used for selected wound and mucosal antisepsis — strength and site matter.",
      "Materia does not invent a concentration or soak duration — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about iodine allergy, thyroid disease, pregnancy, and large open wounds before use.",
      "Avoid swallowing and keep out of eyes unless the product is specifically labelled for that site.",
      "Ask how to clean and dress the wound after antisepsis and when to return if redness spreads.",
      "If swelling, wheeze, or severe rash develops after use — seek emergency care immediately.",
    ],
    [
      "I-povidone-iodine i-iodophor antiseptic esetshenziswa ekulweni kwezifo ezikhethiwe zezilonda nezimucosal — amandla nendawo kubalulekile.",
      "I-Materia ayiqambi ukugxilisa noma isikhathi sokucwilisa — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela nge-allergy ye-iodine, isifo se-thyroid, ukukhulelwa, nezilonda ezivulekile ezinkulu ngaphambi kokusebenzisa.",
      "Gwema ukugwinya futhi gcina kude namehlo ngaphandle kokuthi umkhiqizo unolebula ngqo yaleyo ndawo.",
      "Buza ukuthi kuhlanzwa futhi kufakwa kanjani isilonda ngemva kwe-antisepsis nokuthi ubuyela nini uma ukubomvu kusabalala.",
      "Uma ukuvuvuka, ukuhema kanzima, noma ukuqubuka okukhulu kuvela ngemva kokusebenzisa — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Povidoon-jodium is 'n jodofoor antiseptikum vir geselekteerde wond- en mukosale antiseptika — sterkte en plek maak saak.",
      "Materia versin nie 'n konsentrasie of weekduur nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van jodiumallergie, skildkliersiekte, swangerskap, en groot oop wonde voor gebruik.",
      "Vermy insluk en hou uit oë tensy die produk spesifiek vir daardie plek geëtiketteer is.",
      "Vra hoe om die wond na antiseptika te reinig en verbind en wanneer om terug te kom as rooiheid versprei.",
      "As swelling, piepende asem, of ernstige uitslag na gebruik ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Povidone-iodine ke iodophor antiseptic e sebelisoang bakeng sa antiseptika e khethiloeng ea maqeba le mucosal — matla le sebaka lia bohlokoa.",
      "Materia ha e iqape concentration kapa nako ea ho qoelisa — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka allergy ea iodine, lefu la thyroid, bokhachane, le maqeba a maholo a bulehileng pele u sebelisa.",
      "Qoba ho koenya 'me u boloke hole le mahlo ntle le haeba sehlahisoa se nang le ileibole e tobileng bakeng sa sebaka seo.",
      "Botsoa hore na u hlatsoa le ho tlama leqeba joang ka mor'a antiseptika le hore na u khutle neng haeba bofubelu bo hasana.",
      "Haeba ho ruruha, ho hema ka thata, kapa lekhopho le matla le hlaha ka mor'a tšebeliso — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-povidone-iodine yi-iodophor antiseptic esetyenziswa kwi-antisepsis ekhethiweyo yezilonda kunye ne-mucosal — amandla nendawo kubalulekile.",
      "I-Materia ayiyiqiqi ukugxininisa okanye ixesha lokucwilisa — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha nge-allergy ye-iodine, isifo se-thyroid, ukukhulelwa, kunye nezilonda ezivulekileyo ezinkulu ngaphambi kokusebenzisa.",
      "Phepha ukuginya kwaye ugcine kude namehlo ngaphandle kokuba imveliso inelebula ngokukodwa yaloo ndawo.",
      "Buza ukuba kuhlamba kwaye kufakwa njani isilonda emva kwe-antisepsis nokuba ubuyela nini ukuba ubomvu busasazeka.",
      "Ukuba ukudumba, ukuphefumla nzima, okanye irhashalala enzima kuvela emva kokusebenzisa — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-nicotinamide": five(
    [
      "Nicotinamide is the amide form of vitamin B3 used in selected deficiency and dermatology contexts — it is distinct from nicotinic acid flushing.",
      "Materia does not invent a dose — confirm against current SA PHC STG/EML and the labelled product.",
      "Tell the clinician about liver disease, peptic ulcer history, pregnancy plans, and ALL other medicines before starting.",
      "Ask whether this is for nutritional deficiency, skin pathway support, or another labelled indication in your care plan.",
      "Take as directed with food if the labelled product advises — do not invent a meal rule.",
      "If severe rash, yellow eyes, or unexplained vomiting develops — seek care urgently.",
    ],
    [
      "I-nicotinamide iwuhlobo lwe-amide lwe-vitamin B3 olusetshenziswa ezimeni ezikhethiwe zokuntuleka nasesikhumbeni — luhlukile ekushiseni kwe-nicotinic acid.",
      "I-Materia ayiqambi umthamo — qinisekisa ne-STG/EML ye-PHC yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngesifo sesibindi, umlando wesilonda sesisu, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi ngaphambi kokuqala.",
      "Buza ukuthi lokhu kungokuntuleka kwezakhamzimba, ukweseka indlela yesikhumba, noma esinye isizathu esinolebula ohlelweni lwakho.",
      "Thatha njengoba kushiwo nokudla uma umkhiqizo onelebula ucebisa — ungacabangi umthetho wokudla.",
      "Uma ukuqubuka okukhulu, amehlo aphuzi, noma ukuhlanza okungachazeki kuvela — funa usizo ngokushesha.",
    ],
    [
      "Nikotinamied is die amiedvorm van vitamien B3 in geselekteerde tekort- en dermatologie kontekste — dit verskil van nikotiensuur-bloos.",
      "Materia versin nie 'n dosis nie — bevestig teen huidige SA PHC STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van lewersiekte, peptic ulkusgeskiedenis, swangerskapplanne, en ALLE ander medisyne voor jy begin.",
      "Vra of dit vir voedingstekort, velpad ondersteuning, of 'n ander geëtiketteerde aanduiding in jou sorgplan is.",
      "Neem soos aangedui met kos as die geëtiketteerde produk dit aanbeveel — moenie 'n maaltydreël versin nie.",
      "As ernstige uitslag, geel oë, of onverklaarde braking ontwikkel — soek dringend sorg.",
    ],
    [
      "Nicotinamide ke mofuta oa amide oa vitamin B3 o sebelisoang maemong a khethiloeng a khaello le dermatology — o fapane le ho fifala ha nicotinic acid.",
      "Materia ha e iqape tekanyo — netefatsa khahlanong le STG/EML ea PHC ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka lefu la sebete, nalane ea lisoa la mala, merero ea bokhachane, le MERIANA EOHLE e meng pele u qala.",
      "Botsoa hore na sena ke sa khaello ea phepo, tšehetso ea tsela ea letlalo, kapa sesosa se seng se nang le ileibole moralo oa hau oa tlhokomelo.",
      "E nke joalo ka ha u laetsoe le lijo haeba sehlahisoa se nang le ileibole se eletsa — u se ke ua iqapa molao oa lijo.",
      "Haeba lekhopho le matla, mahlo a mosehla, kapa ho hlatsa ho sa hlaloseng ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-nicotinamide luhlobo lwe-amide lwe-vitamin B3 olusetyenziswa kwiimeko ezikhethiweyo zokunqongophala kunye ne-dermatology — yahlukile kukubomvu kwe-nicotinic acid.",
      "I-Materia ayiyiqiqi idosi — Qinisekisa ne-STG/EML ye-PHC yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngesifo sesibindi, imbali yesilonda sesisu, izicwangciso zokukhulelwa, kunye NAWO ONKE amanye amayeza ngaphambi kokuqala.",
      "Buza ukuba oku kukunqongophala kwezakhamzimba, inkxaso yendlela yolusu, okanye esinye isizathu esinelebula kwisicwangciso sakho sokhathalelo.",
      "Thatha njengoko uyalelelwe nokutya ukuba imveliso enelebula icebisa — ungacingi umthetho wokutya.",
      "Ukuba irhashalala enzima, amehlo atyheli, okanye ukugabha okungachazekiyo kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),
};
