/**
 * v330–v344 deepened SA counselling batch (6 lines × 5 langs) — STG/EML Batch C hospital-chronic gaps.
 * Respiratory, diabetes, cardio, ART, psych, neuro, supportive, obstetric. Original Materia only —
 * no invented doses, puff counts, lab schedules, infusion rates, or regimens.
 * Types kept local to avoid circular import with counselling.ts.
 */

export type ExtLang = "en" | "zu" | "af" | "st" | "xh";

export interface ExtScript {
  lang: ExtLang;
  lines: string[];
  sourceNote: string;
  publishState: "published" | "draft";
}

const EN_NOTE = "Materia original counselling — founder-reviewed educational layer";
const ZU_NOTE = "Materia original isiZulu counselling — founder-reviewed educational layer";
const AF_NOTE = "Materia original Afrikaans counselling — founder-reviewed educational layer";
const ST_NOTE = "Materia original Sesotho counselling — founder-reviewed educational layer";
const XH_NOTE = "Materia original isiXhosa counselling — founder-reviewed educational layer";

function five(
  en: string[],
  zu: string[],
  af: string[],
  st: string[],
  xh: string[],
): Partial<Record<ExtLang, ExtScript>> {
  return {
    en: { lang: "en", publishState: "published", sourceNote: EN_NOTE, lines: en },
    zu: { lang: "zu", publishState: "published", sourceNote: ZU_NOTE, lines: zu },
    af: { lang: "af", publishState: "published", sourceNote: AF_NOTE, lines: af },
    st: { lang: "st", publishState: "published", sourceNote: ST_NOTE, lines: st },
    xh: { lang: "xh", publishState: "published", sourceNote: XH_NOTE, lines: xh },
  };
}

export const COUNSELLING_V330_TO_V344: Record<string, Partial<Record<ExtLang, ExtScript>>> = {
  "mol-beclomethasone": five(
    [
      "Beclomethasone is an inhaled corticosteroid (ICS) controller for asthma/COPD pathways — it is not a quick-relief (reliever) inhaler.",
      "Materia does not invent puff counts or spacer schedules — use exactly as the labelled product and your clinician direct.",
      "Rinse your mouth after inhaled steroid use if advised on your pack — thrush and hoarseness are common counselling points.",
      "Tell your pharmacist about oral steroids, recent infections, and ALL other inhalers you use.",
      "Ask for inhaler/spacer technique check — poor technique is a common reason controllers seem to fail.",
      "If breathing worsens suddenly, lips turn blue, or you need your reliever far more often — seek urgent care; do not rely on the controller alone.",
    ],
    [
      "I-beclomethasone i-inhaled corticosteroid (ICS) yokulawula i-asthma/COPD — akuyona i-inhaler yokululama ngokushesha.",
      "I-Materia ayiqambi inani lamaphimbo noma uhlelo lwe-spacer — sebenzisa ngokwemikhiqizo eneebula nomyalelo kadokotela.",
      "Geza umlomo ngemva kwe-steroid yokuphefumula uma uyalelwa kuphakethe — i-thrush nezwi elirhabayo zizinto ezivamile zokweluleka.",
      "Tshela usokhemisi ngama-steroid omlomo, izifo zakamuva, nawo WONKE amanye ama-inhaler owasebenzisayo.",
      "Cela ukuhlolwa kwendlela ye-inhaler/spacer — indlela embi iyimbangela evamile yokuthi izilawuli zibonakale zehluleka.",
      "Uma ukuphefumula kuba kubi ngokushesha, izindebe ziba luhlaza, noma udinga i-reliever kaningi kakhulu — funa usizo; unganciki kusilawuli sodwa.",
    ],
    [
      "Beclometasoon is 'n ingeasemde kortikosteroïed (ICS) beheerder vir asma/COPD — dit is nie 'n kitsverligter-inhaler nie.",
      "Materia versin nie puf-tellings of spacer-skedules nie — gebruik presies soos die geëtiketteerde produk en jou klinikus aandui.",
      "Spoel jou mond ná ingeasemde steroïedgebruik indien op jou pak aangeraai — swaminfeksie en heesheid is algemene beradingspunte.",
      "Sê vir jou apteker van mondelinge steroïede, onlangse infeksies, en ALLE ander inhalers wat jy gebruik.",
      "Vra 'n inhaler/spacer-tegniektoets — swak tegniek is 'n algemene rede waarom beheerder misluk lyk.",
      "As asemhaling skielik versleg, lippe blou word, of jy jou verligter baie meer nodig het — soek dringende sorg; moenie net op die beheerder staatmaak nie.",
    ],
    [
      "Beclomethasone ke corticosteroid e kenang ka moea (ICS) ea ho laola asthma/COPD — ha se inhaler ea ho imolla kapele.",
      "Materia ha e iqape palo ea puff kapa kemiso ea spacer — sebelisa hantle joalo ka sehlahisoa se nang le ileibole le tataiso ea ngaka.",
      "Hlatsa molomo ka mor'a steroid ea ho hema haeba u elelitsoe pakete — thrush le lentsoe le hoama ke lintlha tse tloaelehileng tsa keletso.",
      "Bolella chemist ka li-steroid tsa molomo, mafu a morao tjena, le LI-INHALER TSOHLE tseo u li sebelisang.",
      "Kopa tlhahlobo ea mokhoa oa inhaler/spacer — mokhoa o mobe ke lebaka le tloaelehileng la hore li-controller li bonahale li hloleha.",
      "Haeba ho hema ho mpefala ka tšohanyetso, melomo e fetoha boputsoa, kapa u hloka reliever hangata haholo — batla thuso; u se ke ua its'epa controller feela.",
    ],
    [
      "I-beclomethasone yi-inhaled corticosteroid (ICS) yokulawula i-asthma/COPD — ayisiyo i-inhaler yokukhulula ngokukhawuleza.",
      "I-Materia ayiyiqiqi inani leepuff okanye ishedyuli ye-spacer — sebenzisa ngokwenene njengemveliso enelebula kunye nomyalelo kagqirha.",
      "Hlamba umlomo emva kwesteroid yokuphefumla ukuba uyalelwa kwipakethe — i-thrush nelizwi elirhabaxa zizinto eziqhelekileyo zokucebisa.",
      "Xelela usokhemisi ngee-steroid zomlomo, izifo zakutsha nje, nazo ZONKE ezinye ii-inhaler ozisebenzisayo.",
      "Cela uvavanyo lwendlela ye-inhaler/spacer — indlela embi sisizathu esiqhelekileyo sokuba abalawuli babonakale besilela.",
      "Ukuba ukuphefumla kuya kuba kubi ngequbuliso, imilebe iba luhlaza, okanye ufuna i-reliever rhoqo kakhulu — funa uncedo; ungaxhomekeki kulawulo lodwa.",
    ],
  ),

  "mol-ipratropium": five(
    [
      "Ipratropium bromide is a short-acting muscarinic antagonist (SAMA) used in selected asthma/COPD pathways, including nebuliser contexts.",
      "Materia does not invent puff or nebuliser doses — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about glaucoma, prostate/urinary problems, and ALL other inhalers or nebuliser medicines.",
      "Avoid getting mist in the eyes with nebulisers if advised — eye pain or blurred vision needs prompt review.",
      "Ask when this is a reliever add-on versus a planned nebuliser regimen in your care plan.",
      "If breathing does not improve, chest tightness worsens, or you feel faint during nebulisation — seek urgent care.",
    ],
    [
      "I-ipratropium bromide i-SAMA esetshenziswa ezindleleni ezikhethiwe ze-asthma/COPD, kuhlanganise ne-nebuliser.",
      "I-Materia ayiqambi imithamo yephimbo noma ye-nebuliser — qinisekisa nomkhiqizo onelebula ne-STG/EML yaseNingizimu Afrika.",
      "Tshela usokhemisi nge-glaucoma, izinkinga ze-prostate/umchamo, nawo WONKE amanye ama-inhaler noma imithi ye-nebuliser.",
      "Gwema ukufaka inkungu emehlweni nama-nebuliser uma uyalelwa — ubuhlungu beso noma ukubona okufiphele kudinga ukuhlolwa ngokushesha.",
      "Buza ukuthi lokhu kuyisengezo se-reliever noma uhlelo lwe-nebuliser oluhleliwe ohlelweni lwakho.",
      "Uma ukuphefumula kungathuthuki, isifuba siqina, noma uzizwa uphelelwa amandla ngesikhathi se-nebuliser — funa usizo.",
    ],
    [
      "Ipratropiumbromied is 'n kortwerkende muskariniese antagonis (SAMA) in geselekteerde asma/COPD-paaie, insluitend verwieweraar-kontekste.",
      "Materia versin nie puf- of verwieweraar-dosisse nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van gloukoom, prostaat-/urieneprobleme, en ALLE ander inhalers of verwieweraar-medisyne.",
      "Vermy mis in die oë met verwieweraars indien aangeraai — oogpyn of dowwe sig benodig gou hersiening.",
      "Vra wanneer dit 'n verligter-byvoeging versus 'n beplande verwieweraar-regimen in jou sorgplan is.",
      "As asemhaling nie verbeter nie, borsdigtheid versleg, of jy flou voel tydens verwiewering — soek dringende sorg.",
    ],
    [
      "Ipratropium bromide ke SAMA e sebelisoang litseleng tse khethiloeng tsa asthma/COPD, ho kenyelletsa maemo a nebuliser.",
      "Materia ha e iqape litekanyo tsa puff kapa nebuliser — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML ea SA.",
      "Bolella chemist ka glaucoma, mathata a prostate/moroto, le LI-INHALER TSOHLE kapa meriana ea nebuliser.",
      "Qoba ho kenya moholi mahlong ka li-nebuliser haeba u elelitsoe — bohloko ba mahlo kapa pono e fifalitseng e hloka tlhahlobo kapele.",
      "Botsoa hore na sena ke tlatsetso ea reliever kapa moralo oa nebuliser o reriloeng moralong oa hau oa tlhokomelo.",
      "Haeba ho hema ho sa ntlafale, sefuba se thatafala, kapa u ikutloa u fokola nakong ea nebuliser — batla thuso.",
    ],
    [
      "I-ipratropium bromide yi-SAMA esetyenziswa kwiindlela ezikhethiweyo ze-asthma/COPD, kuquka iimeko ze-nebuliser.",
      "I-Materia ayiyiqiqi iidosi zeepuff okanye ze-nebuliser — Qinisekisa nemveliso enelebula kunye ne-STG/EML yaseMzantsi Afrika.",
      "Xelela usokhemisi nge-glaucoma, iingxaki ze-prostate/umchamo, nazo ZONKE ezinye ii-inhaler okanye amayeza e-nebuliser.",
      "Pepa ukufaka inkungu emehlweni ngee-nebuliser ukuba uyalelwa — intlungu yeso okanye ukubona okufiphele kufuna uphononongo ngokukhawuleza.",
      "Buza ukuba oku sisongezo se-reliever okanye inkqubo ye-nebuliser ecwangcisiweyo kwisicwangciso sakho sokhathalelo.",
      "Ukuba ukuphefumla akuphucuki, isifuba siyaqina, okanye uziva uphelelwa ngamandla ngexesha le-nebuliser — funa uncedo.",
    ],
  ),

  "mol-glibenclamide": five(
    [
      "Glibenclamide is a sulfonylurea tablet that can lower blood sugar — hypoglycaemia risk is a central counselling point.",
      "Materia does not invent a dose or renal cut-off — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about kidney disease, elderly age concerns, irregular meals, and ALL other diabetes medicines.",
      "Learn hypo warning signs (sweating, shakiness, confusion) and keep a clinician-advised rescue plan — Materia does not invent that plan.",
      "Ask what to do on sick days when you cannot eat, and whether alcohol increases your hypo risk.",
      "If you cannot wake someone with suspected low sugar, or seizures occur — call emergency services immediately.",
    ],
    [
      "I-glibenclamide i-sulfonylurea tablet enganciphisa ushukela — ingozi ye-hypoglycaemia iyiphuzu elibalulekile lokweluleka.",
      "I-Materia ayiqambi umthamo noma umkhawulo wezinso — qinisekisa nomkhiqizo onelebula ne-STG/EML yaseNingizimu Afrika.",
      "Tshela usokhemisi ngesifo sezinso, ukuguga, ukudla okungajwayelekile, nawo WONKE amanye amaphilisi esifo sikashukela.",
      "Funda izimpawu ze-hypo (ukujuluka, ukuthuthumela, ukudideka) futhi ugcine uhlelo lokusiza olutuswe udokotela — i-Materia ayiluqambi lolo hlelo.",
      "Buza ukuthi wenzani ngezinsuku zokugula uma ungakwazi ukudla, nokuthi utshwala lukhuphula yini ingozi ye-hypo.",
      "Uma ungakwazi ukuvusa umuntu ocabanga ukuthi unoshukela ophansi, noma kuvela ukuxega — shayela izinsiza eziphuthumayo.",
    ],
    [
      "Glibenklamied is 'n sulfonielureumtablet wat bloedsuiker kan verlaag — hipoglukemie-risiko is 'n sentrale beradingspunt.",
      "Materia versin nie 'n dosis of nierafsnyding nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van niersiekte, bejaardesorg, ongereelde maaltye, en ALLE ander diabetesmedisyne.",
      "Leer hipo-waarskuwingstekens (sweet, bewing, verwarring) en hou 'n klinikus-aangerade reddingsplan — Materia versin nie daardie plan nie.",
      "Vra wat om te doen op siekdae wanneer jy nie kan eet nie, en of alkohol jou hipo-risiko verhoog.",
      "As jy iemand met vermoedelike lae suiker nie kan wakker maak nie, of aanvalle voorkom — bel nooddienste onmiddellik.",
    ],
    [
      "Glibenclamide ke tablete ea sulfonylurea e ka theola tsoekere ea mali — kotsi ea hypoglycaemia ke ntlha ea bohlokoa ea keletso.",
      "Materia ha e iqape tekanyo kapa cut-off ea liphio — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML ea SA.",
      "Bolella chemist ka lefu la liphio, matšoenyeho a botsofali, lijo tse sa tloaelehang, le MERIANA EOHLE e meng ea lefu la tsoekere.",
      "Ithute matšoao a hypo (ho fufuleloa, ho thothomela, ho ferekana) 'me u boloke moralo oa pholoso o elelitsoeng ke ngaka — Materia ha e o iqape.",
      "Botsoa hore na u etsa eng matsatsing a ho kula ha u sa khone ho ja, le hore na joala e eketsa kotsi ea hypo.",
      "Haeba u sitoa ho tsosa motho ea belaelloang ka tsoekere e tlase, kapa ho thothomela ho hlaha — letsetsa litšebeletso tsa tšohanyetso.",
    ],
    [
      "I-glibenclamide yipilisi ye-sulfonylurea enokunciphisa iswekile yegazi — umngcipheko we-hypoglycaemia yinto ephambili yokucebisa.",
      "I-Materia ayiyiqiqi idosi okanye umda wezintso — Qinisekisa nemveliso enelebula kunye ne-STG/EML yaseMzantsi Afrika.",
      "Xelela usokhemisi ngesifo sezintso, iinkxalabo zobudala, ukutya okungaqhelekanga, nawo WONKE amanye amayeza esifo seswekile.",
      "Funda iimpawu ze-hypo (ukubila, ukungcangcazela, ukudideka) kwaye ugcine isicwangciso sosindiso esicebiswe ngugqirha — i-Materia ayisiyiqiqi eso sicwangciso.",
      "Buza ukuba wenza ntoni ngeentsuku zokugula xa ungakwazi ukutya, nokuba utywala luyawandisa na umngcipheko we-hypo.",
      "Ukuba awukwazi ukuvusa umntu ekucingelwa ukuba uneswekile ephantsi, okanye ukuxhuzula kuvela — tsalela iinkonzo ezingxamisekileyo.",
    ],
  ),

  "mol-amiodarone": five(
    [
      "Amiodarone is a multi-channel antiarrhythmic used in selected heart-rhythm pathways — monitoring often continues long term.",
      "Materia does not invent loading/maintenance doses or monitoring intervals — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about thyroid disease, lung disease, liver disease, and ALL other medicines — interaction checks are essential.",
      "Report new shortness of breath, cough, eye problems, yellowing of the eyes, or unusual skin sensitivity to sun.",
      "Ask which blood tests and heart checks your clinician plans while you remain on amiodarone.",
      "If severe breathlessness, fainting, or yellowing develops — seek urgent clinical review.",
    ],
    [
      "I-amiodarone i-antiarrhythmic esetshenziswa ezindleleni ezikhethiwe zesigqi senhliziyo — ukuqapha kuvame ukuqhubeka isikhathi eside.",
      "I-Materia ayiqambi imithamo yokuqala/yokugcina noma izikhathi zokuqapha — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela usokhemisi ngesifo se-thyroid, amaphaphu, isibindi, nawo WONKE amanye amaphilisi — ukuhlolwa kokuxhumana kubalulekile.",
      "Bika ukuphefumula okusha okunzima, ukukhwehlela, izinkinga zamehlo, ukuphuzi, noma ukuzwela kwesikhumba elangeni.",
      "Buza ukuthi yiziphi izivivinyo zegazi nokuhlolwa kwenhliziyo udokotela akuhlelele ngenkathi usesebenzisa i-amiodarone.",
      "Uma ukuphefumula kanzima kakhulu, ukuwa, noma ukuphuzi kuvela — funa ukuhlolwa ngokushesha.",
    ],
    [
      "Amiodaroon is 'n multi-kanaal antiaritmiese middel in geselekteerde hart-ritmepaaie — monitering duur dikwels lank.",
      "Materia versin nie laai-/onderhouddosisse of moniteringintervalle nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van tiroïedsiekte, longsiekte, lewersiekte, en ALLE ander medisyne — interaksiekontroles is noodsaaklik.",
      "Rapporteer nuwe asemnood, hoes, oogprobleme, vergeling, of ongewone sonvelgevoeligheid.",
      "Vra watter bloedtoetse en hartkontroles jou klinikus beplan terwyl jy op amiodaroon bly.",
      "As ernstige asemnood, floute, of vergeling ontwikkel — soek dringende kliniese hersiening.",
    ],
    [
      "Amiodarone ke antiarrhythmic e sebelisoang litseleng tse khethiloeng tsa morethetho oa pelo — tlhokomelo hangata e tsoela pele nako e telele.",
      "Materia ha e iqape litekanyo tsa ho qala/ho boloka kapa nako ea ho hlokomela — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella chemist ka lefu la thyroid, matšoafo, sebete, le MERIANA EOHLE e meng — tlhahlobo ea ho sebelisana e bohlokoa.",
      "Tlaleha ho hema ho mocha ho thata, ho khohlela, mathata a mahlo, ho mofubelu, kapa ho utloa letlalo le tsamaea le letsatsi.",
      "Botsoa hore na ke liteko life tsa mali le tlhahlobo ea pelo eo ngaka e e rerileng ha u ntse u sebelisa amiodarone.",
      "Haeba ho hema thata haholo, ho oa, kapa ho mofubelu ho hlaha — batla tlhahlobo ea potlako.",
    ],
    [
      "I-amiodarone yi-antiarrhythmic esetyenziswa kwiindlela ezikhethiweyo zesigqi sentliziyo — ukubeka esweni kudla ngokuqhubeka ixesha elide.",
      "I-Materia ayiyiqiqi iidosi zokuqala/zokugcina okanye amaxesha okuqaphela — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela usokhemisi ngesifo se-thyroid, imiphunga, isibindi, nawo WONKE amanye amayeza — ukuhlola ukudibana kubalulekile.",
      "Xela ukuphefumla okutsha okunzima, ukukhohlela, iingxaki zamehlo, ukutyheliwa, okanye ukuziva kwesikhumba elangeni.",
      "Buza ukuba zeziphi iimvavanyo zegazi kunye nokuhlola intliziyo ugqirha akucwangcisela ngelixa usebenzisa i-amiodarone.",
      "Ukuba ukuphefumla nzima kakhulu, ukuwa, okanye ukutyheliwa kuvela — funa uphononongo ngokukhawuleza.",
    ],
  ),

  "mol-adenosine": five(
    [
      "Adenosine is an acute hospital medicine used in selected SVT pathways — it is given only with cardiac monitoring capability.",
      "Materia does not invent a dose or flush technique — confirm against current SA STG/EML and the labelled product.",
      "Tell the team about asthma/COPD, heart transplant history, and ALL other medicines before adenosine is considered.",
      "A brief flush, chest discomfort, or pause in heart beat can occur — the team expects and watches for this.",
      "Ask what rhythm diagnosis they are treating and what happens if the first dose does not convert the rhythm.",
      "If severe breathing difficulty or prolonged chest pain continues after the dose — alert clinicians immediately.",
    ],
    [
      "I-adenosine umuthi wesibhedlela ophuthumayo osetshenziswa ezindleleni ezikhethiwe ze-SVT — unikwa kuphela lapho kukhona ukuqapha inhliziyo.",
      "I-Materia ayiqambi umthamo noma indlela ye-flush — qinisekisa ne-STG/EML yaseNingizimu Afrika nomkhiqizo onelebula.",
      "Tshela ithimba nge-asthma/COPD, umlando wokufakelwa inhliziyo, nawo WONKE amanye amaphilisi ngaphambi kwe-adenosine.",
      "Ukushisa okufushane, ukungakhululeki esifubeni, noma ukumiswa kwesigqi kungenzeka — ithimba liyalindela futhi liyaqapha.",
      "Buza ukuthi yisiphi isigqi eselashwayo nokuthi kwenzekani uma umthamo wokuqala ungaguquli isigqi.",
      "Uma ukuphefumula kanzima noma ubuhlungu besifuba obuqhubekayo ngemva komthamo — xwayisa odokotela ngokushesha.",
    ],
    [
      "Adenosien is 'n akute hospitaalmedisyne in geselekteerde SVT-paaie — dit word slegs met hartmoniteringvermoë gegee.",
      "Materia versin nie 'n dosis of spoel-tegniek nie — bevestig teen huidige SA STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van asma/COPD, hartoorplantinggeskiedenis, en ALLE ander medisyne voordat adenosien oorweeg word.",
      "'n Kort flush, borsongemak, of pouse in hartklop kan voorkom — die span verwag en let hierop.",
      "Vra watter ritme-diagnose hulle behandel en wat gebeur as die eerste dosis die ritme nie omskakel nie.",
      "As ernstige asemnood of aanhoudende borspyn ná die dosis voortduur — waarsku klinici onmiddellik.",
    ],
    [
      "Adenosine ke moriana oa sepetlele oa tšohanyetso o sebelisoang litseleng tse khethiloeng tsa SVT — o fanoa feela ha ho na le bokhoni ba ho hlokomela pelo.",
      "Materia ha e iqape tekanyo kapa mokhoa oa flush — netefatsa khahlanong le STG/EML ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka asthma/COPD, histori ea ho kenya pelo, le MERIANA EOHLE e meng pele adenosine e nahanoa.",
      "Ho futhumala ha nakoana, ho se phutholohe sefubeng, kapa khefu ea lebelo la pelo ho ka hlaha — sehlopha sea lebella 'me sea hlokomela.",
      "Botsoa hore na ke diagnosis efe ea morethetho eo ba e alafang le hore na ho etsahala eng haeba tekanyo ea pele e sa fetole morethetho.",
      "Haeba ho hema thata kapa bohloko ba sefuba bo tsoelang pele ka mor'a tekanyo — tsebisa lingaka hang-hang.",
    ],
    [
      "I-adenosine liyeza lesibhedlele elingxamisekileyo elisetyenziswa kwiindlela ezikhethiweyo ze-SVT — linikwa kuphela kunye nokukwazi ukubeka esweni intliziyo.",
      "I-Materia ayiyiqiqi idosi okanye indlela ye-flush — Qinisekisa ne-STG/EML yaseMzantsi Afrika kunye nemveliso enelebula.",
      "Xelela iqela nge-asthma/COPD, imbali yokufakelwa intliziyo, nawo WONKE amanye amayeza phambi kwe-adenosine.",
      "Ukushisa okufutshane, ukungakhululeki esifubeni, okanye ukunqamka kwesigqi kunokuvela — iqela liyalindela kwaye liyaqaphela.",
      "Buza ukuba yeyiphi isigqi esinyangwayo nokuba kwenzeka ntoni ukuba idosi yokuqala ayiguquli isigqi.",
      "Ukuba ukuphefumla nzima okanye intlungu yesifuba eqhubekayo emva kwedosi — xelela oogqirha ngoko nangoko.",
    ],
  ),

  "mol-nevirapine": five(
    [
      "Nevirapine is an NNRTI antiretroviral that may still appear in selected ART pathways — adherence and liver-safety counselling matter.",
      "Materia does not invent a regimen or lead-in schedule — confirm against current DoH HIV STG/EML and the labelled product.",
      "Tell your pharmacist about rash history, liver disease, pregnancy plans, and ALL other medicines — interactions are important.",
      "Report rash, fever, yellowing of the eyes, dark urine, or severe tummy pain promptly — do not ignore new skin symptoms.",
      "Ask what blood tests are planned when starting or switching nevirapine-containing therapy.",
      "If blistering rash, breathing difficulty, or yellowing develops — seek urgent care and contact your HIV clinic.",
    ],
    [
      "I-nevirapine i-NNRTI antiretroviral engase ibonakale ezindleleni ezikhethiwe ze-ART — ukunamathela nokuphepha kwesibindi kubalulekile.",
      "I-Materia ayiqambi uhlelo noma i-lead-in — qinisekisa ne-HIV STG/EML ye-DoH yamanje nomkhiqizo onelebula.",
      "Tshela usokhemisi ngomlando werashi, isifo sesibindi, izinhlelo zokukhulelwa, nawo WONKE amanye amaphilisi.",
      "Bika irashi, umkhuhlane, ukuphuzi, umchamo omnyama, noma ubuhlungu besisu ngokushesha — ungazishiya izimpawu zesikhumba.",
      "Buza ukuthi yiziphi izivivinyo zegazi ezihleliwe lapho uqala noma ushintsha ukwelashwa okune-nevirapine.",
      "Uma irashi elinamabhamuza, ubunzima bokuphefumula, noma ukuphuzi kuvela — funa usizo uthinte ikliniki ye-HIV.",
    ],
    [
      "Nevirapien is 'n NNRTI-antiretrovirale middel wat nog in geselekteerde ART-paaie mag voorkom — nakoming en lewer-veiligheid saak.",
      "Materia versin nie 'n regimen of inleidingskedule nie — bevestig teen huidige DoH HIV STG/EML en die geëtiketteerde produk.",
      "Sê vir jou apteker van uitslaggeskiedenis, lewersiekte, swangerskapsplanne, en ALLE ander medisyne.",
      "Rapporteer uitslag, koors, vergeling, donker urine, of ernstige buikpyn gou — ignoreer nie nuwe vel simptome nie.",
      "Vra watter bloedtoetse beplan is wanneer nevirapien-bevattende terapie begin of verander word.",
      "As blaasuitslag, asemnood, of vergeling ontwikkel — soek dringende sorg en kontak jou MIV-kliniek.",
    ],
    [
      "Nevirapine ke NNRTI antiretroviral e ka ntse e hlaha litseleng tse khethiloeng tsa ART — ho khomarela le tšireletso ea sebete hoa bohlokoa.",
      "Materia ha e iqape moralo kapa lead-in — netefatsa khahlanong le HIV STG/EML ea DoH ea hajoale le sehlahisoa se nang le ileibole.",
      "Bolella chemist ka histori ea lekome, lefu la sebete, merero ea bokhachane, le MERIANA EOHLE e meng.",
      "Tlaleha lekome, feberu, ho mofubelu, moroto o lefifi, kapa bohloko ba mpeng ka potlako — u se ke ua hlokomoloha matšoao a letlalo.",
      "Botsoa hore na ke liteko life tsa mali tse reriloeng ha u qala kapa u fetola kalafo e nang le nevirapine.",
      "Haeba lekome le nang le li-blister, ho hema thata, kapa ho mofubelu ho hlaha — batla thuso 'me u ikopanye le tleliniki ea HIV.",
    ],
    [
      "I-nevirapine yi-NNRTI antiretroviral enokuvela kwiindlela ezikhethiweyo ze-ART — ukunamathela nokhuseleko lwesibindi kubalulekile.",
      "I-Materia ayiyiqiqi inkqubo okanye i-lead-in — Qinisekisa ne-HIV STG/EML ye-DoH yangoku kunye nemveliso enelebula.",
      "Xelela usokhemisi ngembali yerhashi, isifo sesibindi, izicwangciso zokukhulelwa, nawo WONKE amanye amayeza.",
      "Xela irhashi, umkhuhlane, ukutyheliwa, umchamo omnyama, okanye intlungu yesisu ngokukhawuleza — ungazityesheli iimpawu zesikhumba.",
      "Buza ukuba zeziphi iimvavanyo zegazi ezicwangcisiweyo xa uqala okanye utshintsha unyango olune-nevirapine.",
      "Ukuba irhashi elinamabhulorho, ubunzima bokuphefumla, okanye ukutyheliwa kuvela — funa uncedo uqhagamshelane neklinikhi ye-HIV.",
    ],
  ),

  "mol-atazanavir": five(
    [
      "Atazanavir is an HIV protease inhibitor used in selected ART regimens — it is often taken with a pharmacokinetic booster as directed.",
      "Materia does not invent a dose, booster pairing, or interaction list — confirm against current DoH HIV STG/EML and the labelled product.",
      "Tell your pharmacist about acid-reducing medicines, jaundice history, kidney stones, and ALL other medicines and herbals.",
      "Yellowing of the eyes can occur with atazanavir and needs clinical interpretation — do not stop without advice.",
      "Ask how food timing and acid suppressants affect absorption for your specific regimen.",
      "If severe tummy/back pain, inability to pass urine, or deep yellowing develops — seek urgent clinical review.",
    ],
    [
      "I-atazanavir i-HIV protease inhibitor esetshenziswa ezinhlelweni ezikhethiwe ze-ART — ivame ukuthathwa ne-booster njengomyalelo.",
      "I-Materia ayiqambi umthamo, ukubhanqa kwe-booster, noma uhlu lokuxhumana — qinisekisa ne-HIV STG/EML ye-DoH nomkhiqizo onelebula.",
      "Tshela usokhemisi ngemithi enciphisa i-asidi, umlando wokuphuzi, amatshe ezinso, nawo WONKE amanye amaphilisi nezitshalo.",
      "Ukuphuzi kwamehlo kungenzeka nge-atazanavir futhi kudinga ukuhunyushwa kodokotela — ungayeki ngaphandle kweseluleko.",
      "Buza ukuthi isikhathi sokudla nezinciphisi ze-asidi zithinta kanjani ukumunca ohlelweni lwakho.",
      "Uma ubuhlungu besisu/umhlane obukhulu, ukungachami, noma ukuphuzi okukhulu kuvela — funa ukuhlolwa ngokushesha.",
    ],
    [
      "Atasanavir is 'n MIV-protease-inhibeerder in geselekteerde ART-regimens — dit word dikwels met 'n farmakokinetiese versterker soos aangedui geneem.",
      "Materia versin nie 'n dosis, versterker-paring, of interaksielys nie — bevestig teen huidige DoH HIV STG/EML en die geëtiketteerde produk.",
      "Sê vir jou apteker van suurverminderende medisyne, geelsuggeskiedenis, nierstene, en ALLE ander medisyne en kruie.",
      "Vergeling van die oë kan met atasanavir voorkom en benodig kliniese interpretasie — moenie sonder advies stop nie.",
      "Vra hoe voedingstydsberekening en suuronderdrukkers absorpsie vir jou spesifieke regimen beïnvloed.",
      "As ernstige buik-/rugpyn, onvermoë om urine te passeer, of diep vergeling ontwikkel — soek dringende kliniese hersiening.",
    ],
    [
      "Atazanavir ke HIV protease inhibitor e sebelisoang moralong o khethiloeng oa ART — hangata e nkoa le booster joalo ka tataiso.",
      "Materia ha e iqape tekanyo, ho kopanya booster, kapa lenane la ho sebelisana — netefatsa khahlanong le HIV STG/EML ea DoH le sehlahisoa se nang le ileibole.",
      "Bolella chemist ka meriana e fokotsang asiti, histori ea ho mofubelu, majoe a liphio, le MERIANA EOHLE e meng le litlama.",
      "Ho mofubelu ha mahlo ho ka hlaha ka atazanavir 'me ho hloka tlhaloso ea bongaka — u se ke ua emisa ntle le keletso.",
      "Botsoa hore na nako ea lijo le li-suppressant tsa asiti li ama monko joang moralong oa hau.",
      "Haeba bohloko ba mpeng/mokokotlo bo matla, ho sitoa ho ntša moroto, kapa ho mofubelu ho tebileng ho hlaha — batla tlhahlobo ea potlako.",
    ],
    [
      "I-atazanavir yi-HIV protease inhibitor esetyenziswa kwiinkqubo ezikhethiweyo ze-ART — idla ngokuthathwa kunye ne-booster njengomyalelo.",
      "I-Materia ayiyiqiqi idosi, ukudibanisa i-booster, okanye uluhlu lokudibana — Qinisekisa ne-HIV STG/EML ye-DoH kunye nemveliso enelebula.",
      "Xelela usokhemisi ngamayeza anciphisa iasidi, imbali yokutyheliwa, amatye ezintso, nawo WONKE amanye amayeza nezityalo.",
      "Ukutyheliwa kwamehlo kunokuvela nge-atazanavir kwaye kufuna ukutolikwa kwezonyango — ungayeki ngaphandle kwengcebiso.",
      "Buza ukuba ixesha lokutya kunye nezinciphisi zeasidi zichaphazela njani ukufunxa kwinkqubo yakho.",
      "Ukuba intlungu yesisu/umqolo enzima, ukungakwazi ukuchama, okanye ukutyheliwa okunzulu kuvela — funa uphononongo ngokukhawuleza.",
    ],
  ),

  "mol-chlorpromazine": five(
    [
      "Chlorpromazine is a typical antipsychotic used in selected acute and chronic psychiatry pathways — sedation and movement side-effects are key counselling points.",
      "Materia does not invent a dose or titration — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about other sedatives, alcohol, heart disease, and ALL other medicines.",
      "Avoid alcohol and be careful with driving or machinery until you know how sedated you feel.",
      "Ask what movement side-effects to watch for and when to seek urgent review for fever with rigidity.",
      "If high fever with stiff muscles, severe restlessness, or fainting occurs — seek emergency care.",
    ],
    [
      "I-chlorpromazine i-antipsychotic ejwayelekile esetshenziswa ezindleleni ezikhethiwe zengqondo — ukulala kanye nemiphumela yokunyakaza kubalulekile.",
      "I-Materia ayiqambi umthamo noma i-titration — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela usokhemisi ngezanye izidakamizwa, utshwala, isifo senhliziyo, nawo WONKE amanye amaphilisi.",
      "Gwema utshwala futhi qaphela ukushayela noma imishini uze wazi ukuthi uzizwa kanjani.",
      "Buza ukuthi yiziphi izimpawu zokunyakaza okufanele uziqaphele nokuthi ubheka nini usizo uma kunomkhuhlane nokuqina.",
      "Uma umkhuhlane ophezulu nemisipha eqinile, ukungakhululeki okukhulu, noma ukuwa — funa usizo oluphuthumayo.",
    ],
    [
      "Chloorpromasien is 'n tipiese antipsigotikum in geselekteerde psigiatrie-paaie — sedasie en bewegingsnewe-effekte is sleutelberadingspunte.",
      "Materia versin nie 'n dosis of titrasie nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van ander kalmeermiddels, alkohol, hartsiekte, en ALLE ander medisyne.",
      "Vermy alkohol en wees versigtig met bestuur of masjinerie totdat jy weet hoe verslaap jy voel.",
      "Vra watter bewegingsnewe-effekte om dop te hou en wanneer om dringende hersiening te soek vir koors met styfheid.",
      "As hoë koors met stywe spiere, ernstige rusteloosheid, of floute voorkom — soek noodhulp.",
    ],
    [
      "Chlorpromazine ke antipsychotic e tloaelehileng e sebelisoang litseleng tse khethiloeng tsa kelello — ho otlolla le liphello tsa motsamao ke lintlha tsa bohlokoa.",
      "Materia ha e iqape tekanyo kapa titration — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella chemist ka lithethefatsi tse ling, joala, lefu la pelo, le MERIANA EOHLE e meng.",
      "Qoba joala 'me u hlokomele ho khanna kapa mechini ho fihlela u tseba hore na u ikutloa joang.",
      "Botsoa hore na ke liphello life tsa motsamao tseo u lokelang ho li hlokomela le hore na u batla tlhahlobo neng bakeng sa feberu le ho thatafala.",
      "Haeba feberu e phahameng le mesifa e thata, ho se phomole ho matla, kapa ho oa — batla thuso ea tšohanyetso.",
    ],
    [
      "I-chlorpromazine yi-antipsychotic eqhelekileyo esetyenziswa kwiindlela ezikhethiweyo zengqondo — ukulala kunye neziphumo zokushukuma zibalulekile.",
      "I-Materia ayiyiqiqi idosi okanye i-titration — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela usokhemisi ngezinye iziyobisi, utywala, isifo sentliziyo, nawo WONKE amanye amayeza.",
      "Pepa utywala kwaye lumkela ukuqhuba okanye oomatshini de wazi indlela oziva ngayo.",
      "Buza ukuba zeziphi iimpawu zokushukuma ofanele uziqaphele nokuba ufuna nini uphononongo ngenxa yomkhuhlane kunye nokuqina.",
      "Ukuba umkhuhlane ophezulu kunye nemisipha eqinileyo, ukungakhululeki okukhulu, okanye ukuwa — funa uncedo olungxamisekileyo.",
    ],
  ),

  "mol-clozapine": five(
    [
      "Clozapine is reserved for treatment-resistant psychosis pathways — structured haematological monitoring is essential and non-negotiable.",
      "Materia does not invent a titration or FBC monitoring schedule — confirm against the labelled product, clinic protocol, and current SA STG/EML.",
      "Tell every clinician about sore throat, fever, or infection symptoms before each supply — low white cells can be life-threatening.",
      "Do not restart after a break without specialist advice — missed doses need a clinician plan.",
      "Ask which blood-test days are required and what happens if you miss a clinic appointment.",
      "If fever, sore throat, mouth ulcers, or unexplained bruising develops — seek urgent care and contact the clozapine clinic the same day.",
    ],
    [
      "I-clozapine igcinelwe izindlela zengqondo ezingelapheki kalula — ukuqapha kwegazi okuhleliwe kubalulekile futhi akuphikiswa.",
      "I-Materia ayiqambi i-titration noma uhlelo lwe-FBC — qinisekisa nomkhiqizo onelebula, inqubo yekliniki, ne-STG/EML.",
      "Tshela wonke udokotela ngomphimbo obuhlungu, umkhuhlane, noma izimpawu zesifo ngaphambi kokunikezwa ngakunye — amaseli amhlophe aphansi angabulala.",
      "Ungaqali kabusha ngemva kwekhefu ngaphandle kweseluleko sochwepheshe — imithamo elahlekile idinga uhlelo lukadokotela.",
      "Buza ukuthi yiziphi izinsuku zokuhlolwa kwegazi ezidingekayo nokuthi kwenzekani uma uphuthelwa yi-appointment.",
      "Uma umkhuhlane, umphimbo obuhlungu, izilonda zomlomo, noma ukulinyazeka okungaziwa kuvela — funa usizo uthinte ikliniki ye-clozapine ngalolo suku.",
    ],
    [
      "Clozapien is gereserveer vir behandelingsweerstandige psigose-paaie — gestruktureerde hematologiese monitering is noodsaaklik.",
      "Materia versin nie 'n titrasie of FBC-moniteringskedule nie — bevestig teen die geëtiketteerde produk, kliniekprotokol, en huidige SA STG/EML.",
      "Sê vir elke klinikus van seerkeel, koors, of infeksiesimptome vóór elke voorsiening — lae wit selle kan lewensgevaarlik wees.",
      "Moenie ná 'n underbreking sonder spesialisadvies herbegin nie — gemiste dosisse benodig 'n klinikusplan.",
      "Vra watter bloedtoetsdae vereis word en wat gebeur as jy 'n kliniekafspraak mis.",
      "As koors, seerkeel, mondsere, of onverklaarde kneusings ontwikkel — soek dringende sorg en kontak die clozapienkliniek dieselfde dag.",
    ],
    [
      "Clozapine e boloketsoe litsela tsa psychosis tse hanyetsang kalafo — tlhokomelo ea mali e hlophisitsoeng e bohlokoa.",
      "Materia ha e iqape titration kapa kemiso ea FBC — netefatsa khahlanong le sehlahisoa se nang le ileibole, protocol ea tleliniki, le STG/EML.",
      "Bolella ngaka eohle ka 'metso o bohloko, feberu, kapa matšoao a tšoaetso pele ho fanoa ha 'ngoe le e 'ngoe — lisele tse tšoeu tse tlase li ka bolaea.",
      "U se ke ua qala hape ka mor'a khefu ntle le keletso ea setsebi — litekanyo tse lahlehileng li hloka moralo oa ngaka.",
      "Botsoa hore na ke matsatsi afe a liteko tsa mali a hlokahalang le hore na ho etsahala eng haeba u fosa appointment.",
      "Haeba feberu, 'metso o bohloko, liso tsa molomo, kapa ho otloa ho sa hlaloseng ho hlaha — batla thuso 'me u ikopanye le tleliniki ea clozapine ka letsatsi leo.",
    ],
    [
      "I-clozapine igcinelwe iindlela zengqondo ezingaphatheki lula — ukubeka esweni kwegazi okucwangcisiweyo kubalulekile.",
      "I-Materia ayiyiqiqi i-titration okanye ishedyuli ye-FBC — Qinisekisa nemveliso enelebula, umgaqo weklinikhi, kunye ne-STG/EML.",
      "Xelela wonke ugqirha ngomqala obuhlungu, umkhuhlane, okanye iimpawu zesifo phambi kokunikezelwa ngakunye — iiseli ezimhlophe eziphantsi zinokubulala.",
      "Ungaqali kwakhona emva kwekhefu ngaphandle kwengcebiso yengcali — iidosi ezilahlekileyo zifuna isicwangciso sikagqirha.",
      "Buza ukuba zeziphi iintsuku zovavanyo lwegazi ezifunekayo nokuba kwenzeka ntoni ukuba uphoswa yi-appointment.",
      "Ukuba umkhuhlane, umqala obuhlungu, izilonda zomlomo, okanye ukulimala okungachazwanga kuvela — funa uncedo uqhagamshelane neklinikhi ye-clozapine kwangolo suku.",
    ],
  ),

  "mol-phenobarbital": five(
    [
      "Phenobarbital is a barbiturate antiepileptic used in selected seizure pathways — sedation and interaction risk are central counselling points.",
      "Materia does not invent a dose or blood-level target — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about pregnancy plans, other sedatives, alcohol, and ALL other medicines — enzyme induction affects many drugs.",
      "Do not stop suddenly unless a clinician directs an emergency change — abrupt withdrawal can worsen seizures.",
      "Ask about contraception effectiveness if relevant, and what sedative activities to avoid while starting therapy.",
      "If severe rash, breathing difficulty, or prolonged seizures occur — seek emergency care.",
    ],
    [
      "I-phenobarbital i-barbiturate antiepileptic esetshenziswa ezindleleni ezikhethiwe zokuxega — ukulala nengozii yokuxhumana kubalulekile.",
      "I-Materia ayiqambi umthamo noma umgomo wezinga legazi — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela usokhemisi ngezinhlelo zokukhulelwa, ezinye izidakamizwa, utshwala, nawo WONKE amanye amaphilisi.",
      "Ungayeki ngokuzumayo ngaphandle uma udokotela eyala ushintsho oluphuthumayo — ukuyeka kungabi kabi koku xega.",
      "Buza ngokusebenza kwezokuvimbela ukukhulelwa uma kufanele, nokuthi yiziphi izinto zokulala okufanele uzigweme uma uqala.",
      "Uma irashi elibi, ubunzima bokuphefumula, noma ukuxega okude kuvela — funa usizo oluphuthumayo.",
    ],
    [
      "Fenobarbital is 'n barbituraat-antiepileptikum in geselekteerde aanvalpaaie — sedasie en interaksierisiko is sentraal.",
      "Materia versin nie 'n dosis of bloedvlakteiken nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van swangerskapsplanne, ander kalmeermiddels, alkohol, en ALLE ander medisyne.",
      "Moenie skielik stop nie tensy 'n klinikus 'n noodverandering rig — abrupte onttrekking kan aanvalle vererger.",
      "Vra oor voorbehoedingseffektiwiteit indien relevant, en watter sedatiewe aktiwiteite om te vermy wanneer terapie begin.",
      "As ernstige uitslag, asemnood, of langdurige aanvalle voorkom — soek noodhulp.",
    ],
    [
      "Phenobarbital ke barbiturate antiepileptic e sebelisoang litseleng tse khethiloeng tsa ho thothomela — ho otlolla le kotsi ea ho sebelisana ke lintlha tsa bohlokoa.",
      "Materia ha e iqape tekanyo kapa sepheo sa boemo ba mali — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella chemist ka merero ea bokhachane, lithethefatsi tse ling, joala, le MERIANA EOHLE e meng.",
      "U se ke ua emisa ka tšohanyetso ntle le haeba ngaka e laela phetoho ea tšohanyetso — ho tlohela ka tšohanyetso ho ka mpefatsa ho thothomela.",
      "Botsoa ka katleho ea thibelo ea bokhachane haeba ho hlokahala, le hore na ke mesebetsi efe ea ho otlolla eo u lokelang ho e qoba ha u qala.",
      "Haeba lekome le matla, ho hema thata, kapa ho thothomela ho telele ho hlaha — batla thuso ea tšohanyetso.",
    ],
    [
      "I-phenobarbital yi-barbiturate antiepileptic esetyenziswa kwiindlela ezikhethiweyo zokuxhuzula — ukulala kunye nomngcipheko wokudibana kubalulekile.",
      "I-Materia ayiyiqiqi idosi okanye umgomo wenqanaba legazi — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela usokhemisi ngezicwangciso zokukhulelwa, ezinye iziyobisi, utywala, nawo WONKE amanye amayeza.",
      "Ungayeki ngequbuliso ngaphandle kokuba ugqirha alathise utshintsho olungxamisekileyo — ukuyeka kungabi mbi koku xhuzula.",
      "Buza ngokusebenza kozithinteli zokukhulelwa ukuba kufanelekile, nokuba zeziphi izinto zokulala ofanele uzypephe xa uqala.",
      "Ukuba irhashi elibi, ubunzima bokuphefumla, okanye ukuxhuzula okude kuvela — funa uncedo olungxamisekileyo.",
    ],
  ),

  "mol-potassium-chloride": five(
    [
      "Potassium chloride replaces potassium — concentration and rate errors can be fatal, so hospital and institutional safety rules apply.",
      "Materia does not invent an infusion rate or mmol dose — confirm against current SA STG/EML and local electrolyte protocols.",
      "Tell clinicians about kidney disease, heart medicines (especially digoxin), and ALL other electrolytes you take.",
      "Report burning at the drip site, palpitations, muscle weakness, or tingling during IV potassium.",
      "Ask how often blood potassium will be rechecked while replacement continues.",
      "If sudden weakness, irregular heartbeat, or chest pain develops — alert the care team immediately.",
    ],
    [
      "I-potassium chloride ifaka i-potassium — amaphutha okugxilisa nesivinini angabulala, ngakho imithetho yesibhedlela iyasebenza.",
      "I-Materia ayiqambi isivinini se-infusion noma umthamo we-mmol — qinisekisa ne-STG/EML nemithetho yendawo.",
      "Tshela odokotela ngesifo sezinso, imithi yenhliziyo (ikakhulukazi i-digoxin), nawo WONKE amanye ama-electrolyte.",
      "Bika ukushisa endaweni ye-drip, ukushaya kwenhliziyo, ubuthaka bemisipha, noma ukucwizayo ngesikhathi se-IV potassium.",
      "Buza ukuthi i-potassium yegazi ihlolwa kangaki ngenkathi ukufaka kuqhubeka.",
      "Uma ubuthaka obusheshayo, isigqi esingajwayelekile, noma ubuhlungu besifuba kuvela — xwayisa ithimba ngokushesha.",
    ],
    [
      "Kaliumchloried vervang kalium — konsentrasie- en tempofoute kan dodelik wees, daarom geld hospitaalveiligheidsreëls.",
      "Materia versin nie 'n infusietempo of mmol-dosis nie — bevestig teen huidige SA STG/EML en plaaslike elektrolietprotokolle.",
      "Sê vir klinici van niersiekte, hartmedisyne (veral digoksien), en ALLE ander elektroliete wat jy neem.",
      "Rapporteer brand by die driplek, hartklop, spierswakheid, of tinteling tydens IV-kalium.",
      "Vra hoe gereeld bloedkalium herkontroleer word terwyl vervanging voortduur.",
      "As skielike swakheid, onreëlmatige hartklop, of borspyn ontwikkel — waarsku die sorgspan onmiddellik.",
    ],
    [
      "Potassium chloride e kenya potassium — liphoso tsa concentration le lebelo li ka bolaea, kahoo melao ea sepetlele ea sebetsa.",
      "Materia ha e iqape lebelo la infusion kapa tekanyo ea mmol — netefatsa khahlanong le STG/EML le melao ea lehae.",
      "Bolella lingaka ka lefu la liphio, meriana ea pelo (haholo digoxin), le LI-ELECTROLYTE TSOHLE tseo u li nkelang.",
      "Tlaleha ho chesa sebakeng sa drip, ho otla ha pelo, bokoa ba mesifa, kapa ho hlohlona nakong ea IV potassium.",
      "Botsoa hore na potassium ea mali e hlahloboa hangata hakae ha ho kenya ho tsoela pele.",
      "Haeba bokoa ba tšohanyetso, morethetho o sa tloaelehang, kapa bohloko ba sefuba ho hlaha — tsebisa sehlopha hang-hang.",
    ],
    [
      "I-potassium chloride ifaka i-potassium — iimpazamo zoxinaniso nesantya zinokubulala, ngoko imithetho yesibhedlele iyasebenza.",
      "I-Materia ayiyiqiqi isantya se-infusion okanye idosi ye-mmol — Qinisekisa ne-STG/EML kunye nemigaqo yendawo.",
      "Xelela oogqirha ngesifo sezintso, amayeza entliziyo (ngakumbi i-digoxin), nazo ZONKE ezinye ii-electrolyte.",
      "Xela ukutshisa kwindawo ye-drip, ukubetha kwentliziyo, ubuthaka bemisipha, okanye ukurhawuzela ngexesha le-IV potassium.",
      "Buza ukuba i-potassium yegazi ihlolwa rhoqo kangakanani ngelixa ukufaka kuqhubeka.",
      "Ukuba ubuthaka obukhawulezayo, isigqi esingaqhelekanga, okanye intlungu yesifuba kuvela — xelela iqela ngoko nangoko.",
    ],
  ),

  "mol-thiamine": five(
    [
      "Thiamine (vitamin B1) is used in deficiency and Wernicke-risk pathways — early replacement can be clinically urgent.",
      "Materia does not invent a dose or infusion sequence — confirm against the labelled product and current SA STG/EML.",
      "Tell clinicians about alcohol use, malnutrition, prolonged vomiting, and ALL other medicines.",
      "Injectable thiamine is given by clinicians; oral forms should be taken as labelled if prescribed for ongoing care.",
      "Ask why thiamine is being given in your case and whether further nutrition support is planned.",
      "If confusion, unsteady walking, or eye-movement problems worsen — alert the care team urgently.",
    ],
    [
      "I-thiamine (vitamin B1) isetshenziswa ekusweleni nasezindleleni ze-Wernicke — ukufaka kusenesikhathi kungaphuthuma.",
      "I-Materia ayiqambi umthamo noma ukulandelana kwe-infusion — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela odokotela ngotshwala, ukungondleki, ukuhlanza okude, nawo WONKE amanye amaphilisi.",
      "I-thiamine yomjovo inikezwa odokotela; amafomu omlomo kufanele athathwe njengelebula uma enqunyiwe.",
      "Buza ukuthi kungani i-thiamine inikezwa ecaleni lakho nokuthi kukhona yini ukwesekwa kokudla okwengeziwe.",
      "Uma ukudideka, ukuhamba okungazinzi, noma izinkinga zamehlo ziba kubi — xwayisa ithimba ngokushesha.",
    ],
    [
      "Tiamien (vitamien B1) word in tekort- en Wernicke-risiko-paaie gebruik — vroeë vervanging kan klinies dringend wees.",
      "Materia versin nie 'n dosis of infusiesekwens nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir klinici van alkoholgebruik, wanvoeding, langdurige braking, en ALLE ander medisyne.",
      "Inspuitbare tiamien word deur klinici gegee; mondelinge vorms moet soos geëtiketteer geneem word indien voorgeskryf.",
      "Vra waarom tiamien in jou geval gegee word en of verdere voedingsteun beplan is.",
      "As verwarring, onstabiele loop, of oogbewegingsprobleme versleg — waarsku die sorgspan dringend.",
    ],
    [
      "Thiamine (vitamin B1) e sebelisoa litseleng tsa khaello le kotsi ea Wernicke — ho kenya kapele ho ka potlaka.",
      "Materia ha e iqape tekanyo kapa tatellano ea infusion — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella lingaka ka tšebeliso ea joala, khaello ea lijo, ho hlatsa ho telele, le MERIANA EOHLE e meng.",
      "Thiamine ea ente e fanoa ke lingaka; liforomo tsa molomo li lokela ho nkoa joalo ka ileibole haeba li ngoliloe.",
      "Botsoa hore na ke hobaneng thiamine e fanoa nyeoeng ea hau le hore na ho na le tšehetso e 'ngoe ea lijo e reriloeng.",
      "Haeba ho ferekana, ho tsamaea ho sa tsitsang, kapa mathata a mahlo a mpefala — tsebisa sehlopha ka potlako.",
    ],
    [
      "I-thiamine (vitamin B1) isetyenziswa kwiindlela zokungabikho kunye nomngcipheko we-Wernicke — ukufaka kwangethuba kunokuba ngxamisekile.",
      "I-Materia ayiyiqiqi idosi okanye ulandelelwano lwe-infusion — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela oogqirha ngokusebenzisa utywala, ukungondleki, ukugabha okude, nawo WONKE amanye amayeza.",
      "I-thiamine yenjeksini inikwa ngoogqirha; iifomu zomlomo kufuneka zithathwe njengelebula ukuba zimiselwe.",
      "Buza ukuba kutheni i-thiamine inikwa kwityala lakho nokuba kukho na inkxaso yokutya eyongezelelweyo.",
      "Ukuba ukudideka, ukuhamba okungazinzi, okanye iingxaki zamehlo ziya kuba mbi — xelela iqela ngokukhawuleza.",
    ],
  ),

  "mol-pyridoxine": five(
    [
      "Pyridoxine (vitamin B6) is used in deficiency and as an isoniazid adjunct in selected TB pathways.",
      "Materia does not invent a dose — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist if you are on isoniazid or other TB medicines, and about neuropathy symptoms in hands or feet.",
      "Take as directed with your TB regimen when prescribed as an adjunct — do not stop one medicine without advice.",
      "Ask whether tingling or numbness should be reported as possible neuropathy needing review.",
      "If new severe numbness, weakness, or skin blistering develops — seek clinical advice promptly.",
    ],
    [
      "I-pyridoxine (vitamin B6) isetshenziswa ekusweleni nanjengesengezo se-isoniazid ezindleleni ezikhethiwe ze-TB.",
      "I-Materia ayiqambi umthamo — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela usokhemisi uma usebenzisa i-isoniazid noma eminye imithi ye-TB, nangezimpawu ze-neuropathy ezandleni noma ezinyaweni.",
      "Thatha ngomyalelo nohlelo lwakho lwe-TB uma inqunyiwe njengesengezo — ungayeki omunye umuthi ngaphandle kweseluleko.",
      "Buza ukuthi ukucwizayo noma ukuba yizintambo kufanele kubikwe njenge-neuropathy edinga ukuhlolwa.",
      "Uma ukuba yizintambo okusha okukhulu, ubuthaka, noma amabhamuza esikhumba kuvela — funa iseluleko ngokushesha.",
    ],
    [
      "Piridoksien (vitamien B6) word in tekort en as isoniasied-aanvulling in geselekteerde TB-paaie gebruik.",
      "Materia versin nie 'n dosis nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker as jy op isoniasied of ander TB-medisyne is, en oor neuropatiesimptome in hande of voete.",
      "Neem soos aangedui met jou TB-regimen wanneer as aanvulling voorgeskryf — moenie een medisyne sonder advies stop nie.",
      "Vra of tinteling of doofheid as moontlike neuropatie gerapporteer moet word.",
      "As nuwe ernstige doofheid, swakheid, of velblase ontwikkel — soek gou kliniese advies.",
    ],
    [
      "Pyridoxine (vitamin B6) e sebelisoa khaellong le e le tlatsetso ea isoniazid litseleng tse khethiloeng tsa TB.",
      "Materia ha e iqape tekanyo — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella chemist haeba u sebelisa isoniazid kapa meriana e meng ea TB, le ka matšoao a neuropathy matsohong kapa maotong.",
      "Nka joalo ka tataiso le moralo oa hau oa TB haeba e ngoliloe e le tlatsetso — u se ke ua emisa moriana o mong ntle le keletso.",
      "Botsoa hore na ho hlohlona kapa ho hloka maikutlo ho lokela ho tlalehoa e le neuropathy e hlokang tlhahlobo.",
      "Haeba ho hloka maikutlo ho mocha ho matla, bokoa, kapa li-blister tsa letlalo ho hlaha — batla keletso ka potlako.",
    ],
    [
      "I-pyridoxine (vitamin B6) isetyenziswa ekungabikho nanjengesongezo se-isoniazid kwiindlela ezikhethiweyo ze-TB.",
      "I-Materia ayiyiqiqi idosi — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela usokhemisi ukuba usebenzisa i-isoniazid okanye amanye amayeza e-TB, nangeempawu ze-neuropathy ezandleni okanye ezinyaweni.",
      "Thatha ngomyalelo nenkqubo yakho ye-TB xa imiselwe njengesongezo — ungayeki elinye iyeza ngaphandle kwengcebiso.",
      "Buza ukuba ukurhawuzela okanye ukuba ziintambo kufanele kuxelwe njenge-neuropathy efuna uphononongo.",
      "Ukuba ukuba ziintambo okutsha okukhulu, ubuthaka, okanye amabhulorho esikhumba kuvela — funa ingcebiso ngokukhawuleza.",
    ],
  ),

  "mol-oseltamivir": five(
    [
      "Oseltamivir is a neuraminidase inhibitor used in selected influenza treatment or prevention pathways.",
      "Materia does not invent a start-window or renal adjustment — confirm against the labelled product and current SA STG/EML.",
      "Tell your pharmacist about kidney disease, pregnancy or breastfeeding, and ALL other medicines.",
      "Start as soon as directed after influenza symptoms or exposure when prescribed — delayed starts may be less useful.",
      "Ask what to do if you vomit a dose and which warning symptoms mean you need urgent review (for example breathing difficulty).",
      "If breathing worsens, confusion, or you cannot keep fluids down — seek urgent care; influenza complications need clinical assessment.",
    ],
    [
      "I-oseltamivir i-neuraminidase inhibitor esetshenziswa ezindleleni ezikhethiwe zokwelapha noma zokuvimbela i-influenza.",
      "I-Materia ayiqambi iwindi yokuqala noma ukulungiswa kwezinso — qinisekisa nomkhiqizo onelebula ne-STG/EML.",
      "Tshela usokhemisi ngesifo sezinso, ukukhulelwa noma ukuncelisa, nawo WONKE amanye amaphilisi.",
      "Qala ngokushesha njengomyalelo ngemva kwezimpawu ze-influenza noma ukuchayeka uma kunqunyiwe.",
      "Buza ukuthi wenzani uma uhlanza umthamo nokuthi yiziphi izimpawu ezidinga ukuhlolwa ngokushesha.",
      "Uma ukuphefumula kuba kubi, ukudideka, noma ungakwazi ukugcina uketshezi — funa usizo; izinkinga ze-influenza zidinga ukuhlolwa.",
    ],
    [
      "Oseltamivir is 'n neuraminidase-inhibeerder in geselekteerde griepbehandeling- of voorkomingspaaie.",
      "Materia versin nie 'n beginvenster of nieraanpassing nie — bevestig teen die geëtiketteerde produk en huidige SA STG/EML.",
      "Sê vir jou apteker van niersiekte, swangerskap of borsvoeding, en ALLE ander medisyne.",
      "Begin so gou as aangedui ná griepsimptome of blootstelling wanneer voorgeskryf.",
      "Vra wat om te doen as jy 'n dosis braak en watter waarskuwingssimptome dringende hersiening beteken.",
      "As asemhaling versleg, verwarring, of jy nie vloeistowwe kan hou nie — soek dringende sorg.",
    ],
    [
      "Oseltamivir ke neuraminidase inhibitor e sebelisoang litseleng tse khethiloeng tsa kalafo kapa thibelo ea influenza.",
      "Materia ha e iqape window ea ho qala kapa tokiso ea liphio — netefatsa khahlanong le sehlahisoa se nang le ileibole le STG/EML.",
      "Bolella chemist ka lefu la liphio, bokhachane kapa ho anyesa, le MERIANA EOHLE e meng.",
      "Qala kapele joalo ka tataiso ka mor'a matšoao a influenza kapa ho pepesoha haeba e ngoliloe.",
      "Botsoa hore na u etsa eng haeba u hlatsa tekanyo le hore na ke matšoao afe a hlokang tlhahlobo ea potlako.",
      "Haeba ho hema ho mpefala, ho ferekana, kapa u sitoa ho boloka mokelikeli — batla thuso.",
    ],
    [
      "I-oseltamivir yi-neuraminidase inhibitor esetyenziswa kwiindlela ezikhethiweyo zonyango okanye zothintelo lwe-influenza.",
      "I-Materia ayiyiqiqi ifestile yokuqala okanye uhlengahlengiso lwezintso — Qinisekisa nemveliso enelebula kunye ne-STG/EML.",
      "Xelela usokhemisi ngesifo sezintso, ukukhulelwa okanye ukuncancisa, nawo WONKE amanye amayeza.",
      "Qala ngokukhawuleza njengomyalelo emva kweempawu ze-influenza okanye ukuchayeka xa kumiselwe.",
      "Buza ukuba wenza ntoni ukuba ugabha idosi nokuba zeziphi iimpawu ezifuna uphononongo ngokukhawuleza.",
      "Ukuba ukuphefumla kuya kuba kubi, ukudideka, okanye awukwazi ukugcina ulwelo — funa uncedo.",
    ],
  ),

  "mol-misoprostol": five(
    [
      "Misoprostol is a prostaglandin analogue used in obstetric and selected GI-protection contexts — indication and route completely change counselling.",
      "Materia does not invent a dose or route regimen — confirm the clinical pathway against current SA STG/EML and the labelled product.",
      "Tell clinicians if you are pregnant or could be pregnant before any non-obstetric use, and list ALL other medicines.",
      "Do not use leftover tablets for a different indication without clinical advice — wrong use can be dangerous.",
      "Ask which indication you are being treated for and what bleeding or pain symptoms should trigger urgent return.",
      "If heavy bleeding, severe pain, fainting, or fever after obstetric use develops — seek emergency care immediately.",
    ],
    [
      "I-misoprostol i-prostaglandin analogue esetshenziswa ezimo zezokubeletha nasezindleleni ezikhethiwe zokuvikela isisu — isidingo nendlela kuguqula ukweluleka.",
      "I-Materia ayiqambi umthamo noma uhlelo lwendlela — qinisekisa indlela yokwelapha ne-STG/EML nomkhiqizo onelebula.",
      "Tshela odokotela uma ukhulelwe noma ungakhulelwa ngaphambi kokusetshenziswa okungezona ezokubeletha, futhi ubale WONKE amanye amaphilisi.",
      "Ungasebenzisi amaphilisi asele ngesidingo esihlukile ngaphandle kweseluleko — ukusetshenziswa okungalungile kuyingozi.",
      "Buza ukuthi yisiphi isidingo oselashwa ngaso nokuthi yiziphi izimpawu zokopha noma zobuhlungu ezidinga ukubuya ngokushesha.",
      "Uma ukopha okukhulu, ubuhlungu obukhulu, ukuwa, noma umkhuhlane ngemva kokusetshenziswa kwezokubeletha — funa usizo oluphuthumayo.",
    ],
    [
      "Misoprostol is 'n prostaglandienanaloog in verloskunde- en geselekteerde GI-beskermingskontekste — indikasie en roete verander berading heeltemal.",
      "Materia versin nie 'n dosis of roeteregimen nie — bevestig die kliniese pad teen huidige SA STG/EML en die geëtiketteerde produk.",
      "Sê vir klinici as jy swanger is of kan wees vóór enige nie-verloskundige gebruik, en lys ALLE ander medisyne.",
      "Moenie oorblywende tablette vir 'n ander indikasie sonder advies gebruik nie — verkeerde gebruik kan gevaarlik wees.",
      "Vra vir watter indikasie jy behandel word en watter bloeding- of pynsimptome dringende terugkeer moet sneller.",
      "As swaar bloeding, ernstige pyn, floute, of koors ná verloskundige gebruik ontwikkel — soek onmiddellik noodhulp.",
    ],
    [
      "Misoprostol ke prostaglandin analogue e sebelisoang maemong a obstetric le a tšireletso ea GI a khethiloeng — tšebeliso le tsela li fetola keletso ka ho feletseng.",
      "Materia ha e iqape tekanyo kapa moralo oa tsela — netefatsa tsela ea kalafo khahlanong le STG/EML le sehlahisoa se nang le ileibole.",
      "Bolella lingaka haeba u mokhachane kapa u ka 'na ua ba pele ho tšebeliso e seng ea obstetric, 'me u thathamise MERIANA EOHLE e meng.",
      "U se ke ua sebelisa lipilisi tse setseng bakeng sa tšebeliso e fapaneng ntle le keletso — tšebeliso e fosahetseng e ka ba kotsi.",
      "Botsoa hore na ke tšebeliso efe eo u e alafsoang le hore na ke matšoao afe a ho tsoa mali kapa bohloko a tlamehang ho baka ho khutla ka potlako.",
      "Haeba ho tsoa mali ho matla, bohloko bo matla, ho oa, kapa feberu ka mor'a tšebeliso ea obstetric — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-misoprostol yi-prostaglandin analogue esetyenziswa kwiimeko zezobeletho nakwiindlela ezikhethiweyo zokukhusela isisu — ukusetyenziswa kunye nendlela kuguqula ukucebisa ngokupheleleyo.",
      "I-Materia ayiyiqiqi idosi okanye inkqubo yendlela — Qinisekisa indlela yonyango ne-STG/EML kunye nemveliso enelebula.",
      "Xelela oogqirha ukuba ukhulelwe okanye ungakhulelwa phambi kokusetyenziswa okungeyiyo ezobeletho, kwaye ubale ONKE amanye amayeza.",
      "Ungasebenzisi iipilisi ezisele ngesizathu esahlukileyo ngaphandle kwengcebiso — ukusetyenziswa gwenxa kuyingozi.",
      "Buza ukuba sesiphi isizathu osinyangelwa ngaso nokuba zeziphi iimpawu zokopha okanye zentlungu ezifuna ukubuya ngokukhawuleza.",
      "Ukuba ukopha okuninzi, intlungu enzima, ukuwa, okanye umkhuhlane emva kokusetyenziswa kwezobeletho — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),
};
