/**
 * v385–v403 deepened SA counselling batch (6 lines × 5 langs) — STG/EML Paediatric Batches H–I.
 * Original Materia educational scripts only —
 * no invented mg/kg doses, mcg/kg/min rates, gram doses, microgram doses, sachet doses, or mmol/kg regimens.
 * Types kept local to avoid circular import with counselling.ts.
 */

export type ExtLang = "en" | "zu" | "af" | "st" | "xh";

export interface ExtScript {
  lang: ExtLang;
  lines: string[];
  sourceNote: string;
  publishState: "published" | "draft";
}

const EN_NOTE = "Materia original counselling — founder-reviewed educational layer";
const ZU_NOTE = "Materia original isiZulu counselling — founder-reviewed educational layer";
const AF_NOTE = "Materia original Afrikaans counselling — founder-reviewed educational layer";
const ST_NOTE = "Materia original Sesotho counselling — founder-reviewed educational layer";
const XH_NOTE = "Materia original isiXhosa counselling — founder-reviewed educational layer";

function five(
  en: string[],
  zu: string[],
  af: string[],
  st: string[],
  xh: string[],
): Partial<Record<ExtLang, ExtScript>> {
  return {
    en: { lang: "en", publishState: "published", sourceNote: EN_NOTE, lines: en },
    zu: { lang: "zu", publishState: "published", sourceNote: ZU_NOTE, lines: zu },
    af: { lang: "af", publishState: "published", sourceNote: AF_NOTE, lines: af },
    st: { lang: "st", publishState: "published", sourceNote: ST_NOTE, lines: st },
    xh: { lang: "xh", publishState: "published", sourceNote: XH_NOTE, lines: xh },
  };
}

export const COUNSELLING_V385_TO_V403: Record<string, Partial<Record<ExtLang, ExtScript>>> = {
  "mol-propranolol": five(
    [
      "Propranolol is a beta-blocker used in selected paediatric heart-rhythm, migraine, and infantile haemangioma pathways — hospital or specialist oversight is typical.",
      "Materia does not invent a mg/kg dose or titration schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about asthma, low blood pressure, heart rhythm concerns, and ALL other medicines the child receives.",
      "Caregivers: ask what heart-rate or blood-pressure checks are planned and what unusual tiredness or wheeze should trigger review.",
      "This informs professional judgement — do not change or stop a beta-blocker without the prescribing team.",
      "If severe wheeze, fainting, markedly slow pulse, or breathing difficulty develops — seek care urgently.",
    ],
    [
      "I-propranolol i-beta-blocker esetshenziswa ezindleleni ezikhethiwe zesigqi senhliziyo, i-migraine, ne-infantile haemangioma ezinganeni — ukuqapha esibhedlela noma ochwepheshe kujwayelekile.",
      "I-Materia ayiqambi umthamo we-mg/kg noma uhlelo lokukhuphula — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba nge-asthma, ukushaya kwamandla egazi okuphansi, izinkinga zesigqi senhliziyo, nawo WONKE amanye amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwesivinini senhliziyo noma kwamandla egazi okucwangisiwe nokuthi ukukhathala okungajwayelekile noma ukuhema kufanele kuqale ukubuyekezwa.",
      "Lokhu kuchaza isigqi — ungashintshi noma umise i-beta-blocker ngaphandle kwethimba elibhalisile.",
      "Uma ukuhema okukhulu, ukuwa, ukushaya kwenhliziyo okuphansi kakhulu, noma ubunzima bokuphefumula kuvela — funa usizo ngokushesha.",
    ],
    [
      "Propranolol is 'n beta-blokker in geselekteerde pediatriese hartritme-, migreen- en infantiele hemangioom-paaie — hospitaal- of spesialistoesig is tipies.",
      "Materia versin nie 'n mg/kg dosis of titrasieskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van asma, lae bloeddruk, hartritme kommer, en ALLE ander medisyne wat die kind ontvang.",
      "Versorgers: vra watter hartklop- of bloeddruktoetse beplan is en watter ongewone moegheid of piepende asem hersiening moet sneller.",
      "Dit informeer professionele oordeel — moenie 'n beta-blokker verander of stop sonder die voorskriwende span nie.",
      "As ernstige piepende asem, floute, merkbaar stadige pols, of asemnood ontwikkel — soek dringend sorg.",
    ],
    [
      "Propranolol ke beta-blocker e sebelisoang litseleng tse khethiloeng tsa morethetho oa pelo, migraine, le infantile haemangioma ho bana — tlhokomelo ea sepetlele kapa setsebi e tloaelehile.",
      "Materia ha e iqape tekanyo ea mg/kg kapa kemiso ea ho khupisa — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka asthma, khatello e tlase ea mali, mathata a morethetho oa pelo, le MERIANA EOHLE e meng eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa ho otla ha pelo kapa khatello ea mali tse reriloeng le hore na mokhathala o sa tloaelehang kapa ho hema ka thata ho lokela ho qala tlhahlobo.",
      "Sena se tsebisa tsebo ea bongaka — u se ke ua fetola kapa ua emisa beta-blocker ntle le sehlopha se ngolisitseng.",
      "Haeba ho hema ho matla, ho wa, ho otla ha pelo ho fokotsehileng haholo, kapa ho hema thata ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-propranolol yi-beta-blocker esetyenziswa kwiindlela ezikhethiweyo zesingqisho sentliziyo, i-migraine, kunye ne-infantile haemangioma kubantwana — ukujongwa esibhedlele okanye ngogcisa kuqhelekile.",
      "I-Materia ayiyiqiqi idosi ye-mg/kg okanye ishedyuli yokukhuphula — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela nge-asthma, uxinzelelo lwegazi oluphantsi, iingxaki zesingqisho sentliziyo, kunye NAWO ONKE amanye amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zesantya sentliziyo okanye uxinzelelo lwegazi ezicwangcisiweyo nokuba ukudinwa okungaqhelekanga okanye ukuphefumla nzima kufuneka kuqalise ukujongwa.",
      "Oku kuchaza ingqiqo yobungcali — ungatshintshi okanye umisi i-beta-blocker ngaphandle kweqela elibhalisileyo.",
      "Ukuba ukuphefumla nzima, ukuwa, ukubetha kwentliziyo okuphantsi kakhulu, okanye ubunzima bokuphefumla kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-captopril": five(
    [
      "Captopril is an ACE inhibitor used in selected paediatric heart-failure and hypertension pathways — kidney function and potassium monitoring matter.",
      "Materia does not invent a mg/kg dose — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about kidney disease, dehydration, pregnancy concerns in adolescents, and ALL other medicines including NSAIDs.",
      "Caregivers: ask what blood-pressure and kidney checks are planned and what persistent cough or facial swelling should trigger review.",
      "Do not invent salt-restriction rules — follow the clinician and dietitian plan for the child.",
      "If facial or lip swelling, severe dizziness, reduced urine, or breathing difficulty develops — seek emergency care immediately.",
    ],
    [
      "I-captopril i-ACE inhibitor esetshenziswa ezindleleni ezikhethiwe zokwehluleka kwenhliziyo nokushaya kwamandla egazi ezinganeni — ukusebenza kwezinso nokuqapha i-potassium kubalulekile.",
      "I-Materia ayiqambi umthamo we-mg/kg — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngesifo sezinso, ukoma, ukukhulelwa kwezentsha, nawo WONKE amanye amaphilisi kufaka ne-NSAIDs.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwamandla egazi nezinso okucwangisiwe nokuthi ukhwehlela okuqhubekayo noma ukuvuvuka kobuso kufanele kuqale ukubuyekezwa.",
      "Ungacabangi imithetho yokunciphisa usawoti — landela uhlelo lukadokotela nodietitian lomntwana.",
      "Uma ukuvuvuka kobuso noma izindebe, isiyezi esikhulu, umchamo omncane, noma ubunzima bokuphefumula kuvela — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Kaptopril is 'n ACE-inhibeerder in geselekteerde pediatriese hartversaking- en hipertensiepaaie — niersfunksie en kalium monitering maak saak.",
      "Materia versin nie 'n mg/kg dosis nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van niersiekte, dehidrasie, swangerskapkommer by adolessente, en ALLE ander medisyne insluitend NSAIDs.",
      "Versorgers: vra watter bloeddruk- en niertoetse beplan is en watter aanhoudende hoes of gesigswelling hersiening moet sneller.",
      "Moenie soutbeperkingsreëls versin nie — volg die klinikus- en dieetkundigeplan vir die kind.",
      "As gesig- of lipswelling, ernstige duiseligheid, verminderde urine, of asemnood ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Captopril ke ACE inhibitor e sebelisoang litseleng tse khethiloeng tsa ho hloleha ha pelo le khatello ea mali ho bana — ts'ebetso ea liphio le tlhokomelo ea potassium li bohlokoa.",
      "Materia ha e iqape tekanyo ea mg/kg — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka lefu la liphio, ho omella, mathata a bokhachane ho bacha, le MERIANA EOHLE e meng ho kenyeletsoa li-NSAIDs.",
      "Bahlokomeli: botsa hore na ke liteko life tsa khatello ea mali le liphio tse reriloeng le hore na ho khwehla ho tsoelang pele kapa ho ruruha ha sefahleho ho lokela ho qala tlhahlobo.",
      "U se ke ua iqapa melao ea ho fokotsa lets'i — latela moralo oa ngaka le dietitian bakeng sa ngoana.",
      "Haeba ho ruruha ha sefahleho kapa melomo, ho tsekela ho matla, moroto o fokotsehileng, kapa ho hema thata ho hlaha — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-captopril yi-ACE inhibitor esetyenziswa kwiindlela ezikhethiweyo zokusilela kwentliziyo kunye noxinzelelo lwegazi kubantwana — ukusebenza kwezintso nokujonga i-potassium kubalulekile.",
      "I-Materia ayiyiqiqi idosi ye-mg/kg — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngesifo sezintso, ukoma, iinkxalabo zokukhulelwa kulutsha, kunye NAWO ONKE amanye amayeza kuquka ii-NSAIDs.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zoxinzelelo lwegazi nezintso ezicwangcisiweyo nokuba ukukhwehla okuqhubekayo okanye ukudumba kobuso kufuneka kuqalise ukujongwa.",
      "Ungacingi imithetho yokunciphisa utywala — landela isicwangciso sogqirha kunye nedietitian yomntwana.",
      "Ukuba ukudumba kobuso okanye imilebe, isiyezi esikhulu, umchamo omncinci, okanye ubunzima bokuphefumla kuvela — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-clonazepam": five(
    [
      "Clonazepam is a benzodiazepine used in selected paediatric seizure and movement-disorder pathways — specialist prescribing and taper plans apply.",
      "Materia does not invent a mg/kg dose or taper schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about breathing problems, liver disease, other sedating medicines, and ALL medicines the child receives.",
      "Caregivers: ask what seizure diary or safety plan applies and what excessive sleepiness or new unsteadiness should trigger review.",
      "Do not stop suddenly without a clinician taper plan — withdrawal can worsen seizures.",
      "If prolonged seizure, breathing stops, blue lips, or cannot wake the child — seek emergency care immediately.",
    ],
    [
      "I-clonazepam i-benzodiazepine esetshenziswa ezindleleni ezikhethiwe zokuxega nezinkinga zokunyakaza ezinganeni — ukubhaliswa kochwepheshe nohlelo lokwehlisa kuyadingeka.",
      "I-Materia ayiqambi umthamo we-mg/kg noma uhlelo lokwehlisa — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngezinkinga zokuphefumula, isifo sesibindi, amanye amaphilisi okulala, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yisiphi isincwadi sokuxega noma uhlelo lokuphepha olusebenza nokuthi ukulala okweqile noma ukungazinzi okusha kufanele kuqale ukubuyekezwa.",
      "Ungayeki ngokuzumayo ngaphandle kohlelo lokwehlisa lukadokotela — ukuhoxa kungenza ukuxega kube kubi.",
      "Uma ukuxega okude, ukuphefumula kumisa, izindebe eziluhlaza, noma ungavuki umntwana — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Klonazepam is 'n benzodiazepien in geselekteerde pediatriese aanval- en bewegingsversteuringspaaie — spesialistvoorskrywing en aftrapplanne geld.",
      "Materia versin nie 'n mg/kg dosis of aftrapskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van asemhalingsprobleme, lewersiekte, ander kalmerende medisyne, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter aanvaldagboek of veiligheidsplan geld en watter oormatige slaapiness of nuwe onbestendigheid hersiening moet sneller.",
      "Moenie skielik stop sonder 'n klinikus aftrapplan nie — onttrekking kan aanvalle verser.",
      "As langdurige aanval, asemhaling stop, blou lippe, of kan nie die kind wakker maak nie — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Clonazepam ke benzodiazepine e sebelisoang litseleng tse khethiloeng tsa ho thothomela le mathata a tsamaiso ho bana — ho ngolisa ha setsebi le mananeo a ho fokotsa a sebetsa.",
      "Materia ha e iqape tekanyo ea mg/kg kapa kemiso ea ho fokotsa — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka mathata a ho hema, lefu la sebete, meriana e ling e khutsitseng, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke buka efe ea ho thothomela kapa moralo oa tšireletso o sebetsang le hore na ho robala haholo kapa ho tsitsa ha bocha ho lokela ho qala tlhahlobo.",
      "U se ke ua emisa ka tšohanyetso ntle le moralo oa ho fokotsa oa ngaka — ho hoa ho ka mpefatsa ho thothomela.",
      "Haeba ho thothomela ho letele, ho hema ho ema, melomo e putsoa, kapa u sa ka ua tsosa ngoana — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-clonazepam yi-benzodiazepine esetyenziswa kwiindlela ezikhethiweyo zokuxhuzula kunye neengxaki zokunyakaza kubantwana — ukubhaliswa ngogcisa kunye nezicwangciso zokunciphisa ziyasebenza.",
      "I-Materia ayiyiqiqi idosi ye-mg/kg okanye ishedyuli yokunciphisa — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngeengxaki zokuphefumla, isifo sesibindi, amanye amayeza okulala, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba yeyiphi incwadi yokuxhuzula okanye isicwangciso sokhuseleko esisebenzayo nokuba ukulala ngokweqile okanye ukungazinzi okutsha kufuneka kuqalise ukujongwa.",
      "Ungayeki ngequbuliso ngaphandle kwesicwangciso sokunciphisa sogqirha — ukurhoxa kunokwenza ukuxhuzula kuba mbi.",
      "Ukuba ukuxhuzula okude, ukuphefumla kuyeka, imilebe eziluhlaza, okanye awunakuvusa umntwana — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-methylphenidate": five(
    [
      "Methylphenidate is a stimulant used in selected paediatric ADHD pathways — formulation, timing, and growth monitoring are clinician-led.",
      "Materia does not invent a dose or formulation switch rule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the clinician about heart problems, tics, anxiety, other stimulants, and ALL medicines the child receives.",
      "Caregivers: ask what school-day timing applies, what appetite or sleep changes are expected, and when to review growth.",
      "This is not a study aid to share — use only as prescribed for the named child.",
      "If chest pain, fainting, severe mood change, or hallucinations develop — seek care urgently.",
    ],
    [
      "I-methylphenidate i-stimulant esetshenziswa ezindleleni ezikhethiwe ze-ADHD ezinganeni — uhlobo, isikhathi, nokuqapha ukukhula kuqhutshwa odokotela.",
      "I-Materia ayiqambi umthamo noma umthetho wokushintsha uhlobo — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngezinkinga zenhliziyo, ama-tics, ukukhathazeka, amanye ama-stimulant, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yisiphi isikhathi sosuku lwesikole esisebenza, yiziphi izinguquko zokudla noma zokulala ezilindelekile, nokuthi ukukhula kubuyekezwa nini.",
      "Lokhu akuyona insiza yokufunda yokwabelana — sebenzisa kuphela njengoba kubhalwe lomntwana.",
      "Uma ubuhlungu besifuba, ukuwa, ukushintsha kwemizwa okukhulu, noma ukubona okungelona iqiniso kuvela — funa usizo ngokushesha.",
    ],
    [
      "Metilfenidaat is 'n stimulant in geselekteerde pediatriese ADHD-paaie — formulering, tydsberekening, en groeimonitering is klinikus-gelei.",
      "Materia versin nie 'n dosis of formuleringwisselreël nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van hartprobleme, tics, angs, ander stimulante, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter skooldagtydsberekening geld, watter eetlus- of slaapveranderinge verwag word, en wanneer groei hersien word.",
      "Dit is nie 'n studiehulp om te deel nie — gebruik slegs soos voorgeskryf vir die genoemde kind.",
      "As borspyn, floute, ernstige bui verandering, of hallusinasies ontwikkel — soek dringend sorg.",
    ],
    [
      "Methylphenidate ke stimulant e sebelisoang litseleng tse khethiloeng tsa ADHD ho bana — sebopeho, nako, le tlhokomelo ea ho hola li etelloa pele ke lingaka.",
      "Materia ha e iqape tekanyo kapa molao oa ho fetola sebopeho — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka mathata a pelo, li-tics, tshabo, li-stimulant tse ling, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke nako efe ea letsatsi la sekolo e sebetsang, ke liphetoho life tsa ho ja kapa ho robala tse lebelloang, le hore na ho hola ho hlahloboa neng.",
      "Sena ha se thuso ea ho ithuta ea ho arolelana — sebelisa feela joalo ka ha e ngoliloe bakeng sa ngoana ea bitsoang.",
      "Haeba bohloko ba sefubeng, ho wa, phetoho e matla ea maikutlo, kapa ho bona ho sa nepahaleng ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-methylphenidate yi-stimulant esetyenziswa kwiindlela ezikhethiweyo ze-ADHD kubantwana — ifomu, ixesha, nokujonga ukukhula kukhokelwa ngoogqirha.",
      "I-Materia ayiyiqiqi idosi okanye umthetho wokutshintsha ifomu — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngeengxaki zentliziyo, ii-tics, ukuxhalaba, ezinye ii-stimulant, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba yeyiphi imixholo yosuku lwesikolo esebenzayo, zeziphi iinguquko zokutya okanye zokulala ezilindelekileyo, nokuba ukukhula lujongwa nini.",
      "Oku ayililo isixhobo sokufunda sokwabelana — sebenzisa kuphela njengoko kubhaliweyo kulo mntwana.",
      "Ukuba intlungu yesisu, ukuwa, utshintsho olukhulu lwemvakalelo, okanye iimbono ezingelona iqiniso kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-olanzapine": five(
    [
      "Olanzapine is an antipsychotic used in selected paediatric mental-health pathways — metabolic monitoring and weight counselling are common.",
      "Materia does not invent a dose or metabolic-monitoring schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the psychiatrist about diabetes risk, movement side effects, other sedating medicines, and ALL medicines the child receives.",
      "Caregivers: ask what blood-sugar, weight, and lipids checks are planned and what excessive sleepiness should trigger review.",
      "Do not stop suddenly without a clinician plan — relapse of psychosis can be dangerous.",
      "If severe muscle stiffness, high fever with confusion, or suicidal thoughts develop — seek emergency care immediately.",
    ],
    [
      "I-olanzapine i-antipsychotic esetshenziswa ezindleleni ezikhethiwe zempilo yengqondo ezinganeni — ukuqapha ukushintsha kwesikolo nokukhuluma ngesisindo kujwayelekile.",
      "I-Materia ayiqambi umthamo noma uhlelo lokuqapha ukushintsha kwesikolo — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela wezengqondo ngozingozi ze-diabetes, iziphumo zokunyakaza, amanye amaphilisi okulala, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwe-shukela egazini, isisindo, namafutha okucwangisiwe nokuthi ukulala okweqile kufanele kuqale ukubuyekezwa.",
      "Ungayeki ngokuzumayo ngaphandle kohlelo lukadokotela — ukubuya kwe-psychosis kungaba yingozi.",
      "Uma ukuqina kwezihlunu okukhulu, umkhuhlane omkhulu nokudideka, noma imicabango yokuzibulala kuvela — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Olanzapine is 'n antipsigotikum in geselekteerde pediatriese geestesorgpaaie — metaboliese monitering en gewigberading is algemeen.",
      "Materia versin nie 'n dosis of metaboliese moniteringskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die psigiater van diabetesrisiko, bewegingsnewe-effekte, ander kalmerende medisyne, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter bloedsuiker-, gewig-, en lipiedtoetse beplan is en watter oormatige slaapiness hersiening moet sneller.",
      "Moenie skielik stop sonder 'n klinikusplan nie — terugval van psigose kan gevaarlik wees.",
      "As ernstige spierstyfheid, hoë koors met verwarring, of selfmoordgedagtes ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Olanzapine ke antipsychotic e sebelisoang litseleng tse khethiloeng tsa bophelo ba kelello ho bana — tlhokomelo ea metabolic le keletso ea boima e tloaelehile.",
      "Materia ha e iqape tekanyo kapa kemiso ea tlhokomelo ea metabolic — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ea bokhopolo ka kotsi ea diabetes, liphetoho tsa tsamaiso, meriana e ling e khutsitseng, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa suka ea mali, boima, le lipids tse reriloeng le hore na ho robala haholo ho lokela ho qala tlhahlobo.",
      "U se ke ua emisa ka tšohanyetso ntle le moralo oa ngaka — ho khutla ha psychosis ho ka ba kotsi.",
      "Haeba ho thata ha mesifa ho matla, feberu e phahameng le ho hlakisoa, kapa maikutlo a ho ipolaea a hlaha — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-olanzapine yi-antipsychotic esetyenziswa kwiindlela ezikhethiweyo zempilo yengqondo kubantwana — ukujonga i-metabolic kunye neengcebiso zobunzima kuqhelekile.",
      "I-Materia ayiyiqiqi idosi okanye ishedyuli yokujonga i-metabolic — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha wengqondo ngomngcipheko we-diabetes, iiziphumo zokunyakaza, amanye amayeza okulala, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zikashukela egazini, ubunzima, nee-lipids ezicwangcisiweyo nokuba ukulala ngokweqile kufuneka kuqalise ukujongwa.",
      "Ungayeki ngequbuliso ngaphandle kwesicwangciso sogqirha — ukubuya kwe-psychosis kunokuba yingozi.",
      "Ukuba ukuqina kwemisipha okukhulu, umkhuhlane omkhulu kunye nodideko, okanye iingcinga zokuzibulala kuvela — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-glucagon": five(
    [
      "Glucagon is used in selected paediatric hypoglycaemia emergencies when oral glucose is not possible — it is a rescue medicine, not routine home treatment.",
      "Materia does not invent a dose or age-band kit rule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about insulin use, adrenal insufficiency, and ALL medicines that lower blood sugar.",
      "Caregivers: ask when glucagon may be given, how to recognise severe hypoglycaemia, and what follow-up blood-sugar checks are needed after use.",
      "After any rescue dose, seek clinical review — hypoglycaemia can recur once glucagon wears off.",
      "If the child does not wake, has a prolonged seizure, or breathing difficulty after hypoglycaemia — seek emergency care immediately.",
    ],
    [
      "I-glucagon isetshenziswa ezimeni ezikhethiwe zokwehluleka kwe-shukera ezinganeni lapho i-glucose yomlomo ingenakwenzeka — umuthi wokusindisa, hhayi ukwelashwa okujwayelekile ekhaya.",
      "I-Materia ayiqambi umthamo noma umthetho we-kit yobudala — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba nge-insulin, ukwehluleka kwe-adrenal, nawo WONKE amaphilisi anciphisa i-shukera.",
      "Abanakekeli: buza ukuthi i-glucagon inganikwa nini, ukubona kanjani i-hypoglycaemia emangalisayo, nokuthi yimaphi ukuhlolwa kwe-shukera okulandelayo ngemva kokusetshenziswa.",
      "Ngemva konke umthamo wokusindisa, funa ukubuyekezwa kwezokwelapha — i-hypoglycaemia ingaphinda lapho i-glucagon iphela.",
      "Uma umntwana engavuki, unokuxega okude, noma ubunzima bokuphefumula ngemva kwe-hypoglycaemia — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Glukagon word in geselekteerde pediatriese hipoglikemie-noodgevalle gebruik wanneer mondelinge glukose nie moontlik is nie — dit is 'n reddingsmiddel, nie roetine tuisbehandeling nie.",
      "Materia versin nie 'n dosis of ouderdomsband-kitreël nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van insuliengebruik, byniersinsuffisiënsie, en ALLE medisyne wat bloedsuiker verlaag.",
      "Versorgers: vra wanneer glukagon gegee mag word, hoe om ernstige hipoglikemie te herken, en watter opvolg-bloedsuikertoetse nodig is na gebruik.",
      "Na enige reddingsdosis, soek kliniese hersiening — hipoglikemie kan terugkeer wanneer glukagon uitgewerk het.",
      "As die kind nie wakker word nie, 'n langdurige aanval het, of asemnood na hipoglikemie — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Glucagon e sebelisoa maemong a khethiloeng a hypoglycaemia ea bana ha glucose ea molomo e sa khone — ke moriana oa ho pholosa, eseng kalafo ea lapeng ea kamehla.",
      "Materia ha e iqape tekanyo kapa molao oa kit ea lilemo — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka tšebeliso ea insulin, ho hloleha ha adrenal, le MERIANA EOHLE e fokotsang suka ea mali.",
      "Bahlokomeli: botsa hore na glucagon e ka fuoa neng, ho tseba joang hypoglycaemia e matla, le hore na ke liteko life tsa suka ea mali tse hlokahalang ka mor'a tšebeliso.",
      "Ka mor'a tekanyo efe kapa efe ea ho pholosa, batla tlhahlobo ea bongaka — hypoglycaemia e ka khutla ha glucagon e felile.",
      "Haeba ngoana a sa tsoge, a na le ho thothomela ho letele, kapa ho hema thata ka mor'a hypoglycaemia — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-glucagon isetyenziswa kwiimeko ezikhethiweyo ze-hypoglycaemia kubantwana xa i-glucose yomlomo ayinakwenzeka — yiyeza lokusindisa, hayi unyango oluqhelekileyo ekhaya.",
      "I-Materia ayiyiqiqi idosi okanye umthetho we-kit yobudala — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngokusetyenziswa kwe-insulin, ukusilela kwe-adrenal, kunye NAWO ONKE amayeza anciphisa ikashukela.",
      "Abakhathaleli: buza ukuba i-glucagon inokunikwa nini, ukubona njani i-hypoglycaemia enzima, nokuba zeziphi iimvavanyo zikashukela ezilandelayo ezifunekayo emva kokusetyenziswa.",
      "Emva nayiphi na idosi yosindiso, funa ukujongwa kwezonyango — i-hypoglycaemia inokubuya xa i-glucagon iphelile.",
      "Ukuba umntwana akavuki, unokuxhuzula okude, okanye ubunzima bokuphefumla emva kwe-hypoglycaemia — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-mannitol": five(
    [
      "Mannitol is an osmotic diuretic used in selected paediatric raised-intracranial-pressure pathways — ICU or neurosurgical oversight is typical.",
      "Materia does not invent a gram dose or osmolarity threshold — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about kidney disease, heart failure, dehydration, and ALL fluids and medicines the child receives.",
      "Caregivers: ask what urine output and electrolyte checks are planned and what headache or reduced consciousness should trigger review.",
      "Do not invent home diuretic use — mannitol stays under critical-care supervision.",
      "If reduced urine, severe headache with vomiting, or worsening confusion develops — seek care urgently.",
    ],
    [
      "I-mannitol i-osmotic diuretic esetshenziswa ezindleleni ezikhethiwe zokuphakama kwengcindezi yangaphakathi kweskhulu ezinganeni — ukuqapha kwe-ICU noma i-neurosurgery kujwayelekile.",
      "I-Materia ayiqambi umthamo we-gram noma umgomo we-osmolarity — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngesifo sezinso, ukwehluleka kwenhliziyo, ukoma, nawo WONKE amanzi namaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa komchamo nezinto ze-electrolyte okucwangisiwe nokuthi ikhanda elibuhlungu noma ukucitshwa kwemiqondo kufanele kuqale ukubuyekezwa.",
      "Ungacabangi ukusetshenziswa kwe-diuretic ekhaya — i-mannitol ihlala ngaphansi kokuqapha kwe-critical care.",
      "Uma umchamo omncane, ikhanda elibuhlungu elikhulu nokuhlanza, noma ukudideka okuya emuva kuvela — funa usizo ngokushesha.",
    ],
    [
      "Mannitol is 'n osmotiese diuretikum in geselekteerde pediatriese verhoogde-intrakraniale-druk-paaie — ICU- of neurochirurgiese toesig is tipies.",
      "Materia versin nie 'n gram dosis of osmolarietiedrempel nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van niersiekte, hartversaking, dehidrasie, en ALLE vloeistowwe en medisyne wat die kind ontvang.",
      "Versorgers: vra watter urine-uitset en elektroliettoetse beplan is en watter hoofpyn of verminderde bewustheid hersiening moet sneller.",
      "Moenie tuis-diuretikumgebruik versin nie — mannitol bly onder kritieke-sorg toesig.",
      "As verminderde urine, ernstige hoofpyn met braking, of verslechterende verwarring ontwikkel — soek dringend sorg.",
    ],
    [
      "Mannitol ke diuretic ea osmotic e sebelisoang litseleng tse khethiloeng tsa ho phahama ha khatello ea ka hare ho bana — tlhokomelo ea ICU kapa neurosurgery e tloaelehile.",
      "Materia ha e iqape tekanyo ea gram kapa moelo oa osmolarity — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka lefu la liphio, ho hloleha ha pelo, ho omella, le MELA EOHLE le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa moroto le electrolyte tse reriloeng le hore na ho opa ha hlooho kapa ho fokotseha ha tsebo ho lokela ho qala tlhahlobo.",
      "U se ke ua iqape tšebeliso ea diuretic ea lapeng — mannitol e sala tlas'a tlhokomelo ea critical care.",
      "Haeba moroto o fokotsehileng, ho opa ha hlooho ho matla le ho hlatsa, kapa ho hlakisoa ho mpefala ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-mannitol yi-osmotic diuretic esetyenziswa kwiindlela ezikhethiweyo zoxinzelelo oluphakamileyo lwangaphakathi kweskhulu kubantwana — ukujongwa kwe-ICU okanye ye-neurosurgery kuqhelekile.",
      "I-Materia ayiyiqiqi idosi ye-gram okanye umgama we-osmolarity — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngesifo sezintso, ukusilela kwentliziyo, ukoma, kunye NAWO ONKE iilwelo namayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zomchamo nee-electrolyte ezicwangcisiweyo nokuba intloko ebuhlungu okanye ukucitshwa kwengqondo kufuneka kuqalise ukujongwa.",
      "Ungacingi ukusetyenziswa kwe-diuretic ekhaya — i-mannitol ihlala phantsi kokujongwa kwe-critical care.",
      "Ukuba umchamo omncinci, intloko ebuhlungu enkulu kunye nokugabha, okanye ukudideka okuya emva kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-calcitriol": five(
    [
      "Calcitriol is active vitamin D used in selected paediatric renal and bone pathways — calcium and phosphate monitoring are clinician-led.",
      "Materia does not invent a microgram dose — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about kidney disease, other vitamin D products, thiazide diuretics, and ALL medicines the child receives.",
      "Caregivers: ask what calcium, phosphate, and kidney checks are planned and what vomiting or unusual tiredness should trigger review.",
      "Do not add over-the-counter vitamin D without the renal team — toxicity risk rises with overlap.",
      "If severe vomiting, confusion, reduced urine, or muscle weakness develops — seek care urgently.",
    ],
    [
      "I-calcitriol i-vitamin D esebenzayo esetshenziswa ezindleleni ezikhethiwe zezinso namathambo ezinganeni — ukuqapha i-calcium ne-phosphate kuqhutshwa odokotela.",
      "I-Materia ayiqambi umthamo we-microgram — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngesifo sezinso, amanye amikhiqizo e-vitamin D, ama-thiazide diuretic, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwe-calcium, i-phosphate, nezinso okucwangisiwe nokuthi ukuhlanza noma ukukhathala okungajwayelekile kufanele kuqale ukubuyekezwa.",
      "Ungangezi i-vitamin D ethengwayo ngaphandle kwethimba lezinso — ubungozi bokuthi kudlule kukhula ngokuphindaphinda.",
      "Uma ukuhlanza okukhulu, ukudideka, umchamo omncane, noma ubuthakathaka bezihlunu kuvela — funa usizo ngokushesha.",
    ],
    [
      "Kalsitriol is aktiewe vitamien D in geselekteerde pediatriese niere- en beenpaaie — kalsium- en fosfaatmonitering is klinikus-gelei.",
      "Materia versin nie 'n microgram dosis nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van niersiekte, ander vitamien D produkte, tiasied diuretika, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter kalsium-, fosfaat-, en niertoetse beplan is en watter braking of ongewone moegheid hersiening moet sneller.",
      "Moenie oor-die-toonbank vitamien D byvoeg sonder die nierspan nie — toksisiteit risiko styg met oorvleueling.",
      "As ernstige braking, verwarring, verminderde urine, of spierswakheid ontwikkel — soek dringend sorg.",
    ],
    [
      "Calcitriol ke vitamin D e sebetsang e sebelisoang litseleng tse khethiloeng tsa liphio le likholo ho bana — tlhokomelo ea calcium le phosphate e etelloa pele ke lingaka.",
      "Materia ha e iqape tekanyo ea microgram — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka lefu la liphio, lihlahisoa tse ling tsa vitamin D, li-thiazide diuretic, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa calcium, phosphate, le liphio tse reriloeng le hore na ho hlatsa kapa mokhathala o sa tloaelehang o lokela ho qala tlhahlobo.",
      "U se ke ua eketsa vitamin D e rekisoang ntle le sehlopha sa liphio — kotsi ea ho fetela tekanyong e eketseha ha li kopana.",
      "Haeba ho hlatsa ho matla, ho hlakisoa, moroto o fokotsehileng, kapa ho fokotsa ha mesifa ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-calcitriol yivitamin D esebenzayo esetyenziswa kwiindlela ezikhethiweyo zezintso namathambo kubantwana — ukujonga i-calcium ne-phosphate kukhokelwa ngoogqirha.",
      "I-Materia ayiyiqiqi idosi ye-microgram — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngesifo sezintso, ezinye iimveliso ze-vitamin D, ii-thiazide diuretic, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo ze-calcium, i-phosphate, nezintso ezicwangcisiweyo nokuba ukugabha okanye ukudinwa okungaqhelekanga kufuneka kuqalise ukujongwa.",
      "Ungongeze i-vitamin D ethengwayo ngaphandle kweqela lezintso — umngcipheko wokudlula kukhula ukhula ngokuphindaphinda.",
      "Ukuba ukugabha okukhulu, ukudideka, umchamo omncinci, okanye ubuthathaka bemisipha kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-aminophylline": five(
    [
      "Aminophylline is a methylxanthine used in selected paediatric asthma and apnoea pathways — serum-level monitoring may apply in hospital.",
      "Materia does not invent a loading dose or serum-level target — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about heart rhythm concerns, seizures, other methylxanthines including caffeine, and ALL medicines the child receives.",
      "Caregivers: ask what monitoring is planned during IV use and what vomiting, tremor, or fast heart rate should trigger review.",
      "Do not invent home IV or infusion schedules — aminophylline stays under clinical oversight.",
      "If persistent vomiting, seizures, chest pain, or breathing worsens despite treatment — seek emergency care immediately.",
    ],
    [
      "I-aminophylline i-methylxanthine esetshenziswa ezindleleni ezikhethiwe ze-asthma ne-apnoea ezinganeni — ukuqapha amazinga egazi kungasebenza esibhedlela.",
      "I-Materia ayiqambi umthamo wokuqala noma umgomo wezinga legazi — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngezinkinga zesigqi senhliziyo, ukuxega, amanye ama-methylxanthine kufaka ne-caffeine, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yiluphi ukuqapha okucwangisiwe ngesikhathi sokusetshenziswa kwe-IV nokuthi ukuhlanza, ukuthuthumela, noma isivinini senhliziyo esikhulu kufanele kuqale ukubuyekezwa.",
      "Ungacabangi izinhlelo ze-IV noma zokufaka emithanjeni zasekhaya — i-aminophylline ihlala ngaphansi kokuqapha kwezokwelapha.",
      "Uma ukuhlanza okuqhubekayo, ukuxega, ubuhlungu besifuba, noma ukuphefumula kuba kubi naphezu kokwelashwa — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Aminofillien is 'n metielxantien in geselekteerde pediatriese asma- en apnee-paaie — serumvlakmonitering kan in hospitaal geld.",
      "Materia versin nie 'n laaidosis of serumvlakteiken nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van hartritme kommer, aanvalle, ander metielxantiene insluitend kafeïen, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter monitering beplan is tydens IV gebruik en watter braking, bewing, of vinnige hartklop hersiening moet sneller.",
      "Moenie tuis-IV of infusieskedules versin nie — aminofillien bly onder kliniese toesig.",
      "As aanhoudende braking, aanvalle, borspyn, of asemhaling versleg ondanks behandeling — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Aminophylline ke methylxanthine e sebelisoang litseleng tse khethiloeng tsa asthma le apnoea ho bana — tlhokomelo ea maemo a mali e ka sebetsa sepetlele.",
      "Materia ha e iqape tekanyo ea ho qala kapa sepheo sa boemo ba mali — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka mathata a morethetho oa pelo, ho thothomela, li-methylxanthine tse ling ho kenyeletsoa caffeine, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke tlhokomelo efe e reriloeng nakong ea tšebeliso ea IV le hore na ho hlatsa, ho thothomela, kapa ho otla ha pelo ka potlako ho lokela ho qala tlhahlobo.",
      "U se ke ua iqapa kemiso ea IV kapa infusion ea lapeng — aminophylline e sala tlas'a tlhokomelo ea bongaka.",
      "Haeba ho hlatsa ho tsoelang pele, ho thothomela, bohloko ba sefubeng, kapa ho hema ho mpefala le ha ho phekolo — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-aminophylline yi-methylxanthine esetyenziswa kwiindlela ezikhethiweyo ze-asthma ne-apnoea kubantwana — ukujonga amanqanaba egazi kunokusebenza esibhedlele.",
      "I-Materia ayiyiqiqi idosi yokuqala okanye usukelo lwenqanaba legazi — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngeengxaki zesingqisho sentliziyo, ukuxhuzula, ezinye ii-methylxanthine kuquka i-caffeine, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba luphi na ukujonga olucwangcisiweyo ngexesha lokusetyenziswa kwe-IV nokuba ukugabha, ukungcangcazela, okanye isantya sentliziyo esikhulu kufuneka kuqalise ukujongwa.",
      "Ungacingi iishedyuli ze-IV okanye zokugalela zasekhaya — i-aminophylline ihlala phantsi kokujonga kwezonyango.",
      "Ukuba ukugabha okuqhubekayo, ukuxhuzula, intlungu yesifuba, okanye ukuphefumla kuba mbi naphezu kolunyango — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-dopamine": five(
    [
      "Dopamine is a catecholamine vasopressor used in selected paediatric shock pathways — ICU infusion with continuous monitoring is required.",
      "Materia does not invent a mcg/kg/min infusion rate — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the ICU team about heart rhythm concerns, pheochromocytoma history if known, and ALL medicines and fluids running.",
      "Caregivers: ask what blood-pressure and urine-output targets the team is watching and what limb colour changes should trigger review.",
      "Do not invent home infusion use — dopamine stays in critical care only.",
      "If limb becomes cold and mottled, chest pain, or breathing worsens on the infusion — alert the ICU team immediately.",
    ],
    [
      "I-dopamine i-catecholamine vasopressor esetshenziswa ezindleleni ezikhethiwe zokumelana ne-shock ezinganeni — ukufaka emithanjeni kwe-ICU nokuqapha okuqhubekayo kuyadingeka.",
      "I-Materia ayiqambi izinga lokufaka le-mcg/kg/min — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba le-ICU ngezinkinga zesigqi senhliziyo, umlando we-pheochromocytoma uma waziwa, nawo WONKE amaphilisi namanzi ayagijima.",
      "Abanakekeli: buza ukuthi yimaphi ama-target okushaya kwamandla egazi nomchamo ithimba eliwabheka nokuthi ukushintsha kombala kwezihlunu kufanele kuqale ukubuyekezwa.",
      "Ungacabangi ukusetshenziswa kokufaka emithanjeni ekhaya — i-dopamine ihlala ku-critical care kuphela.",
      "Uma isihlunu siba sibanda futhi sinesimo, ubuhlungu besifuba, noma ukuphefumula kuba kubi ngesikhathi sokufaka — xwayisa ithimba le-ICU ngokushesha.",
    ],
    [
      "Dopamien is 'n katekolamien vasopressor in geselekteerde pediatriese skokpaaie — ICU-infusie met deurlopende monitering is vereis.",
      "Materia versin nie 'n mcg/kg/min infusietempo nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die ICU-span van hartritme kommer, feochromositoom geskiedenis indien bekend, en ALLE medisyne en vloeistowwe wat loop.",
      "Versorgers: vra watter bloeddruk- en urine-uitsetteikens die span dop en watter ledematskleurveranderinge hersiening moet sneller.",
      "Moenie tuis-infusiegebruik versin nie — dopamien bly slegs in kritieke sorg.",
      "As ledemaat koud en gevlek word, borspyn, of asemhaling versleg op infusie — waarsku die ICU-span onmiddellik.",
    ],
    [
      "Dopamine ke catecholamine vasopressor e sebelisoang litseleng tse khethiloeng tsa shock ho bana — infusion ea ICU le tlhokomelo e tsoelang pele e hlokahala.",
      "Materia ha e iqape lebelo la infusion la mcg/kg/min — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha sa ICU ka mathata a morethetho oa pelo, nalane ea pheochromocytoma haeba e tsejoa, le MERIANA EOHLE le mela e mathang.",
      "Bahlokomeli: botsa hore na ke lipheo life tsa khatello ea mali le moroto seo sehlopha se se shebelang le hore na liphetoho tsa mmala tsa matsoho le maoto li lokela ho qala tlhahlobo.",
      "U se ke ua iqape tšebeliso ea infusion ea lapeng — dopamine e lula feela critical care.",
      "Haeba letsoho le leoto li fela le li na le matheba, bohloko ba sefubeng, kapa ho hema ho mpefala infusion — tsebisa sehlopha sa ICU hang-hang.",
    ],
    [
      "I-dopamine yi-catecholamine vasopressor esetyenziswa kwiindlela ezikhethiweyo ze-shock kubantwana — ukugalela kwe-ICU kunye nokujonga okuqhubekayo kuyafuneka.",
      "I-Materia ayiyiqiqi izinga lokugalela le-mcg/kg/min — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela le-ICU ngeengxaki zesingqisho sentliziyo, imbali ye-pheochromocytoma ukuba iyaziwa, kunye NAWO ONKE amayeza neelwelo eziyasebenza.",
      "Abakhathaleli: buza ukuba zeziphi iinjongo zoxinzelelo lwegazi nomchamo iqela elijongayo nokuba utshintsho lombala lwezihlunu kufuneka kuqalise ukujongwa.",
      "Ungacingi ukusetyenziswa kokugalela ekhaya — i-dopamine ihlala kwi-critical care kuphela.",
      "Ukuba isihlunu siba sibandayo nesinamabala, intlungu yesifuba, okanye ukuphefumla kuba mbi ngexesha lokugalela — xelela iqela le-ICU ngoko nangoko.",
    ],
  ),

  "mol-dobutamine": five(
    [
      "Dobutamine is an inotrope used in selected paediatric heart-failure and low-cardiac-output pathways — ICU infusion with monitoring is required.",
      "Materia does not invent a mcg/kg/min infusion rate — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the ICU team about heart rhythm concerns, outflow-tract obstruction if known, and ALL medicines and fluids running.",
      "Caregivers: ask what heart-rate and blood-pressure checks are planned and what chest pain or new arrhythmia should trigger review.",
      "Do not invent home infusion use — dobutamine stays in critical care only.",
      "If fast irregular heartbeat, chest pain, or breathing worsens on the infusion — alert the ICU team immediately.",
    ],
    [
      "I-dobutamine i-inotrope esetshenziswa ezindleleni ezikhethiwe zokwehluleka kwenhliziyo nokuphuma okuphansi kwe-cardiac output ezinganeni — ukufaka emithanjeni kwe-ICU nokuqapha kuyadingeka.",
      "I-Materia ayiqambi izinga lokufaka le-mcg/kg/min — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba le-ICU ngezinkinga zesigqi senhliziyo, ukuvinjelwa kwe-outflow tract uma kaziwa, nawo WONKE amaphilisi namanzi ayagijima.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwesivinini senhliziyo namandla egazi okucwangisiwe nokuthi ubuhlungu besifuba noma i-arrhythmia entsha kufanele kuqale ukubuyekezwa.",
      "Ungacabangi ukusetshenziswa kokufaka emithanjeni ekhaya — i-dobutamine ihlala ku-critical care kuphela.",
      "Uma ukushaya kwenhliziyo okusheshayo okungahleliwe, ubuhlungu besifuba, noma ukuphefumula kuba kubi ngesikhathi sokufaka — xwayisa ithimba le-ICU ngokushesha.",
    ],
    [
      "Dobutamien is 'n inotroop in geselekteerde pediatriese hartversaking- en lae-hartuitsetpaaie — ICU-infusie met monitering is vereis.",
      "Materia versin nie 'n mcg/kg/min infusietempo nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die ICU-span van hartritme kommer, uitstroombaanobstruksie indien bekend, en ALLE medisyne en vloeistowwe wat loop.",
      "Versorgers: vra watter hartklop- en bloeddruktoetse beplan is en watter borspyn of nuwe aritmie hersiening moet sneller.",
      "Moenie tuis-infusiegebruik versin nie — dobutamien bly slegs in kritieke sorg.",
      "As vinnige onreëlmatige hartklop, borspyn, of asemhaling versleg op infusie — waarsku die ICU-span onmiddellik.",
    ],
    [
      "Dobutamine ke inotrope e sebelisoang litseleng tse khethiloeng tsa ho hloleha ha pelo le ho fokotseha ha cardiac output ho bana — infusion ea ICU le tlhokomelo e hlokahala.",
      "Materia ha e iqape lebelo la infusion la mcg/kg/min — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha sa ICU ka mathata a morethetho oa pelo, ho thibela ha outflow tract haeba ho tsejoa, le MERIANA EOHLE le mela e mathang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa ho otla ha pelo le khatello ea mali tse reriloeng le hore na bohloko ba sefubeng kapa arrhythmia e ncha e lokela ho qala tlhahlobo.",
      "U se ke ua iqape tšebeliso ea infusion ea lapeng — dobutamine e lula feela critical care.",
      "Haeba ho otla ha pelo ka potlako ho sa hlophiseheng, bohloko ba sefubeng, kapa ho hema ho mpefala infusion — tsebisa sehlopha sa ICU hang-hang.",
    ],
    [
      "I-dobutamine yi-inotrope esetyenziswa kwiindlela ezikhethiweyo zokusilela kwentliziyo nokuphuma okuphantsi kwe-cardiac output kubantwana — ukugalela kwe-ICU kunye nokujonga kuyafuneka.",
      "I-Materia ayiyiqiqi izinga lokugalela le-mcg/kg/min — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela le-ICU ngeengxaki zesingqisho sentliziyo, ukuvinjelwa kwe-outflow tract ukuba kuyaziwa, kunye NAWO ONKE amayeza neelwelo eziyasebenza.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zesantya sentliziyo noxinzelelo lwegazi ezicwangcisiweyo nokuba intlungu yesifuba okanye i-arrhythmia entsha kufuneka iqalise ukujongwa.",
      "Ungacingi ukusetyenziswa kokugalela ekhaya — i-dobutamine ihlala kwi-critical care kuphela.",
      "Ukuba ukubetha kwentliziyo okukhawulezayo okungahlelekanga, intlungu yesifuba, okanye ukuphefumla kuba mbi ngexesha lokugalela — xelela iqela le-ICU ngoko nangoko.",
    ],
  ),

  "mol-octreotide": five(
    [
      "Octreotide is a somatostatin analogue used in selected paediatric bleeding, fistula, and hormone-excess pathways — specialist oversight is typical.",
      "Materia does not invent a dose or infusion schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about diabetes, gallbladder disease, thyroid concerns, and ALL other medicines the child receives.",
      "Caregivers: ask whether injections or infusion are planned and what tummy pain, high blood sugar, or slow pulse should trigger review.",
      "Do not invent home injection timing — follow the specialist plan and labelled product.",
      "If severe tummy pain, yellow eyes, persistent vomiting, or breathing difficulty develops — seek care urgently.",
    ],
    [
      "I-octreotide i-somatostatin analogue esetshenziswa ezindleleni ezikhethiwe zokuphalala kwegazi, i-fistula, nokweqisa amahormone ezinganeni — ukuqapha kochwepheshe kujwayelekile.",
      "I-Materia ayiqambi umthamo noma uhlelo lokufaka emithanjeni — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba nge-diabetes, isifo sesinyeni, izinkinga ze-thyroid, nawo WONKE amanye amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi imijovo noma ukufaka emithanjeni kucwangisiwe yini nokuthi ubuhlungu besisu, i-shukera ephezulu, noma ukushaya kwenhliziyo okuphansi kufanele kuqale ukubuyekezwa.",
      "Ungacabangi isikhathi somjovo wasekhaya — landela uhlelo lochwepheshe nomkhiqizo onelebula.",
      "Uma ubuhlungu besisu obukhulu, amehlo aphuzi, ukuhlanza okuqhubekayo, noma ubunzima bokuphefumula kuvela — funa usizo ngokushesha.",
    ],
    [
      "Oktreotied is 'n somatostatin-analoog in geselekteerde pediatriese bloeding-, fistel-, en hormoon-oormaatpaaie — spesialistoesig is tipies.",
      "Materia versin nie 'n dosis of infusieskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van diabetes, galblaassiekte, skildklierkommer, en ALLE ander medisyne wat die kind ontvang.",
      "Versorgers: vra of inspuitings of infusie beplan is en watter maagpyn, hoë bloedsuiker, of stadige pols hersiening moet sneller.",
      "Moenie tuis-inspuitingtydsberekening versin nie — volg die spesialisplan en geëtiketteerde produk.",
      "As ernstige maagpyn, geel oë, aanhoudende braking, of asemnood ontwikkel — soek dringend sorg.",
    ],
    [
      "Octreotide ke somatostatin analogue e sebelisoang litseleng tse khethiloeng tsa ho tsoa mali, fistula, le ho fetela ha hormone ho bana — tlhokomelo ea setsebi e tloaelehile.",
      "Materia ha e iqape tekanyo kapa kemiso ea infusion — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka diabetes, lefu la sefubetsane, mathata a thyroid, le MERIANA EOHLE e meng eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ho kenya kapa infusion e reriloe le hore na bohloko ba mpa, suka ea mali e phahameng, kapa ho otla ha pelo ho fokotsehileng ho lokela ho qala tlhahlobo.",
      "U se ke ua iqape nako ea ente ea lapeng — latela moralo oa setsebi le sehlahisoa se nang le ileibole.",
      "Haeba bohloko bo boholo ba mpa, mahlo a mosehla, ho hlatsa ho tsoelang pele, kapa ho hema thata ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-octreotide yi-somatostatin analogue esetyenziswa kwiindlela ezikhethiweyo zokuphalala kwegazi, i-fistula, nokweqisa amahormone kubantwana — ukujongwa ngogcisa kuqhelekile.",
      "I-Materia ayiyiqiqi idosi okanye ishedyuli yokugalela — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela nge-diabetes, isifo sesinyeni, iingxaki ze-thyroid, kunye NAWO ONKE amanye amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba iindlela zokugalela okanye ukugalela zicwangcisiwe na nokuba intlungu yesisu, ikashukela ephezulu, okanye ukubetha kwentliziyo okuphantsi kufuneka kuqalise ukujongwa.",
      "Ungacingi ixesha lenaliti lasekhaya — landela isicwangciso sogcisa kunye nemveliso enelebula.",
      "Ukuba intlungu yesisu enzima, amehlo atyheli, ukugabha okuqhubekayo, okanye ubunzima bokuphefumla kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-zinc-sulfate": five(
    [
      "Zinc sulfate is used in selected paediatric diarrhoea and deficiency pathways — elemental zinc content and course length are clinician-set.",
      "Materia does not invent an elemental-mg dose or course length — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the clinician about other zinc supplements, copper deficiency concerns, and ALL medicines the child receives.",
      "Caregivers: ask how long to continue after diarrhoea improves and what vomiting or refusal to drink should trigger review.",
      "Do not double zinc products from the shop without the team — overlap can cause imbalance.",
      "If persistent vomiting, no urine, lethargy, or bloody diarrhoea develops — seek care urgently.",
    ],
    [
      "I-zinc sulfate isetshenziswa ezindleleni ezikhethiwe zokuhlanza nokwehluleka kwe-zinc ezinganeni — okuqukethwe kwe-elemental zinc nobude benkambo kubekwa odokotela.",
      "I-Materia ayiqambi umthamo we-elemental-mg noma ubude benkambo — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngezinye izinsiza ze-zinc, izinkinga zokwehluleka kwe-copper, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi uqhubeka isikhathi esingakanani ngemva kokuthi ukuhlanza kuthuthuke nokuthi ukuhlanza noma ukwenqaba ukuphuza kufanele kuqale ukubuyekezwa.",
      "Ungaphindi imikhiqizo ye-zinc esitolo ngaphandle kwethimba — ukuphindaphinda kungadala ukungalingani.",
      "Uma ukuhlanza okuqhubekayo, umchamo omncane, ukudangala, noma ukuhlanza kwegazi kuvela — funa usizo ngokushesha.",
    ],
    [
      "Sink sulfaat word in geselekteerde pediatriese diarree- en tekortpaaie gebruik — elementêre sinkinhoud en kursuslengte word deur klinici gestel.",
      "Materia versin nie 'n elementêre-mg dosis of kursuslengte nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van ander sinkaanvullings, koper tekort kommer, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra hoe lank om voort te gaan nadat diarree verbeter en watter braking of weiering om te drink hersiening moet sneller.",
      "Moenie sink produkte uit die winkel verdubbel sonder die span nie — oorvleueling kan wanbalans veroorsaak.",
      "As aanhoudende braking, geen urine, lethargie, of bloederige diarree ontwikkel — soek dringend sorg.",
    ],
    [
      "Zinc sulfate e sebelisoa litseleng tse khethiloeng tsa letshollo le ho hloka zinc ho bana — zinc ea elemental le bolelele ba thuto li behwa ke lingaka.",
      "Materia ha e iqape tekanyo ea elemental-mg kapa bolelele ba thuto — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka lithuso tse ling tsa zinc, mathata a ho hloka copper, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na u tsoela pele nako e kae ka mor'a hore letshollo le ntlafale le hore na ho hlatsa kapa ho hana ho noa ho lokela ho qala tlhahlobo.",
      "U se ke ua eketsa lihlahisoa tsa zinc lebenkeleng ntle le sehlopha — ho kopanya ho ka baka ho se lekalekane.",
      "Haeba ho hlatsa ho tsoelang pele, ha ho moroto, ho iketla, kapa letshollo le mali le hlaha — batla thuso ka potlako.",
    ],
    [
      "I-zinc sulfate isetyenziswa kwiindlela ezikhethiweyo zorhudo nokusilela kwe-zinc kubantwana — okuqukethwe kwe-elemental zinc nobude bekhosi kubekwa ngogqirha.",
      "I-Materia ayiyiqiqi idosi ye-elemental-mg okanye ubude bekhosi — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngezinye izongezelelo ze-zinc, iingxaki zokusilela kwe-copper, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba uqhubeka ixesha elingakanani emva kokuba urhudo luphucuke nokuba ukugabha okanye ukwala ukusela kufuneka kuqalise ukujongwa.",
      "Ungaphindi iimveliso ze-zinc evenkileni ngaphandle kweqela — ukuphindaphinda kunokudala ukungalingani.",
      "Ukuba ukugabha okuqhubekayo, akukho mchamo, ukudinwa, okanye urhudo lwegazi kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-sodium-bicarbonate": five(
    [
      "Sodium bicarbonate is used in selected paediatric acidosis and alkalinisation pathways — electrolyte and fluid balance are ICU or specialist-led.",
      "Materia does not invent a mmol/kg dose or infusion rate — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about heart disease, kidney disease, low calcium, and ALL fluids and medicines running.",
      "Caregivers: ask what blood-gas and electrolyte checks are planned and what muscle twitching or confusion should trigger review.",
      "Do not invent home alkalinisation — bicarbonate stays under clinical oversight.",
      "If severe breathing difficulty, seizures, or marked confusion develops — seek emergency care immediately.",
    ],
    [
      "I-sodium bicarbonate isetshenziswa ezindleleni ezikhethiwe ze-acidosis nokwenza i-alkali ezinganeni — ukulingana kwe-electrolyte namanzi kuqhutshwa yi-ICU noma ochwepheshe.",
      "I-Materia ayiqambi umthamo we-mmol/kg noma izinga lokufaka — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngesifo senhliziyo, isifo sezinso, i-calcium ephansi, nawo WONKE amanzi namaphilisi ayagijima.",
      "Abanakekeli: buza ukuthi yimaphi ukuhlolwa kwegazi legazi nezinto ze-electrolyte okucwangisiwe nokuthi ukuthuthumela kwezihlunu noma ukudideka kufanele kuqale ukubuyekezwa.",
      "Ungacabangi ukwenza i-alkali ekhaya — i-bicarbonate ihlala ngaphansi kokuqapha kwezokwelapha.",
      "Uma ubunzima bokuphefumula obukhulu, ukuxega, noma ukudideka okukhulu kuvela — funa usizo oluphuthumayo ngokushesha.",
    ],
    [
      "Natrium bikarbonaat word in geselekteerde pediatriese asidose- en alkaliniseringpaaie gebruik — elektroliet- en vloeistofbalans is ICU- of spesialis-gelei.",
      "Materia versin nie 'n mmol/kg dosis of infusietempo nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van hartsiekte, niersiekte, lae kalsium, en ALLE vloeistowwe en medisyne wat loop.",
      "Versorgers: vra watter bloedgass- en elektroliettoetse beplan is en watter spierbewing of verwarring hersiening moet sneller.",
      "Moenie tuis-alkalinisering versin nie — bikarbonaat bly onder kliniese toesig.",
      "As ernstige asemnood, aanvalle, of merkbare verwarring ontwikkel — soek onmiddellik noodgeval sorg.",
    ],
    [
      "Sodium bicarbonate e sebelisoa litseleng tse khethiloeng tsa acidosis le alkalinisation ho bana — ho lekana ha electrolyte le mela ho etelloa pele ke ICU kapa setsebi.",
      "Materia ha e iqape tekanyo ea mmol/kg kapa lebelo la infusion — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka lefu la pelo, lefu la liphio, calcium e tlase, le MELA EOHLE le MERIANA EOHLE e mathang.",
      "Bahlokomeli: botsa hore na ke liteko life tsa moea oa mali le electrolyte tse reriloeng le hore na ho thothomela ha mesifa kapa ho hlakisoa ho lokela ho qala tlhahlobo.",
      "U se ke ua iqape alkalinisation ea lapeng — bicarbonate e sala tlas'a tlhokomelo ea bongaka.",
      "Haeba ho hema thata ho matla, ho thothomela, kapa ho hlakisoa ho hlakileng ho hlaha — batla thuso ea tšohanyetso hang-hang.",
    ],
    [
      "I-sodium bicarbonate isetyenziswa kwiindlela ezikhethiweyo ze-acidosis nokwenza i-alkali kubantwana — ukulingana kwe-electrolyte neelwelo kukhokelwa yi-ICU okanye ngogcisa.",
      "I-Materia ayiyiqiqi idosi ye-mmol/kg okanye izinga lokugalela — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngesifo sentliziyo, isifo sezintso, i-calcium ephantsi, kunye NAWO ONKE iilwelo namayeza eziyasebenza.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zegesi legazi nee-electrolyte ezicwangcisiweyo nokuba ukungcangcazela kwemisipha okanye ukudideka kufuneka kuqalise ukujongwa.",
      "Ungacingi ukwenza i-alkali ekhaya — i-bicarbonate ihlala phantsi kokujonga kwezonyango.",
      "Ukuba ubunzima bokuphefumla obukhulu, ukuxhuzula, okanye ukudideka okucacileyo kuvela — funa uncedo olungxamisekileyo ngoko nangoko.",
    ],
  ),

  "mol-silver-sulfadiazine": five(
    [
      "Silver sulfadiazine is a topical sulfonamide used in selected paediatric burn and wound pathways — it is not for mouth or eye use unless labelled.",
      "Materia does not invent an application thickness or dressing schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about sulfa allergy, G6PD status if known, large burn area, and ALL other wound products.",
      "Caregivers: ask how often dressings change, what increasing redness or pus should trigger review, and pain-control plans.",
      "Do not invent home burn creams on top of the prescribed regimen — overlap can hide infection.",
      "If spreading redness, high fever, breathing difficulty, or severe rash develops — seek care urgently.",
    ],
    [
      "I-silver sulfadiazine i-sulfonamide yokufaka esetshenziswa ezindleleni ezikhethiwe zokusha namanxeba ezinganeni — ayifanele umlomo noma amehlo ngaphandle kwalebula.",
      "I-Materia ayiqambi ubukhulu bokufaka noma uhlelo lokushintsha i-dressing — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba nge-allergy ye-sulfa, isimo se-G6PD uma saziwa, indawo enkulu yokusha, nawo WONKE amanye amikhiqizo amanxeba.",
      "Abanakekeli: buza ukuthi i-dressing ishintshwa kangaki, ukubomvu okwandayo noma i-pus kufanele kuqale ukubuyekezwa nini, nezinhlelo zokulwa nobuhlungu.",
      "Ungacabangi ama-cream okusha asekhaya phezu kohlelo olubhaliwe — ukuphindaphinda kungafihla isifo.",
      "Uma ukubomvu okusabalalayo, umkhuhlane omkhulu, ubunzima bokuphefumula, noma ukuqubuka okukhulu kuvela — funa usizo ngokushesha.",
    ],
    [
      "Silwer sulfadiazien is 'n topiese sulfonamied in geselekteerde pediatriese brandwond- en wondpaaie — dit is nie vir mond of oog gebruik tensy geëtiketteer nie.",
      "Materia versin nie 'n aanwendingdikte of verbandskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van sulfa-allergie, G6PD-status indien bekend, groot brandwondarea, en ALLE ander wondprodukte.",
      "Versorgers: vra hoe gereeld verbande verander, watter toenemende rooiness of pus hersiening moet sneller, en pynbeheerplanne.",
      "Moenie tuis-brandwond-smeersels bo-op die voorgeskrewe regime versin nie — oorvleueling kan infeksie verberg.",
      "As spreidende rooiness, hoë koors, asemnood, of ernstige uitslag ontwikkel — soek dringend sorg.",
    ],
    [
      "Silver sulfadiazine ke sulfonamide ea letlalo e sebelisoang litseleng tse khethiloeng tsa ho checha le liwound ho bana — ha e loketse molomo kapa mahlo ntle le ha e na le ileibole.",
      "Materia ha e iqape botebo ba ho kenya kapa kemiso ea ho fetola liaparo — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka allergy ea sulfa, boemo ba G6PD haeba bo tsejoa, sebaka se seholo sa ho checha, le LIHLAHISOA TSOHLE tse ling tsa wound.",
      "Bahlokomeli: botsa hore na liaparo li fetoloa hang hang le hore na ho kgubedu ha ho eketsehang kapa pus ho lokela ho qala tlhahlobo le morero oa ho laola bohloko.",
      "U se ke ua iqape li-cream tsa ho checha tsa lapeng holim'a kemiso e ngoliloeng — ho kopanya ho ka pata tšoaetso.",
      "Haeba ho kgubedu ho hasanang, feberu e phahameng, ho hema thata, kapa lekhopho le matla le hlaha — batla thuso ka potlako.",
    ],
    [
      "I-silver sulfadiazine yi-sulfonamide yokufaka esetyenziswa kwiindlela ezikhethiweyo zokutsha namanxeba kubantwana — ayifanele umlomo okanye amehlo ngaphandle kwalebhile.",
      "I-Materia ayiyiqiqi ubunzulu bokufaka okanye ishedyuli yokutshintsha i-dressing — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela nge-allergy ye-sulfa, imeko ye-G6PD ukuba iyaziwa, indawo enkulu yokutsha, kunye NAWO ONKE ezinye iimveliso zamanxeba.",
      "Abakhathaleli: buza ukuba iidressing zitshintshwa kangaki, ukubomvu okwandayo okanye i-pus kufuneka iqalise ukujongwa nini, nezicwangciso zokulwa nentlungu.",
      "Ungacingi iikrema zokutsha zasekhaya phezu kwenkqubo ebhalisiweyo — ukuphindaphinda kunokufihla usulelo.",
      "Ukuba ukubomvu okusasazekayo, umkhuhlane omkhulu, ubunzima bokuphefumla, okanye irhashalala enzima kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-valganciclovir": five(
    [
      "Valganciclovir is an oral prodrug used in selected paediatric CMV pathways — kidney function and blood-count monitoring are clinician-led.",
      "Materia does not invent a mg/kg dose or induction/maintenance switch — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about kidney disease, low blood counts, pregnancy concerns in adolescents handling tablets, and ALL other medicines.",
      "Caregivers: ask what blood tests are planned and what fever, mouth ulcers, or unusual bruising should trigger earlier review.",
      "Take with food if the labelled product advises — do not invent crushing rules that conflict with the pharmacy plan.",
      "If fever with sore throat, unusual bleeding, severe tiredness, or reduced urine develops — seek care urgently.",
    ],
    [
      "I-valganciclovir i-prodrug yomlomo esetshenziswa ezindleleni ezikhethiwe ze-CMV ezinganeni — ukusebenza kwezinso nokuqapha ukubalwa kwegazi kuqhutshwa odokotela.",
      "I-Materia ayiqambi umthamo we-mg/kg noma ukushintsha kokusuka kokusindisa kokugcina — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba ngesifo sezinso, ukubalwa kwegazi okuphansi, ukukhulelwa kwezentsha eziphatha amaphilisi, nawo WONKE amanye amaphilisi.",
      "Abanakekeli: buza ukuthi yiziphi izivivinyo zegazi ezicwangisiwe nokuthi umkhuhlane, izilonda zomlomo, noma ukulimala okungajwayelekile kufanele kuqale ukubuyekezwa.",
      "Thatha nokudla uma umkhiqizo onelebula ucebisa — ungacabangi imithetho yokucindezela ephikisana nohlelo lwe-pharmacy.",
      "Uma umkhuhlane nomphimbo obuhlungu, ukopha okungajwayelekile, ukukhathala okukhulu, noma umchamo omncane kuvela — funa usizo ngokushesha.",
    ],
    [
      "Valgansiklovir is 'n mondelike prodrug in geselekteerde pediatriese CMV-paaie — niersfunksie en bloedtelling monitering is klinikus-gelei.",
      "Materia versin nie 'n mg/kg dosis of induksie/instandhouding wissel nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van niersiekte, lae bloedtellings, swangerskapkommer by adolessente wat tablette hanteer, en ALLE ander medisyne.",
      "Versorgers: vra watter bloedtoetse beplan is en watter koors, mondsere, of ongewone kneusings vroeër hersiening moet sneller.",
      "Neem met kos as die geëtiketteerde produk dit aanbeveel — moenie fyndrukreëls versin wat met die apteekplan bots nie.",
      "As koors met seer keel, ongewone bloeding, ernstige moegheid, of verminderde urine ontwikkel — soek dringend sorg.",
    ],
    [
      "Valganciclovir ke prodrug ea molomo e sebelisoang litseleng tse khethiloeng tsa CMV ho bana — ts'ebetso ea liphio le tlhokomelo ea palo ea mali e etelloa pele ke lingaka.",
      "Materia ha e iqape tekanyo ea mg/kg kapa ho fetola ho tloha ho qala ho ea ho boloka — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka lefu la liphio, lipalo tse tlase tsa mali, mathata a bokhachane ho bacha ba sebetsanang le li-tablet, le MERIANA EOHLE e meng.",
      "Bahlokomeli: botsa hore na ke liteko life tsa mali tse reriloeng le hore na feberu, lisoa tsa molomo, kapa ho otlaha ho sa tloaelehang ho lokela ho qala tlhahlobo pele.",
      "E nke le lijo haeba sehlahisoa se nang le ileibole se eletsa — u se ke ua iqapa melao a ho sila a loantšanang le moralo oa pharmacy.",
      "Haeba feberu le 'metso o bohloko, ho tsoa mali ho sa tloaelehang, mokhathala o matla, kapa moroto o fokotsehileng o hlaha — batla thuso ka potlako.",
    ],
    [
      "I-valganciclovir yi-prodrug yomlomo esetyenziswa kwiindlela ezikhethiweyo ze-CMV kubantwana — ukusebenza kwezintso nokujonga ukubalwa kwegazi kukhokelwa ngoogqirha.",
      "I-Materia ayiyiqiqi idosi ye-mg/kg okanye utshintsho lokuqala/ukugcina — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela ngesifo sezintso, ukubalwa kwegazi okuphantsi, iinkxalabo zokukhulelwa kulutsha oluphethe amapilisi, kunye NAWO ONKE amanye amayeza.",
      "Abakhathaleli: buza ukuba zeziphi iimvavanyo zegazi ezicwangcisiweyo nokuba umkhuhlane, izilonda zomlomo, okanye ukulimala okungaqhelekanga kufuneka kuqalise ukujongwa kwangethuba.",
      "Thatha nokutya ukuba imveliso enelebula icebisa — ungacingi imithetho yokucinezelela ephikisana nesicwangciso sepharmacy.",
      "Ukuba umkhuhlane nomqala obuhlungu, ukopha okungaqhelekanga, ukudinwa okukhulu, okanye umchamo omncinci kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-rifabutin": five(
    [
      "Rifabutin is a rifamycin used in selected paediatric MAC and TB prophylaxis pathways — drug interactions and eye-colour changes are teaching points.",
      "Materia does not invent a dose or interaction list — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the TB or infectious-disease team about HIV medicines, other rifamycins, eye inflammation history, and ALL medicines the child receives.",
      "Caregivers: ask what interactions to avoid and what orange body fluids, eye pain, or rash should trigger review.",
      "Take on the schedule the TB team sets — do not invent spacing rules that conflict with antiretrovirals.",
      "If severe eye pain, vision change, jaundice, or rash with fever develops — seek care urgently.",
    ],
    [
      "I-rifabutin i-rifamycin esetshenziswa ezindleleni ezikhethiwe ze-MAC ne-TB prophylaxis ezinganeni — ukuxhumana kwamaphilisi nokushintsha kombala kwamehlo yizinto zokufundisa.",
      "I-Materia ayiqambi umthamo noma uhlu lokuxhumana — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba le-TB noma lezifo ezithathelanayo ngamaphilisi e-HIV, amanye ama-rifamycin, umlando wokuvuvuka kwamehlo, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi yiziphi izixhumanisi okufanele zigwenywe nokuthi amanzi omzimba aphuzi, ubuhlungu bamehlo, noma ukuqubuka kufanele kuqale ukubuyekezwa.",
      "Thatha ngeshedyuli ithimba le-TB eliyibekayo — ungacabangi imithetho yokuhlukanisa ephikisana nama-antiretroviral.",
      "Uma ubuhlungu bamehlo obukhulu, ukushintsha kokubona, i-jaundice, noma ukuqubuka nomkhuhlane kuvela — funa usizo ngokushesha.",
    ],
    [
      "Rifabutien is 'n rifamisien in geselekteerde pediatriese MAC- en TB-profilakse paaie — middelinteraksies en oogkleurveranderinge is onderrigpunte.",
      "Materia versin nie 'n dosis of interaksielys nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die TB- of infeksiesiekte-span van HIV-medisyne, ander rifamisienne, oogontsteking geskiedenis, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra watter interaksies om te vermy en watter oranje liggaamvloeistowwe, oogpyn, of uitslag hersiening moet sneller.",
      "Neem op die skedule wat die TB-span stel — moenie spasiëringsreëls versin wat met antiretrovirale bots nie.",
      "As ernstige oogpyn, sigverandering, geelsug, of uitslag met koors ontwikkel — soek dringend sorg.",
    ],
    [
      "Rifabutin ke rifamycin e sebelisoang litseleng tse khethiloeng tsa MAC le TB prophylaxis ho bana — ho kopanya ha meriana le liphetoho tsa mmala wa mahlo ke lintlha tsa thuto.",
      "Materia ha e iqape tekanyo kapa lenaneo la ho kopanya — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha sa TB kapa sa mafu a tšoaetsanoang ka meriana ea HIV, li-rifamycin tse ling, nalane ea ho vuvuka ha mahlo, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na ke likopano life tse lokelang ho qheleloa le hore na metsi a mmele a mofubelu, bohloko ba mahlo, kapa lekhopho li lokela ho qala tlhahlobo.",
      "E nke ka kemiso eo sehlopha sa TB se e behang — u se ke ua iqapa melao a ho arohana a loantšanang le li-antiretroviral.",
      "Haeba bohloko bo boholo ba mahlo, phetoho ea pono, jaundice, kapa lekhopho le feberu li hlaha — batla thuso ka potlako.",
    ],
    [
      "I-rifabutin yi-rifamycin esetyenziswa kwiindlela ezikhethiweyo ze-MAC ne-TB prophylaxis kubantwana — ukudibanisa kwamayeza nokutshintsha kombala kwamehlo ziindawo zokufundisa.",
      "I-Materia ayiyiqiqi idosi okanye uluhlu lokudibanisa — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela le-TB okanye lezifo ezosulelayo ngamayeza e-HIV, ezinye ii-rifamycin, imbali yokuvuvuka kwamehlo, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba zeziphi iindibaniso ekufuneka zigwenywe nokuba iilwelo zomzimba ezibomvu, intlungu yamehlo, okanye irhashalala kufuneka kuqalise ukujongwa.",
      "Thatha ngexesha iqela le-TB elibekayo — ungacingi imithetho yokuhlula ephikisana nee-antiretroviral.",
      "Ukuba intlungu yamehlo enzima, utshintsho lokubona, i-jaundice, okanye irhashalala nomkhuhlane kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-macrogol": five(
    [
      "Macrogol is a PEG-based laxative used in selected paediatric constipation and disimpaction pathways — hydration and stool pattern guide the plan.",
      "Materia does not invent a sachet dose or disimpaction schedule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the clinician about tummy pain, vomiting, blood in stool, neurological conditions, and ALL medicines the child receives.",
      "Caregivers: ask how to mix sachets, what stool pattern is expected, and when to return if no stool passes or pain worsens.",
      "Do not add other laxatives from the shop without the team — overlap can cause dehydration and electrolyte upset.",
      "If severe tummy pain, vomiting, no stool with distended tummy, or blood in stool develops — seek care urgently.",
    ],
    [
      "I-macrogol i-laxative esekwe ku-PEG esetshenziswa ezindleleni ezikhethiwe zokungajiki nokukhipha izimpuphu ezinganeni — ukuhlala unamanzi nesimo sokuphalaza kuqondisa uhlelo.",
      "I-Materia ayiqambi umthamo we-sachet noma uhlelo lokukhipha izimpuphu — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela udokotela ngobuhlungu besisu, ukuhlanza, igazi esitobhini, izimo zezinzwa, nawo WONKE amaphilisi umntwana awatholayo.",
      "Abanakekeli: buza ukuthi kuxutshwa kanjani ama-sachet, yisiphi isimo sokuphalaza esilindelekile, nokuthi ubuyela nini uma kungaphumi isitobhi noma ubuhlungu buya emuva.",
      "Ungangezi amanye ama-laxative esitolo ngaphandle kwethimba — ukuphindaphinda kungadala ukoma nokuphazamiseka kwe-electrolyte.",
      "Uma ubuhlungu besisu obukhulu, ukuhlanza, isitobhi esingaphumi nesisu esivuvukile, noma igazi esitobhini kuvela — funa usizo ngokushesha.",
    ],
    [
      "Makrogol is 'n PEG-gebaseerde lakseermiddel in geselekteerde pediatriese hardlyheid- en disimpaksiepaaie — hidrasie en stoelgangpatroon lei die plan.",
      "Materia versin nie 'n sakkie dosis of disimpaksieskedule nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die klinikus van maagpyn, braking, bloed in stoelgang, neurologiese toestande, en ALLE medisyne wat die kind ontvang.",
      "Versorgers: vra hoe om sakkies te meng, watter stoelgangpatroon verwag word, en wanneer om terug te kom as geen stoelgang nie of pyn versleg.",
      "Moenie ander lakseermiddels uit die winkel byvoeg sonder die span nie — oorvleueling kan dehidrasie en elektrolietversteuring veroorsaak.",
      "As ernstige maagpyn, braking, geen stoelgang met opgeblase maag, of bloed in stoelgang ontwikkel — soek dringend sorg.",
    ],
    [
      "Macrogol ke laxative e thehiloeng ho PEG e sebelisoang litseleng tse khethiloeng tsa ho tšoaroa le ho tlosa li-impaction ho bana — ho nela metsi le mokhoa oa ho etsa mala o tataisa moralo.",
      "Materia ha e iqape tekanyo ea sachet kapa kemiso ea ho tlosa li-impaction — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella ngaka ka bohloko ba mpa, ho hlatsa, mali mabung, maemo a boko, le MERIANA EOHLE eo ngoana a e fumanang.",
      "Bahlokomeli: botsa hore na li-sachet li kopanngoa joang, ke mokhoa ofe oa ho etsa mala o lebelloang, le hore na u khutle neng haeba ha ho mala kapa bohloko bo mpefala.",
      "U se ke ua eketsa li-laxative tse ling lebenkeleng ntle le sehlopha — ho kopanya ho ka baka ho omella le ho senya electrolyte.",
      "Haeba bohloko bo boholo ba mpa, ho hlatsa, ha ho mala le mpa e pharaletseng, kapa mali mabung e hlaha — batla thuso ka potlako.",
    ],
    [
      "I-macrogol yilaxative esekwe ku-PEG esetyenziswa kwiindlela ezikhethiweyo zokungajiki nokukhipha izimpuphu kubantwana — ukunxiliswa kwamanzi kunye nepateni yokuphalaza zikhokela isicwangciso.",
      "I-Materia ayiyiqiqi idosi ye-sachet okanye ishedyuli yokukhipha izimpuphu — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela ugqirha ngentlungu yesisu, ukugabha, igazi esitobhini, iimeko zentsholo, kunye NAWO ONKE amayeza umntwana awafumanayo.",
      "Abakhathaleli: buza ukuba iisachet zixutywa njani, yeyiphi ipateni yokuphalaza elindelekileyo, nokuba ubuyela nini ukuba akukho sitobhi okanye intlungu iba mbi.",
      "Ungongeze ezinye ii-laxative evenkileni ngaphandle kweqela — ukuphindaphinda kunokudala ukoma nokuphazamiseka kwe-electrolyte.",
      "Ukuba intlungu yesisu enzima, ukugabha, sitobhi esingaphumi nesisu esidumbileyo, okanye igazi esitobhini kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),

  "mol-sulfadiazine": five(
    [
      "Sulfadiazine is a sulfonamide used in selected paediatric toxoplasmosis pathways — often paired with pyrimethamine under specialist oversight.",
      "Materia does not invent a mg/kg dose or pyrimethamine pairing rule — confirm against current SA Paediatric STG/EML and the labelled product.",
      "Tell the team about sulfa allergy, G6PD status if known, kidney disease, and ALL other medicines including folinic acid if prescribed.",
      "Caregivers: ask how long the course runs, what folinic acid or monitoring is planned, and what rash or mouth ulcers should trigger review.",
      "Finish the full course the infectious-disease team sets — do not invent stop rules when the child feels better.",
      "If rash with fever, dark urine, severe tiredness, or breathing difficulty develops — seek care urgently.",
    ],
    [
      "I-sulfadiazine i-sulfonamide esetshenziswa ezindleleni ezikhethiwe ze-toxoplasmosis ezinganeni — ivamile ukubanjwa ne-pyrimethamine ngaphansi kokuqapha kochwepheshe.",
      "I-Materia ayiqambi umthamo we-mg/kg noma umthetho wokubhanjiswa ne-pyrimethamine — qinisekisa ne-STG/EML yezingane yaseNingizimu Afrika yamanje nomkhiqizo onelebula.",
      "Tshela ithimba nge-allergy ye-sulfa, isimo se-G6PD uma saziwa, isifo sezinso, nawo WONKE amanye amaphilisi kufaka ne-folinic acid uma kubhaliwe.",
      "Abanakekeli: buza ukuthi inkambo iqhubeka isikhathi esingakanani, yiluphi u-folinic acid noma ukuqapha okucwangisiwe, nokuthi ukuqubuka noma izilonda zomlomo kufanele kuqale ukubuyekezwa.",
      "Qedela inkambo ephelele ithimba lezifo ezithathelanayo eliyibekayo — ungacabangi imithetho yokuyeka lapho umntwana ezizwa ungcono.",
      "Uma ukuqubuka nomkhuhlane, umchamo omnyama, ukukhathala okukhulu, noma ubunzima bokuphefumula kuvela — funa usizo ngokushesha.",
    ],
    [
      "Sulfadiazien is 'n sulfonamied in geselekteerde pediatriese toxoplasmosis-paaie — dikwels saamgebind met pirimetamien onder spesialistoesig.",
      "Materia versin nie 'n mg/kg dosis of pirimetamien-bindingsreël nie — bevestig teen huidige SA Pediatriese STG/EML en die geëtiketteerde produk.",
      "Sê vir die span van sulfa-allergie, G6PD-status indien bekend, niersiekte, en ALLE ander medisyne insluitend foliensuur indien voorgeskryf.",
      "Versorgers: vra hoe lank die kursus loop, watter foliensuur of monitering beplan is, en watter uitslag of mondsere hersiening moet sneller.",
      "Voltooi die volle kursus wat die infeksiesiekte-span stel — moenie stopreëls versin wanneer die kind beter voel nie.",
      "As uitslag met koors, donker urine, ernstige moegheid, of asemnood ontwikkel — soek dringend sorg.",
    ],
    [
      "Sulfadiazine ke sulfonamide e sebelisoang litseleng tse khethiloeng tsa toxoplasmosis ho bana — hangata e kopanyoa le pyrimethamine tlas'a tlhokomelo ea setsebi.",
      "Materia ha e iqape tekanyo ea mg/kg kapa molao oa ho kopanya le pyrimethamine — netefatsa khahlanong le STG/EML ea bana ea SA le sehlahisoa se nang le ileibole.",
      "Bolella sehlopha ka allergy ea sulfa, boemo ba G6PD haeba bo tsejoa, lefu la liphio, le MERIANA EOHLE e meng ho kenyeletsoa folinic acid haeba e ngoliloe.",
      "Bahlokomeli: botsa hore na thuto e tsamaea nako e kae, ke folinic acid kapa tlhokomelo efe e reriloeng, le hore na lekhopho kapa lisoa tsa molomo li lokela ho qala tlhahlobo.",
      "Qetella thuto e felletseng eo sehlopha sa mafu a tšoaetsanoang se e behang — u se ke ua iqapa melao a ho emisa ha ngoana a ikutloa u le betere.",
      "Haeba lekhopho le feberu, moroto o lefifi, mokhathala o matla, kapa ho hema thata ho hlaha — batla thuso ka potlako.",
    ],
    [
      "I-sulfadiazine yi-sulfonamide esetyenziswa kwiindlela ezikhethiweyo ze-toxoplasmosis kubantwana — rhoqo ibambiswa ne-pyrimethamine phantsi kokujongwa ngogcisa.",
      "I-Materia ayiyiqiqi idosi ye-mg/kg okanye umthetho wokubambisana ne-pyrimethamine — Qinisekisa ne-STG/EML yabantwana yaseMzantsi Afrika yangoku kunye nemveliso enelebula.",
      "Xelela iqela nge-allergy ye-sulfa, imeko ye-G6PD ukuba iyaziwa, isifo sezintso, kunye NAWO ONKE amanye amayeza kuquka i-folinic acid ukuba ibhaliwe.",
      "Abakhathaleli: buza ukuba ikhosi iqhuba ixesha elingakanani, yeyiphi i-folinic acid okanye ukujonga okucwangcisiweyo, nokuba irhashalala okanye izilonda zomlomo kufuneka kuqalise ukujongwa.",
      "Gqiba ikhosi epheleleyo iqela lezifo ezosulelayo eliyibekayo — ungacingi imithetho yokuyeka xa umntwana eziva ungcono.",
      "Ukuba irhashalala nomkhuhlane, umchamo omnyama, ukudinwa okukhulu, okanye ubunzima bokuphefumla kuvela — funa uncedo ngokukhawuleza.",
    ],
  ),
};
